using Microsoft.Extensions.DependencyInjection;
using SharedMeta.Core;
using SharedMeta.Server.Core;
using SharedMeta.Test.Meta1;
using SharedMeta.Test.Meta1.Server;

namespace SharedMeta.Test.Server;

/// <summary>
/// Test server configuration — uses fully generated server code.
/// All providers, resolvers, and validators are auto-generated by SharedMeta.Generator.
/// </summary>
public static class TestServerConfiguration
{
    /// <summary>
    /// Shared migration config provider instance — tests adjust CurrentVersion to control
    /// which migration steps fire. Safe because tests in the TestCluster collection are
    /// sequential (xunit collection fixture).
    /// </summary>
    public static readonly TestMigrationConfigProvider MigrationConfigProvider =
        new TestMigrationConfigProvider(new MetaConfigVersion(1, 0));

    /// <summary>
    /// Register all test meta services using generated ConfigureMeta.
    /// </summary>
    public static IServiceCollection ConfigureTestMeta(
        this IServiceCollection services,
        Action<IServiceCollection>? configureServices = null)
    {
        services.AddSingleton<IMetaConfigProvider<MigrationConfig>>(MigrationConfigProvider);
        // 0.20.0 multi-config sibling test fixture: AltConfigService declares ConfigType =
        // typeof(CounterAltConfig). Generated Get{Iface}SiblingAsync() resolves this provider
        // via Context.ResolveService → DI lookup. Without this registration the sibling-async
        // path throws when called from a multi-config sibling test.
        services.AddSingleton<IMetaConfigProvider<CounterAltConfig>>(new TestCounterAltConfigProvider());
        return services.ConfigureMeta(configureServices);
    }
}

/// <summary>
/// Trivial static provider for <see cref="CounterAltConfig"/> — returns the same instance
/// regardless of version. Tests rely on the default <c>MaxValue=7777</c> to verify the sibling
/// saw the alt config rather than the primary <c>CounterConfig</c>.
/// </summary>
public class TestCounterAltConfigProvider : IMetaConfigProvider<CounterAltConfig>
{
    private readonly CounterAltConfig _instance = new() { MaxValue = 7777 };
    public MetaConfigVersion CurrentVersion => new(1, 0);
    public CounterAltConfig GetConfig(MetaConfigVersion version) => _instance;
}

/// <summary>
/// Controllable config provider for MigrationTests. Tests set
/// <see cref="CurrentVersion"/> to simulate a config rollout advancing to a new version.
/// <see cref="GetConfig"/> always returns a MigrationConfig whose Major/Minor reflect
/// the requested version — so [MetaInit] can record which version was pinned to each step.
/// </summary>
public class TestMigrationConfigProvider : IMetaConfigProvider<MigrationConfig>
{
    private MetaConfigVersion _currentVersion;

    public TestMigrationConfigProvider(MetaConfigVersion initialVersion)
        => _currentVersion = initialVersion;

    public MetaConfigVersion CurrentVersion => _currentVersion;

    public void SetVersion(MetaConfigVersion v) => _currentVersion = v;
    public void SetVersion(int major, int minor) => _currentVersion = new MetaConfigVersion(major, minor);

    public MigrationConfig GetConfig(MetaConfigVersion version) => new MigrationConfig
    {
        Major = version.Major,
        Minor = version.Minor,
        Label = $"{version.Major}.{version.Minor}"
    };
}
