using Microsoft.Extensions.DependencyInjection;
using SharedMeta.Core;
using SharedMeta.Server.Core;
using SharedMeta.Test.Meta1;
using SharedMeta.Test.Meta1.Server;

namespace SharedMeta.Test.Server;

/// <summary>
/// Test server configuration — uses fully generated server code.
/// All providers, resolvers, and validators are auto-generated by SharedMeta.Generator.
/// </summary>
public static class TestServerConfiguration
{
    /// <summary>
    /// Shared migration config provider instance — tests adjust CurrentVersion to control
    /// which migration steps fire. Safe because tests in the TestCluster collection are
    /// sequential (xunit collection fixture).
    /// </summary>
    public static readonly TestMigrationConfigProvider MigrationConfigProvider =
        new TestMigrationConfigProvider(new MetaConfigVersion(1, 0));

    /// <summary>
    /// Per-test-class controllable resolver. Tests set <see cref="CurrentClientVersion"/>
    /// to simulate the server's "default client version" used by server-internal callers and
    /// <c>[EntityScope(Global)]</c> entities. Sequential test execution (TestCluster collection)
    /// makes this safe.
    /// </summary>
    public static readonly TestConfigVersionResolver ConfigVersionResolver = new();

    /// <summary>
    /// Register all test meta services using generated ConfigureMeta.
    /// </summary>
    public static IServiceCollection ConfigureTestMeta(
        this IServiceCollection services,
        Action<IServiceCollection>? configureServices = null)
    {
        services.AddSingleton<IMetaConfigProvider<MigrationConfig>>(MigrationConfigProvider);
        // 0.33.0+ CounterConfig moved from [MetaService(DefaultConfig=true)] (auto-registered
        // fallback on both sides) to [ServiceConfig(typeof(CounterConfig), "Config")] on
        // ICounterService/ICounterAuxService — no auto-default by design. Register the
        // server-side equivalent explicitly, matching the fallback's `new CounterConfig()`.
        services.AddSingleton<IMetaConfigProvider<CounterConfig>>(new TestCounterConfigProvider());
        // 0.20.0 multi-config sibling test fixture: AltConfigService declares [ServiceConfig] =
        // typeof(CounterAltConfig). Generated Get{Iface}SiblingAsync() resolves this provider
        // via Context.ResolveService → DI lookup. Without this registration the sibling-async
        // path throws when called from a multi-config sibling test.
        services.AddSingleton<IMetaConfigProvider<CounterAltConfig>>(new TestCounterAltConfigProvider());
        // 0.21.0 EntityScope fixture providers.
        services.AddSingleton<IMetaConfigProvider<SharedScopeConfig>>(new TestSharedScopeConfigProvider());
        services.AddSingleton<IMetaConfigProvider<GlobalScopeConfig>>(new TestGlobalScopeConfigProvider());
        services.AddSingleton<IMetaConfigProvider<MultiConfigA>>(new TestMultiConfigAProvider());
        services.AddSingleton<IMetaConfigProvider<MultiConfigB>>(new TestMultiConfigBProvider());
        // 0.33.0 [ServiceConfig] fixture: legacy primary + two independently-versioned entries.
        services.AddSingleton<IMetaConfigProvider<AdditionalFixturePrimaryConfig>>(new TestAdditionalFixturePrimaryConfigProvider());
        services.AddSingleton<IMetaConfigProvider<AdditionalFixtureBalanceConfig>>(new TestAdditionalFixtureBalanceConfigProvider());
        services.AddSingleton<IMetaConfigProvider<AdditionalFixtureSeasonConfig>>(new TestAdditionalFixtureSeasonConfigProvider());
        // 0.33.0 fully symmetric [ServiceConfig] fixture: no legacy ConfigType at all.
        services.AddSingleton<IMetaConfigProvider<SymmetricFixtureShopConfig>>(new TestSymmetricFixtureShopConfigProvider());
        services.AddSingleton<IMetaConfigProvider<SymmetricFixtureVaultConfig>>(new TestSymmetricFixtureVaultConfigProvider());
        // 0.33.0 Phase A: [ServiceConfig] pin/Global parity fixtures.
        services.AddSingleton<IMetaConfigProvider<ServiceConfigSharedScopeConfig>>(new TestServiceConfigSharedScopeConfigProvider());
        services.AddSingleton<IMetaConfigProvider<ServiceConfigGlobalScopeConfig>>(new TestServiceConfigGlobalScopeConfigProvider());
        // 0.33.0 Phase B: [ServiceConfig] schema-floor migration parity fixture.
        services.AddSingleton<IMetaConfigProvider<ServiceConfigMigrationConfig>>(new TestServiceConfigMigrationConfigProvider());
        services.AddSingleton<IConfigVersionResolver>(ConfigVersionResolver);
        return services.ConfigureMeta(configureServices);
    }
}

/// <summary>
/// Controllable <see cref="IConfigVersionResolver"/> for EntityScope tests. Tests mutate
/// <see cref="CurrentClientVersion"/> to simulate the server's "default client version".
/// </summary>
public class TestConfigVersionResolver : IConfigVersionResolver
{
    public string CurrentClientVersion { get; set; } = "1.0.0";

    public MetaConfigVersion ResolveVersion(string stateTypeName, string entityId, MetaConfigVersion defaultVersion)
        => defaultVersion;
}

/// <summary>
/// Provider for <see cref="SharedScopeConfig"/>: returns a config whose Major/Minor/Patch
/// fields mirror the requested version. Tests assert which version got pinned by reading
/// these fields back from <c>Context.Config</c> via the service's RecordConfig method.
/// </summary>
public class TestSharedScopeConfigProvider : IMetaConfigProvider<SharedScopeConfig>
{
    public SharedScopeConfig GetConfig(MetaConfigVersion version) => new SharedScopeConfig
    {
        Major = version.Major,
        Minor = version.Minor,
        Patch = version.Patch,
    };
}

/// <summary>Provider for <see cref="GlobalScopeConfig"/>; same pattern as SharedScope.</summary>
public class TestGlobalScopeConfigProvider : IMetaConfigProvider<GlobalScopeConfig>
{
    public GlobalScopeConfig GetConfig(MetaConfigVersion version) => new GlobalScopeConfig
    {
        Major = version.Major,
        Minor = version.Minor,
    };
}

/// <summary>Provider for <see cref="ServiceConfigSharedScopeConfig"/>; same pattern as SharedScope, for the [ServiceConfig] pin-parity fixture.</summary>
public class TestServiceConfigSharedScopeConfigProvider : IMetaConfigProvider<ServiceConfigSharedScopeConfig>
{
    public ServiceConfigSharedScopeConfig GetConfig(MetaConfigVersion version) => new ServiceConfigSharedScopeConfig
    {
        Major = version.Major,
        Minor = version.Minor,
        Patch = version.Patch,
    };
}

/// <summary>Provider for <see cref="ServiceConfigGlobalScopeConfig"/>; same pattern as GlobalScope, for the [ServiceConfig] Global-parity fixture.</summary>
public class TestServiceConfigGlobalScopeConfigProvider : IMetaConfigProvider<ServiceConfigGlobalScopeConfig>
{
    public ServiceConfigGlobalScopeConfig GetConfig(MetaConfigVersion version) => new ServiceConfigGlobalScopeConfig
    {
        Major = version.Major,
        Minor = version.Minor,
    };
}

/// <summary>Provider for <see cref="MultiConfigA"/> — used by the AND-gate test fixture.</summary>
public class TestMultiConfigAProvider : IMetaConfigProvider<MultiConfigA>
{
    public MultiConfigA GetConfig(MetaConfigVersion version) => new MultiConfigA
    {
        Major = version.Major,
        Minor = version.Minor,
    };
}

/// <summary>Provider for <see cref="MultiConfigB"/> — used by the AND-gate test fixture.</summary>
public class TestMultiConfigBProvider : IMetaConfigProvider<MultiConfigB>
{
    public MultiConfigB GetConfig(MetaConfigVersion version) => new MultiConfigB
    {
        Major = version.Major,
        Minor = version.Minor,
    };
}

/// <summary>
/// Trivial static provider for <see cref="CounterConfig"/> — returns the same instance
/// (default <c>MaxValue=1000</c>) regardless of version. Replaces the auto-default
/// StaticConfigProvider that [MetaService(DefaultConfig=true)] used to register automatically.
/// </summary>
public class TestCounterConfigProvider : IMetaConfigProvider<CounterConfig>
{
    private readonly CounterConfig _instance = new();
    public MetaConfigVersion CurrentVersion => new(1, 0);
    public CounterConfig GetConfig(MetaConfigVersion version) => _instance;
}

/// <summary>
/// Trivial static provider for <see cref="CounterAltConfig"/> — returns the same instance
/// regardless of version. Tests rely on the default <c>MaxValue=7777</c> to verify the sibling
/// saw the alt config rather than the primary <c>CounterConfig</c>.
/// </summary>
public class TestCounterAltConfigProvider : IMetaConfigProvider<CounterAltConfig>
{
    private readonly CounterAltConfig _instance = new() { MaxValue = 7777 };
    public MetaConfigVersion CurrentVersion => new(1, 0);
    public CounterAltConfig GetConfig(MetaConfigVersion version) => _instance;
}

/// <summary>Provider for <see cref="AdditionalFixturePrimaryConfig"/> — fixed value, not version-dependent.</summary>
public class TestAdditionalFixturePrimaryConfigProvider : IMetaConfigProvider<AdditionalFixturePrimaryConfig>
{
    public AdditionalFixturePrimaryConfig GetConfig(MetaConfigVersion version) => new() { Value = 42 };
}

/// <summary>
/// Provider for <see cref="AdditionalFixtureBalanceConfig"/> — Major/Minor mirror the resolved
/// version, which per its [MetaConfigVersion] rules is ALWAYS 1.0 regardless of client version.
/// </summary>
public class TestAdditionalFixtureBalanceConfigProvider : IMetaConfigProvider<AdditionalFixtureBalanceConfig>
{
    public AdditionalFixtureBalanceConfig GetConfig(MetaConfigVersion version) => new()
    {
        Major = version.Major,
        Minor = version.Minor,
    };
}

/// <summary>
/// Provider for <see cref="AdditionalFixtureSeasonConfig"/> — Major/Minor mirror the resolved
/// version, which per its [MetaConfigVersion] rules tracks the client's own version branch.
/// </summary>
public class TestAdditionalFixtureSeasonConfigProvider : IMetaConfigProvider<AdditionalFixtureSeasonConfig>
{
    public AdditionalFixtureSeasonConfig GetConfig(MetaConfigVersion version) => new()
    {
        Major = version.Major,
        Minor = version.Minor,
    };
}

/// <summary>Provider for <see cref="SymmetricFixtureShopConfig"/> — Major mirrors the resolved version.</summary>
public class TestSymmetricFixtureShopConfigProvider : IMetaConfigProvider<SymmetricFixtureShopConfig>
{
    public SymmetricFixtureShopConfig GetConfig(MetaConfigVersion version) => new() { Major = version.Major };
}

/// <summary>
/// Provider for <see cref="SymmetricFixtureVaultConfig"/> — Major/Minor rules pin it to ALWAYS
/// 1.0 regardless of client version, mirroring how Balance behaves in the legacy+ServiceConfig fixture.
/// </summary>
public class TestSymmetricFixtureVaultConfigProvider : IMetaConfigProvider<SymmetricFixtureVaultConfig>
{
    public SymmetricFixtureVaultConfig GetConfig(MetaConfigVersion version) => new() { Major = version.Major };
}

/// <summary>
/// Controllable config provider for MigrationTests. Tests set
/// <see cref="CurrentVersion"/> to simulate a config rollout advancing to a new version.
/// <see cref="GetConfig"/> always returns a MigrationConfig whose Major/Minor reflect
/// the requested version — so [MetaInit] can record which version was pinned to each step.
/// </summary>
public class TestMigrationConfigProvider : IMetaConfigProvider<MigrationConfig>
{
    private MetaConfigVersion _currentVersion;

    public TestMigrationConfigProvider(MetaConfigVersion initialVersion)
        => _currentVersion = initialVersion;

    public MetaConfigVersion CurrentVersion => _currentVersion;

    public void SetVersion(MetaConfigVersion v) => _currentVersion = v;
    public void SetVersion(int major, int minor) => _currentVersion = new MetaConfigVersion(major, minor);

    public MigrationConfig GetConfig(MetaConfigVersion version) => new MigrationConfig
    {
        Major = version.Major,
        Minor = version.Minor,
        Label = $"{version.Major}.{version.Minor}"
    };
}

/// <summary>Provider for <see cref="ServiceConfigMigrationConfig"/> — Major/Minor echo the resolved version, same pattern as <see cref="TestMigrationConfigProvider"/>.</summary>
public class TestServiceConfigMigrationConfigProvider : IMetaConfigProvider<ServiceConfigMigrationConfig>
{
    public ServiceConfigMigrationConfig GetConfig(MetaConfigVersion version) => new ServiceConfigMigrationConfig
    {
        Major = version.Major,
        Minor = version.Minor,
    };
}
