using System.Text;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SharedMeta.Generator.Generators
{
    public static class ClientProxyGenerator
    {
        public static string Generate(string symbol, string namespaceName, InterfaceDeclarationSyntax node)
        {
            var sbClient = new StringBuilder();
            sbClient.AppendLine("// <auto-generated/>");
            sbClient.AppendLine("#nullable enable");
            sbClient.AppendLine("using System;");
            sbClient.AppendLine("using System.Threading.Tasks;");
            sbClient.AppendLine("using SharedMeta.Core;");
            sbClient.AppendLine($"namespace {namespaceName}.Client");
            sbClient.AppendLine("{");
            var className = symbol;
            if (symbol.StartsWith("I") && symbol.Length > 1 && char.IsUpper(symbol[1]))
            {
                className = symbol.Substring(1);
            }

            sbClient.AppendLine($"    public class {className}Client // : {namespaceName}.{symbol} - Client is Async, Base is Sync. No inheritance.");
            sbClient.AppendLine("    {");
            sbClient.AppendLine("        private readonly IMetaProvider _provider;");
            sbClient.AppendLine("        private readonly IMetaSerializer _serializer;");
            sbClient.AppendLine($"        public {className}Client(IMetaProvider provider, IMetaSerializer serializer) {{ _provider = provider; _serializer = serializer; }}");

            var methods = node.Members.OfType<MethodDeclarationSyntax>().ToList();

            foreach (var method in methods)
            {
                var methodName = method.Identifier.Text;
                var returnType = method.ReturnType.ToString();
                var parameters = string.Join(", ", method.ParameterList.Parameters);
                var paramCount = method.ParameterList.Parameters.Count;
                
                // Parse Attribute for Alias
                var methodAlias = methodName; // Default
                var attributes = method.AttributeLists.SelectMany(a => a.Attributes);
                var metaMethod = attributes.FirstOrDefault(a => a.Name.ToString().Contains("MetaMethod"));
                if (metaMethod != null)
                {
                    var aliasArg = metaMethod.ArgumentList?.Arguments.FirstOrDefault(arg => arg.NameEquals != null && arg.NameEquals.Name.Identifier.Text == "Alias");
                    if (aliasArg != null && aliasArg.Expression is LiteralExpressionSyntax literal)
                    {
                        methodAlias = literal.Token.ValueText;
                    }
                }

                // Determine Client Return Type (Promote Sync to Async)
                bool isAsync = returnType.StartsWith("System.Threading.Tasks.Task") || returnType.StartsWith("Task");
                string clientReturnType;
                
                 if (isAsync)
                {
                    clientReturnType = returnType;
                }
                else if (returnType == "void")
                {
                    clientReturnType = "Task";
                }
                else
                {
                    clientReturnType = $"Task<{returnType}>";
                }

                sbClient.AppendLine($"        public {clientReturnType} {methodName}({parameters})");
                sbClient.AppendLine("        {");
                
                // Pack args sequentially
                if (paramCount == 0)
                {
                    // No args
                    if (returnType == "void" || returnType == "Task")
                    {
                        sbClient.AppendLine($"            return _provider.SendVoidAsync(\"{symbol}\", \"{methodAlias}\", Array.Empty<byte>());");
                    }
                    else if (isAsync)
                    {
                        int open = returnType.IndexOf('<');
                        int close = returnType.LastIndexOf('>');
                        var innerType = returnType.Substring(open + 1, close - open - 1);
                        sbClient.AppendLine($"            return _provider.SendAsync<{innerType}>(\"{symbol}\", \"{methodAlias}\", Array.Empty<byte>());");
                    }
                    else
                    {
                        sbClient.AppendLine($"            return _provider.SendAsync<{returnType}>(\"{symbol}\", \"{methodAlias}\", Array.Empty<byte>());");
                    }
                }
                else
                {
                    sbClient.AppendLine("            var writer = _serializer.CreateWriter();");
                    
                    foreach (var param in method.ParameterList.Parameters)
                    {
                        var paramName = param.Identifier.Text;
                        sbClient.AppendLine($"            writer.Write({paramName});");
                    }
                    
                    sbClient.AppendLine("            var argsBytes = writer.Complete();");
                    
                    if (returnType == "void" || returnType == "Task")
                    {
                        sbClient.AppendLine($"            return _provider.SendVoidAsync(\"{symbol}\", \"{methodAlias}\", argsBytes);");
                    }
                    else if (isAsync)
                    {
                        int open = returnType.IndexOf('<');
                        int close = returnType.LastIndexOf('>');
                        var innerType = returnType.Substring(open + 1, close - open - 1);
                        sbClient.AppendLine($"            return _provider.SendAsync<{innerType}>(\"{symbol}\", \"{methodAlias}\", argsBytes);");
                    }
                    else
                    {
                        sbClient.AppendLine($"            return _provider.SendAsync<{returnType}>(\"{symbol}\", \"{methodAlias}\", argsBytes);");
                    }
                }
                
                sbClient.AppendLine("        }");
            }
            sbClient.AppendLine("    }");
            sbClient.AppendLine("}");
            return sbClient.ToString();
        }
    }
}
