using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Information about a service for aggregate client registration.
    /// </summary>
    public class ClientServiceInfo
    {
        public string InterfaceName { get; set; } = "";
        public string BaseName { get; set; } = "";
        public string Namespace { get; set; } = "";
        public string? StateTypeFullName { get; set; }
        public int AccessPolicy { get; set; } // 0=Open, 1=Authorized, 2=OwnerOnly, 3=UserOwned
    }

    /// <summary>
    /// Generates an aggregate RegisterAllServices() extension method
    /// that calls all individual AddXxxServices() methods.
    /// Also generates convenience methods on MetaClient for UserOwned services.
    /// Eliminates the need for per-project manual service registration chains.
    /// </summary>
    public static class ClientServiceAggregateGenerator
    {
        /// <summary>
        /// Analyze a [MetaService] interface for aggregate registration.
        /// </summary>
        public static ClientServiceInfo? Analyze(INamedTypeSymbol symbol)
        {
            var attr = symbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceAttribute");
            if (attr == null) return null;

            // Need StateType to generate registration
            var stateTypeArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "StateType");
            if (stateTypeArg.Value.Value is not INamedTypeSymbol stateType)
                return null;

            var interfaceName = symbol.Name;
            var baseName = interfaceName;
            if (baseName.StartsWith("I") && baseName.Length > 1 && char.IsUpper(baseName[1]))
            {
                baseName = baseName.Substring(1);
            }

            // Read AccessPolicy from [MetaService] attribute
            int accessPolicy = 0;
            var accessPolicyArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "AccessPolicy");
            if (!accessPolicyArg.Value.IsNull && accessPolicyArg.Value.Value is int policyValue)
            {
                accessPolicy = policyValue;
            }

            return new ClientServiceInfo
            {
                InterfaceName = interfaceName,
                BaseName = baseName,
                Namespace = symbol.ContainingNamespace.ToDisplayString(),
                StateTypeFullName = stateType.ToDisplayString(),
                AccessPolicy = accessPolicy
            };
        }

        /// <summary>
        /// Generate the MetaClientExtensions class with RegisterAllServices()
        /// and UserOwned convenience methods.
        /// </summary>
        public static string Generate(string rootNamespace, IEnumerable<ClientServiceInfo> services)
        {
            var serviceList = services.Where(s => s != null && s.StateTypeFullName != null).ToList();
            if (serviceList.Count == 0) return "";

            var userOwnedServices = serviceList.Where(s => s.AccessPolicy == 3).ToList();
            // Non-UserOwned services (Open / Authorized / OwnerOnly) get a typed convenience
            // helper too — same shape as UserOwned but with an explicit entityId parameter,
            // so callers can write `client.GetExpeditionServiceAsync(entityId)` instead of the
            // generic `client.GetServiceAsync<ExpeditionServiceApiClient>(entityId)`.
            var entityIdServices = serviceList.Where(s => s.AccessPolicy != 3).ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using SharedMeta.Core;");

            // Collect unique DependencyInjection namespaces for using statements
            var diNamespaces = serviceList
                .Select(s => s.Namespace + ".DependencyInjection")
                .Distinct()
                .OrderBy(n => n);
            foreach (var ns in diNamespaces)
            {
                sb.AppendLine($"using {ns};");
            }

            // If any service will get a convenience helper (UserOwned no-arg, or non-UserOwned
            // with an explicit entityId), pull in MetaClient + the per-service Client namespaces
            // so the helpers' return types and `client.GetServiceAsync<…>` calls compile.
            if (userOwnedServices.Count > 0 || entityIdServices.Count > 0)
            {
                sb.AppendLine("using SharedMeta.Client;");
                var clientNamespaces = serviceList
                    .Select(s => s.Namespace + ".Client")
                    .Distinct()
                    .OrderBy(n => n);
                foreach (var ns in clientNamespaces)
                {
                    sb.AppendLine($"using {ns};");
                }
            }

            sb.AppendLine();
            sb.AppendLine($"namespace {rootNamespace}.Client");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Aggregate client service registration.");
            sb.AppendLine("    /// Registers all discovered [MetaService] services with IMetaServiceResolver.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class MetaClientExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Register all meta services discovered in this assembly.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static TResolver RegisterAllServices<TResolver>(this TResolver resolver)");
            sb.AppendLine("            where TResolver : IMetaServiceResolver");
            sb.AppendLine("        {");

            // 0.24.0+ Publish this assembly's client signature as the process default so MetaClient
            // auto-negotiates without manual wiring. Primary mechanism on Unity (the net5+ module
            // initializer doesn't exist there); always runs before ConnectAsync in the normal flow.
            sb.AppendLine($"            global::SharedMeta.Core.Transport.ClientSignatureDefault.Value = global::{rootNamespace}.GameServiceDiscoveryBase.ClientSignature;");

            foreach (var service in serviceList)
            {
                sb.AppendLine($"            resolver.Add{service.BaseName}Services();");
            }

            sb.AppendLine("            return resolver;");
            sb.AppendLine("        }");

            // Generate UserOwned convenience methods
            if (userOwnedServices.Count > 0)
            {
                foreach (var service in userOwnedServices)
                {
                    sb.AppendLine();
                    sb.AppendLine($"        /// <summary>");
                    sb.AppendLine($"        /// Get {service.BaseName}ApiClient for the current player's entity.");
                    sb.AppendLine($"        /// Uses client.PlayerId as the entity ID (UserOwned policy).");
                    sb.AppendLine($"        /// </summary>");
                    sb.AppendLine($"        public static System.Threading.Tasks.Task<{service.BaseName}ApiClient> Get{service.BaseName}Async(this MetaClient client)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            return client.GetServiceAsync<{service.BaseName}ApiClient>(client.PlayerId);");
                    sb.AppendLine("        }");

                    // 0.29.3+ Synchronous, allocation-free accessor for the already-subscribed case.
                    // Typed shortcut for client.TryGetService<{BaseName}ApiClient>(client.PlayerId, out api).
                    sb.AppendLine();
                    sb.AppendLine($"        /// <summary>");
                    sb.AppendLine($"        /// Try to get the already-resolved {service.BaseName}ApiClient for the current player's");
                    sb.AppendLine($"        /// entity without subscribing or allocating. True when it was already created via");
                    sb.AppendLine($"        /// <c>Get{service.BaseName}Async</c>. Uses client.PlayerId as the entity ID (UserOwned policy).");
                    sb.AppendLine($"        /// </summary>");
                    sb.AppendLine($"        public static bool TryGet{service.BaseName}(this MetaClient client, [System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out {service.BaseName}ApiClient? api)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            return client.TryGetService<{service.BaseName}ApiClient>(client.PlayerId, out api);");
                    sb.AppendLine("        }");
                }

                // Generate GetState convenience methods for unique state types among UserOwned services
                var seenStateTypes = new HashSet<string>();
                foreach (var service in userOwnedServices)
                {
                    if (service.StateTypeFullName != null && seenStateTypes.Add(service.StateTypeFullName))
                    {
                        var stateSimpleName = GetSimpleTypeName(service.StateTypeFullName);
                        sb.AppendLine();
                        sb.AppendLine($"        /// <summary>");
                        sb.AppendLine($"        /// Get {stateSimpleName} for the current player's entity.");
                        sb.AppendLine($"        /// Uses client.PlayerId as the entity ID (UserOwned policy).");
                        sb.AppendLine($"        /// </summary>");
                        sb.AppendLine($"        public static {service.StateTypeFullName} Get{stateSimpleName}(this MetaClient client)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            return client.GetState<{service.StateTypeFullName}>(client.PlayerId);");
                        sb.AppendLine("        }");
                    }
                }
            }

            // 0.25.0+ entityId-arg convenience helper for non-UserOwned services. Mirror of the
            // UserOwned no-arg form, just typed at the call site so the caller skips the generic
            // `GetServiceAsync<TApi>` cast and the ApiClient class name.
            foreach (var service in entityIdServices)
            {
                sb.AppendLine();
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// Get {service.BaseName}ApiClient for the entity <paramref name=\"entityId\"/>.");
                sb.AppendLine($"        /// Typed shortcut for <c>client.GetServiceAsync&lt;{service.BaseName}ApiClient&gt;(entityId)</c>.");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        public static System.Threading.Tasks.Task<{service.BaseName}ApiClient> Get{service.BaseName}Async(this MetaClient client, string entityId)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return client.GetServiceAsync<{service.BaseName}ApiClient>(entityId);");
                sb.AppendLine("        }");

                // 0.29.3+ Synchronous, allocation-free accessor for the already-subscribed case.
                // Typed shortcut for client.TryGetService<{BaseName}ApiClient>(entityId, out api).
                sb.AppendLine();
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// Try to get the already-resolved {service.BaseName}ApiClient for <paramref name=\"entityId\"/>");
                sb.AppendLine($"        /// without subscribing or allocating. True when it was already created via");
                sb.AppendLine($"        /// <c>Get{service.BaseName}Async</c>.");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        public static bool TryGet{service.BaseName}(this MetaClient client, string entityId, [System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out {service.BaseName}ApiClient? api)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return client.TryGetService<{service.BaseName}ApiClient>(entityId, out api);");
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string GetSimpleTypeName(string fullTypeName)
        {
            var lastDot = fullTypeName.LastIndexOf('.');
            return lastDot >= 0 ? fullTypeName.Substring(lastDot + 1) : fullTypeName;
        }
    }
}
