using System.Text;
using System.Linq;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SharedMeta.Generator.Utilities;

namespace SharedMeta.Generator.Generators
{
    public static class ContextInjectionGenerator
    {
        public static string? Generate(ClassDeclarationSyntax node, INamedTypeSymbol symbol, Compilation compilation)
        {
            // Detect serializer type for code generation
            var serializer = SerializerDetector.Detect(compilation);
            // Find the attribute
            var attr = symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceImplAttribute");
            if (attr == null) return null;

            // Get constructor arguments
            if (attr.ConstructorArguments.Length < 2) return null;

            // Arg 0: Service Interface (Type)
            // Arg 1: State Type (Type)
            var stateTypeArg = attr.ConstructorArguments[1];
            var stateTypeSymbol = stateTypeArg.Value as INamedTypeSymbol;

            if (stateTypeSymbol == null) return null;

            var stateTypeName = stateTypeSymbol.ToDisplayString();

            // Check for DeepDesync = true
            var deepDesyncArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "DeepDesync");
            bool deepDesync = !deepDesyncArg.Value.IsNull && deepDesyncArg.Value.Value is true;

            var namespaceName = symbol.ContainingNamespace.ToDisplayString();
            var className = symbol.Name;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using SharedMeta.Core;");
            sb.AppendLine("using SharedMeta.Core.Random;");
            sb.AppendLine("using SharedMeta.Core.Transport;");
            if (serializer == DetectedSerializer.MemoryPack)
            {
                sb.AppendLine("using System.Buffers;");
                sb.AppendLine("using MemoryPack;");
            }
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");
            sb.AppendLine($"        // 0.20.0: Context is a typed instance property — the user-code hot path no");
            sb.AppendLine($"        // longer needs the AsyncLocal lookup. The provider's lazy Get{{Name}}() sets");
            sb.AppendLine($"        // it after `new` on the server; client-side ApiClient sets it via");
            sb.AppendLine($"        // SetContext(...) before each method invocation; sibling-bypass paths and");
            sb.AppendLine($"        // Get{{Iface}}SiblingAsync() set it on transient impls. The fallback through");
            sb.AppendLine($"        // MetaContextAccessor remains for framework-internal generated paths that");
            sb.AppendLine($"        // were not migrated in 0.20.0 (foreign-service entity replay dispatcher,");
            sb.AppendLine($"        // signal/trigger/subscriber dispatchers, ServerPatch / ServerReplace");
            sb.AppendLine($"        // appliers). Those continue to set MetaContextAccessor.Current as their");
            sb.AppendLine($"        // ambient context — that's the right primitive for those scenarios and is");
            sb.AppendLine($"        // not a code smell, just an explicit ambient-execution-context handle.");
            sb.AppendLine($"        private MetaContext<{stateTypeName}>? _context;");
            sb.AppendLine($"        public MetaContext<{stateTypeName}> Context");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            get => _context ?? MetaContextAccessor.Get<{stateTypeName}>();");
            sb.AppendLine($"            set => _context = value;");
            sb.AppendLine($"        }}");
            sb.AppendLine();
            sb.AppendLine($"        protected {stateTypeName} State => Context.State;");

            // Named random accessors — one property per [NamedRandom] on the state (positional)
            var namedRandoms = stateTypeSymbol.GetAttributes()
                .Where(a => a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.NamedRandomAttribute")
                .Select(a => a.ConstructorArguments.Length > 0 ? a.ConstructorArguments[0].Value as string : null)
                .Where(n => !string.IsNullOrEmpty(n))
                .ToList();
            for (int i = 0; i < namedRandoms.Count; i++)
            {
                var n = namedRandoms[i];
                sb.AppendLine();
                sb.AppendLine($"        /// <summary>Named deterministic random '{n}' declared via [NamedRandom] on {stateTypeName}.</summary>");
                sb.AppendLine($"        protected IMetaRandom {n}Random => Context.NamedRandoms![{i}];");
            }

            // Typed Config accessor — if the service has a ConfigType
            var serviceInterfaceSymbol = attr.ConstructorArguments[0].Value as INamedTypeSymbol;
            string? configTypeName = null;
            if (serviceInterfaceSymbol != null)
            {
                var metaServiceAttr = serviceInterfaceSymbol.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceAttribute");
                if (metaServiceAttr != null)
                {
                    var configTypeArg = metaServiceAttr.NamedArguments.FirstOrDefault(a => a.Key == "ConfigType");
                    if (!configTypeArg.Value.IsNull && configTypeArg.Value.Value is INamedTypeSymbol configTypeSymbol)
                    {
                        configTypeName = configTypeSymbol.ToDisplayString();
                    }
                    else
                    {
                        // Check DefaultConfig flag — resolve from compilation
                        var defaultConfigArg = metaServiceAttr.NamedArguments.FirstOrDefault(a => a.Key == "DefaultConfig");
                        if (!defaultConfigArg.Value.IsNull && defaultConfigArg.Value.Value is true)
                        {
                            configTypeName = FindDefaultConfigType(compilation);
                        }
                    }
                }
            }
            if (configTypeName != null)
            {
                sb.AppendLine();
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// Static game configuration for this service. 0.20.0: typed instance");
                sb.AppendLine($"        /// field, set by the provider per-call against the caller's resolved");
                sb.AppendLine($"        /// config branch — independent of any other sibling service's Config,");
                sb.AppendLine($"        /// so multi-config sibling-calls each see their own type. Falls back to");
                sb.AppendLine($"        /// the shared <c>Context.Config</c> on client paths that haven't been");
                sb.AppendLine($"        /// migrated to per-service typed Config (Optimistic / CrossOptimistic /");
                sb.AppendLine($"        /// Server replay flows continue to set Context.Config the legacy way).");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        private {configTypeName}? _config;");
                sb.AppendLine($"        public {configTypeName} Config");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            get => _config ?? ({configTypeName})Context.Config!;");
                sb.AppendLine($"            set => _config = value;");
                sb.AppendLine($"        }}");
            }

            // PatchState accessor for ServerPatch mode — only if state has ordinal attributes
            // (PatchWrapper is generated by StatePatchGenerator only for types with [Id], [Key], or [MemoryPackOrder])
            if (HasSerializationOrdinalAttributes(stateTypeSymbol))
            {
                sb.AppendLine();
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// Typed patch-tracking wrapper for State.");
                sb.AppendLine($"        /// Always available. Tracking only active when server is in ServerPatch mode.");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        protected {stateTypeName}PatchWrapper PatchState");
                sb.AppendLine("        {");
                sb.AppendLine("            get");
                sb.AppendLine("            {");
                sb.AppendLine($"                if (Context.PatchWrapper is {stateTypeName}PatchWrapper existing)");
                sb.AppendLine("                    return existing;");
                sb.AppendLine($"                var wrapper = new {stateTypeName}PatchWrapper(");
                sb.AppendLine("                    Context.State, null, Context.MetaSerializer);");
                sb.AppendLine("                Context.PatchWrapper = wrapper;");
                sb.AppendLine("                return wrapper;");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
            }

            // Collect entity services for generating proxy classes
            var entityServices = new List<INamedTypeSymbol>();

            // Arg 2: Params Dependencies (Optional)
            if (attr.ConstructorArguments.Length > 2)
            {
                var depsArg = attr.ConstructorArguments[2];
                if (!depsArg.IsNull && depsArg.Values.Length > 0)
                {
                    foreach (var dep in depsArg.Values)
                    {
                        var depSymbol = dep.Value as INamedTypeSymbol;
                        if (depSymbol != null)
                        {
                            // Check if this is an entity service (implements IMetaService, no [ServerMetaService])
                            if (IsEntityService(depSymbol))
                            {
                                // Resolve dep's TState directly from [MetaService(StateType = typeof(...))]
                                // on the dep interface itself — no compilation scan, attribute is already
                                // on the symbol. Every entity service must declare its TState — otherwise
                                // we can't decide whether sibling-bypass is type-safe. Missing StateType
                                // surfaces as a #error in the generated file at the consumer's compile.
                                var depStateFqn = ReadDepStateType(depSymbol);
                                if (depStateFqn == null)
                                {
                                    sb.AppendLine();
                                    sb.AppendLine($"#error Entity service {depSymbol.ToDisplayString()} declared as a dependency on {symbol.ToDisplayString()} has no [MetaService(StateType = typeof(...))]. Every entity service must declare its TState — otherwise the framework cannot route cross-entity calls.");
                                    sb.AppendLine();
                                    continue;
                                }
                                bool depIsSibling = depStateFqn == stateTypeName;
                                GenerateEntityServiceGetter(sb, depSymbol, stateTypeName, depIsSibling);
                                if (depIsSibling)
                                {
                                    var depConfig = ReadDepConfigType(depSymbol);
                                    GenerateSiblingAsyncGetter(sb, depSymbol, stateTypeName, depConfig);
                                }
                                entityServices.Add(depSymbol);
                            }
                            else
                            {
                                // Server service (e.g., ILobbyRequester)
                                GenerateServerServiceGetter(sb, depSymbol);
                            }
                        }
                    }
                }
            }

            sb.AppendLine("    }");

            // 0.20.0: helper classes ({Iface}EntityCaller + Recorder/Replayer/LocalEntityCaller/
            // SiblingCaller) are emitted by EntityCallerHelpersGenerator — one shared file per
            // (namespace, dep) pair, regardless of how many consumers in that namespace declare
            // the dep. This impl partial only contains the consumer-specific bits: getters and
            // accessor properties. SharedMetaGenerator drives the helpers generator separately.

            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// 0.20.0: Generate a standalone source file containing the entity-caller helper classes
        /// ({Iface}EntityCaller interface + Recorder/Replayer/LocalEntityCaller/SiblingCaller)
        /// for a single dep interface, in the specified consumer namespace. Driven by
        /// <c>SharedMetaGenerator</c>'s pipeline once per unique (namespace, dep) pair.
        /// </summary>
        public static string GenerateHelpersForDep(
            INamedTypeSymbol depInterface, string consumerNamespace, Compilation compilation)
        {
            var serializer = SerializerDetector.Detect(compilation);
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using SharedMeta.Core;");
            sb.AppendLine("using SharedMeta.Core.Random;");
            sb.AppendLine("using SharedMeta.Core.Transport;");
            if (serializer == DetectedSerializer.MemoryPack)
            {
                sb.AppendLine("using System.Buffers;");
                sb.AppendLine("using MemoryPack;");
            }
            sb.AppendLine($"namespace {consumerNamespace}");
            sb.AppendLine("{");
            GenerateEntityCallerInterface(sb, depInterface, consumerNamespace);
            GenerateEntityRecorderClass(sb, depInterface, consumerNamespace, serializer);
            GenerateEntityReplayerClass(sb, depInterface, consumerNamespace);
            GenerateLocalEntityCallerClass(sb, depInterface, consumerNamespace, "");
            GenerateSiblingCallerClass(sb, depInterface);
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static bool HasServerMetaServiceAttribute(INamedTypeSymbol symbol)
        {
            // Check if the interface has [ServerMetaService] attribute
            return symbol.GetAttributes().Any(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.ServerMetaServiceAttribute");
        }

        private static bool IsEntityService(INamedTypeSymbol symbol)
        {
            // Entity services: implement IMetaService but don't have [ServerMetaService] attribute
            // Server services: have [ServerMetaService] attribute (may or may not implement IMetaService)
            if (HasServerMetaServiceAttribute(symbol))
                return false;

            // Check if the interface implements IMetaService
            foreach (var iface in symbol.AllInterfaces)
            {
                if (iface.ToDisplayString() == "SharedMeta.Core.IMetaService")
                    return true;
            }
            // Also check direct base
            if (symbol.ToDisplayString() == "SharedMeta.Core.IMetaService")
                return true;
            foreach (var baseType in symbol.Interfaces)
            {
                if (baseType.ToDisplayString() == "SharedMeta.Core.IMetaService")
                    return true;
            }
            return false;
        }

        /// <summary>
        /// Generate getter for entity services (cross-entity calls).
        /// Returns the async EntityCaller interface, not the original service interface.
        /// </summary>
        private static void GenerateEntityServiceGetter(StringBuilder sb, INamedTypeSymbol depSymbol, string callerStateTypeName, bool depIsSibling)
        {
            var interfaceName = depSymbol.Name;
            var interfaceFqn = depSymbol.ToDisplayString();
            var depNamespace = depSymbol.ContainingNamespace.ToDisplayString();

            // Base name: IProfileService -> ProfileService
            var baseName = interfaceName;
            if (baseName.StartsWith("I") && baseName.Length > 1 && char.IsUpper(baseName[1]))
            {
                baseName = baseName.Substring(1);
            }

            var entityCallerInterface = $"{interfaceName}EntityCaller";

            sb.AppendLine();
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Get a proxy to call {interfaceName} on another entity.");
            sb.AppendLine($"        /// Returns async EntityCaller interface for cross-entity communication.");
            sb.AppendLine($"        /// On server with self-id and same TState: dispatches directly on cached");
            sb.AppendLine($"        /// sibling instance (typed args, no serialization, no grain RPC) — 0.20.0.");
            sb.AppendLine($"        /// On client with self-id and same TState: dispatches on a transient impl");
            sb.AppendLine($"        /// bound to our Context, so its mutations are visible on the local mirror");
            sb.AppendLine($"        /// (matters for Optimistic mode where the inner cross-entity call would");
            sb.AppendLine($"        /// otherwise no-op through Replayer) — 0.20.0.");
            sb.AppendLine($"        /// On server with cross-grain target: packs args and calls CallEntityAsync (EntityRecorder).");
            sb.AppendLine($"        /// On client with CrossEntityResolver: executes locally (LocalEntityCaller).");
            sb.AppendLine($"        /// On client without CrossEntityResolver: replays from recorded data (EntityReplayer).");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        protected {entityCallerInterface} Get{interfaceName}(string entityId)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (Context.IsServer)");
            sb.AppendLine("            {");
            sb.AppendLine($"                // 0.20.0 server self-call short-circuit: if entityId is this entity AND");
            sb.AppendLine($"                // the sibling resolver returns an instance for {interfaceName}, that means");
            sb.AppendLine($"                // {interfaceName} is hosted on this very grain (same TState). Dispatch");
            sb.AppendLine($"                // directly on the cached impl with typed args — no serialization, no");
            sb.AppendLine($"                // grain RPC, no nested-call indirection. Resolver returning null means");
            sb.AppendLine($"                // cross-grain target with same entity id (different TState) — falls");
            sb.AppendLine($"                // through to the recorder path.");
            sb.AppendLine($"                if (entityId == Context.EntityId && Context.SiblingServiceResolver != null)");
            sb.AppendLine("                {");
            sb.AppendLine($"                    var sibling = Context.SiblingServiceResolver(typeof({interfaceFqn})) as {interfaceFqn};");
            sb.AppendLine($"                    if (sibling != null)");
            sb.AppendLine($"                        return new {baseName}SiblingCaller(sibling);");
            sb.AppendLine("                }");
            sb.AppendLine($"                return new {baseName}EntityRecorder(entityId, (IServerRecordContext)Context);");
            sb.AppendLine("            }");
            if (depIsSibling)
            {
                sb.AppendLine();
                sb.AppendLine($"            // 0.20.0 client self-call short-circuit: same-entity target on client side.");
                sb.AppendLine($"            // {interfaceName} lives on the same TState as this caller — sibling. Build");
                sb.AppendLine($"            // a transient {baseName} impl bound to our caller's Context and dispatch");
                sb.AppendLine($"            // on it through the same SiblingCaller adapter. The impl reads our State");
                sb.AppendLine($"            // and MetaContext directly, so its mutations are visible on the local");
                sb.AppendLine($"            // mirror under both Optimistic and CrossOptimistic outer modes — without");
                sb.AppendLine($"            // this short-circuit, an Optimistic outer would route through the no-op");
                sb.AppendLine($"            // EntityReplayer and the inner mutation would never appear on the client");
                sb.AppendLine($"            // (e.g. gift-to-self: outer deducts, inner add-back is invisible).");
                sb.AppendLine($"            if (entityId == Context.EntityId)");
                sb.AppendLine("            {");
                sb.AppendLine($"                var transient = new {depNamespace}.{baseName}() {{ Context = Context }};");
                sb.AppendLine($"                return new {baseName}SiblingCaller(transient);");
                sb.AppendLine("            }");
                sb.AppendLine();
            }
            sb.AppendLine("            if (Context.CrossEntityResolver != null)");
            sb.AppendLine("            {");
            sb.AppendLine($"                return new {baseName}LocalEntityCaller(entityId, Context.CrossEntityResolver);");
            sb.AppendLine("            }");
            sb.AppendLine($"            return new {baseName}EntityReplayer((IClientReplayContext)Context);");
            sb.AppendLine("        }");
        }

        /// <summary>
        /// 0.20.0: Emit the explicit <c>Get{Iface}SiblingAsync()</c> accessor on the calling impl
        /// partial. Returns the original <c>I{Iface}</c> interface (not the async EntityCaller
        /// shape) — the caller awaits to resolve the callee's typed Config asynchronously through
        /// its own <c>IMetaConfigProvider&lt;TConfig&gt;</c>, then gets back a sibling instance
        /// ready to use with sync/async methods as declared in the interface.
        /// </summary>
        private static void GenerateSiblingAsyncGetter(
            StringBuilder sb, INamedTypeSymbol depSymbol, string callerStateTypeName, string? depConfigTypeName)
        {
            var interfaceName = depSymbol.Name;
            var interfaceFqn = depSymbol.ToDisplayString();
            var depNamespace = depSymbol.ContainingNamespace.ToDisplayString();
            var baseName = interfaceName;
            if (baseName.StartsWith("I") && baseName.Length > 1 && char.IsUpper(baseName[1]))
                baseName = baseName.Substring(1);
            var implFqn = $"{depNamespace}.{baseName}";

            sb.AppendLine();
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// 0.20.0 explicit sibling accessor for {interfaceName}. Returns the original");
            sb.AppendLine($"        /// {interfaceName} interface bound to this entity's cached sibling instance");
            sb.AppendLine($"        /// (server) or a transient impl with this caller's Context (client). Async");
            sb.AppendLine($"        /// because resolving the callee's typed Config goes through");
            sb.AppendLine($"        /// IMetaConfigProvider&lt;TConfig&gt;.GetConfigAsync — supports remote / IO-");
            sb.AppendLine($"        /// backed providers without blocking the entity grain.");
            sb.AppendLine($"        /// </summary>");
            // 0.20.0 multi-config caveat: server-side Config-resolve uses SharedMeta.Server.Core.
            // IMetaConfigProvider<T>, which lives in the server-side assembly. Shared
            // [MetaServiceImpl] partials compile into both client and server, so the
            // server-only path is wrapped in #if SHAREDMETA_SERVER. Client-side falls back to
            // the impl's typed Config getter (instance _config field if pre-set, else cast
            // from Context.Config) — multi-config siblings on client require server-only
            // execution modes (Server / ServerReplace / ServerPatch) so the client never
            // replays the method body that would otherwise hit a typed-Config cast mismatch.
            sb.AppendLine($"#if SHAREDMETA_SERVER");
            string asyncModifierServer = depConfigTypeName != null ? "async " : "";
            string returnExprServer = depConfigTypeName != null ? "return sibling;" : "return System.Threading.Tasks.Task.FromResult(sibling);";
            sb.AppendLine($"        protected {asyncModifierServer}System.Threading.Tasks.Task<{interfaceFqn}> Get{interfaceName}SiblingAsync()");
            sb.AppendLine("        {");
            sb.AppendLine($"            {interfaceFqn}? sibling = null;");
            sb.AppendLine($"            if (Context.SiblingServiceResolver != null)");
            sb.AppendLine($"                sibling = Context.SiblingServiceResolver(typeof({interfaceFqn})) as {interfaceFqn};");
            sb.AppendLine($"            if (sibling == null)");
            sb.AppendLine($"                sibling = new {implFqn}() {{ Context = Context }};");
            if (depConfigTypeName != null)
            {
                sb.AppendLine($"            var configProvider = Context.ResolveService<SharedMeta.Server.Core.IMetaConfigProvider<{depConfigTypeName}>>();");
                sb.AppendLine($"            var policyResolver = SharedMeta.Core.MetaConfigVersionResolver.ForType(typeof({depConfigTypeName}));");
                sb.AppendLine($"            var resolvedVersion = configProvider.ResolveForClient(Context.CallerClientVersion, policyResolver);");
                sb.AppendLine($"            var typedConfig = await configProvider.GetConfigAsync(resolvedVersion);");
                sb.AppendLine($"            (({implFqn})sibling).Config = typedConfig;");
            }
            sb.AppendLine($"            {returnExprServer}");
            sb.AppendLine("        }");
            sb.AppendLine($"#else");
            // Client-side body — no Config-resolve, no Server.Core reference.
            sb.AppendLine($"        protected System.Threading.Tasks.Task<{interfaceFqn}> Get{interfaceName}SiblingAsync()");
            sb.AppendLine("        {");
            sb.AppendLine($"            {interfaceFqn}? sibling = null;");
            sb.AppendLine($"            if (Context.SiblingServiceResolver != null)");
            sb.AppendLine($"                sibling = Context.SiblingServiceResolver(typeof({interfaceFqn})) as {interfaceFqn};");
            sb.AppendLine($"            if (sibling == null)");
            sb.AppendLine($"                sibling = new {implFqn}() {{ Context = Context }};");
            sb.AppendLine($"            return System.Threading.Tasks.Task.FromResult(sibling);");
            sb.AppendLine("        }");
            sb.AppendLine($"#endif");
        }

        /// <summary>
        /// 0.20.0: Read the dep service's ConfigType from <c>[MetaService(ConfigType = typeof(...))]</c>
        /// on the interface symbol. Returns null when the service has no associated config — the
        /// generated <c>Get{Iface}SiblingAsync()</c> in that case skips the async config refresh
        /// and returns the bare sibling instance.
        /// </summary>
        private static string? ReadDepConfigType(INamedTypeSymbol depInterface)
        {
            var metaServiceAttr = depInterface.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceAttribute");
            if (metaServiceAttr == null) return null;
            var configTypeArg = metaServiceAttr.NamedArguments.FirstOrDefault(a => a.Key == "ConfigType");
            if (configTypeArg.Value.Value is INamedTypeSymbol cfg)
                return cfg.ToDisplayString();
            return null;
        }

        /// <summary>
        /// 0.20.0: Generate the sibling-caller class for a dependency interface — an in-process
        /// adapter that exposes the async <c>{Iface}EntityCaller</c> shape but delegates each
        /// method to a real <c>I{Iface}</c> impl instance. Used when <see cref="GenerateEntityServiceGetter"/>'s
        /// runtime self-detect fires: the impl resolved via <c>MetaContext.SiblingServiceResolver</c>
        /// is wrapped in this caller, and the user's <c>await GetIInventoryService(self).GrantItemAsync(...)</c>
        /// becomes a typed direct call into the sibling, bypassing the cross-entity machinery
        /// (no arg serialization, no <c>CallEntityAsync</c>, no Orleans RPC).
        /// </summary>
        private static void GenerateSiblingCallerClass(StringBuilder sb, INamedTypeSymbol interfaceSymbol)
        {
            var interfaceName = interfaceSymbol.Name;
            var interfaceFqn = interfaceSymbol.ToDisplayString();
            var entityCallerInterface = $"{interfaceName}EntityCaller";

            var baseName = interfaceName;
            if (baseName.StartsWith("I") && baseName.Length > 1 && char.IsUpper(baseName[1]))
            {
                baseName = baseName.Substring(1);
            }

            sb.AppendLine();
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// In-process sibling caller for {interfaceName} (0.20.0).");
            sb.AppendLine($"    /// Implements {entityCallerInterface} by delegating each method to a typed");
            sb.AppendLine($"    /// {interfaceName} impl instance — used when the cross-entity getter detects");
            sb.AppendLine($"    /// a self-targeted call and the sibling lives on the same TState.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    internal class {baseName}SiblingCaller : {entityCallerInterface}");
            sb.AppendLine("    {");
            sb.AppendLine($"        private readonly {interfaceFqn} _impl;");
            sb.AppendLine();
            sb.AppendLine($"        public {baseName}SiblingCaller({interfaceFqn} impl)");
            sb.AppendLine("        {");
            sb.AppendLine("            _impl = impl;");
            sb.AppendLine("        }");

            foreach (var member in interfaceSymbol.GetMembers().OfType<IMethodSymbol>())
            {
                if (member.MethodKind == MethodKind.Ordinary)
                {
                    GenerateSiblingCallerMethod(sb, member, interfaceFqn);
                }
            }

            sb.AppendLine("    }");
        }

        private static void GenerateSiblingCallerMethod(StringBuilder sb, IMethodSymbol method, string interfaceFqn)
        {
            var methodName = method.Name;
            var returnType = method.ReturnType.ToDisplayString();
            var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"));
            var paramNames = method.Parameters.Select(p => p.Name).ToList();
            var callArgs = string.Join(", ", paramNames);

            var (isAsync, innerType) = ParseReturnType(returnType);

            // 0.22.0+: Notification sibling — same-grain self-target. Just call the impl and
            // discard the Task. No grain RPC, no recording. The impl mutates this entity's state
            // in place; subscribers of this entity get the broadcast as part of the outer op.
            if (IsNotificationMode(method))
            {
                sb.AppendLine();
                sb.AppendLine($"        [global::SharedMeta.Core.GeneratedFromMetaMethod(typeof(global::{interfaceFqn}), \"{methodName}\")]");
                sb.AppendLine($"        public void {methodName}({parameters})");
                sb.AppendLine("        {");
                if (isAsync)
                {
                    // Original returns Task — discard so we behave like a fire-and-forget.
                    sb.AppendLine($"            _ = _impl.{methodName}({callArgs});");
                }
                else if (returnType == "void")
                {
                    sb.AppendLine($"            _impl.{methodName}({callArgs});");
                }
                else
                {
                    sb.AppendLine($"            _impl.{methodName}({callArgs});");
                }
                sb.AppendLine("        }");
                return;
            }

            // Match the EntityCaller naming/return convention: void/sync→Task with Async
            // suffix, async stays as-is. The inner call to _impl uses the original signature.
            string asyncReturnType;
            string asyncMethodName;
            if (isAsync)
            {
                asyncReturnType = returnType;
                asyncMethodName = methodName;
            }
            else if (returnType == "void")
            {
                asyncReturnType = "Task";
                asyncMethodName = methodName + "Async";
            }
            else
            {
                asyncReturnType = $"Task<{returnType}>";
                asyncMethodName = methodName + "Async";
                innerType = returnType;
            }

            sb.AppendLine();
            sb.AppendLine($"        [global::SharedMeta.Core.GeneratedFromMetaMethod(typeof(global::{interfaceFqn}), \"{methodName}\")]");
            sb.AppendLine($"        public {asyncReturnType} {asyncMethodName}({parameters})");
            sb.AppendLine("        {");

            if (isAsync)
            {
                // Original is already async (Task / Task<T>) — direct passthrough.
                if (innerType != null)
                    sb.AppendLine($"            return _impl.{methodName}({callArgs});");
                else
                    sb.AppendLine($"            return _impl.{methodName}({callArgs});");
            }
            else if (returnType == "void")
            {
                sb.AppendLine($"            _impl.{methodName}({callArgs});");
                sb.AppendLine("            return Task.CompletedTask;");
            }
            else
            {
                sb.AppendLine($"            var result = _impl.{methodName}({callArgs});");
                sb.AppendLine($"            return Task.FromResult(result);");
            }

            sb.AppendLine("        }");
        }

        /// <summary>
        /// Generate getter for server services (e.g., ILobbyRequester).
        /// Server services are singleton services resolved from DI.
        /// </summary>
        private static void GenerateServerServiceGetter(StringBuilder sb, INamedTypeSymbol depSymbol)
        {
            var fullTypeName = depSymbol.ToDisplayString();
            var interfaceName = depSymbol.Name;
            var depNamespace = depSymbol.ContainingNamespace.ToDisplayString();

            // Property name: IRandomService -> RandomService
            var propName = interfaceName;
            if (propName.StartsWith("I") && propName.Length > 1 && char.IsUpper(propName[1]))
            {
                propName = propName.Substring(1);
            }

            // Base name for wrapper classes: IRandomService -> RandomService
            var baseName = propName;

            // Cache key - use typeof()
            var cacheKey = $"typeof({fullTypeName})";

            sb.AppendLine();
            sb.AppendLine($"        protected {fullTypeName} {propName} => Get{interfaceName}();");
            sb.AppendLine();
            sb.AppendLine($"        private {fullTypeName} Get{interfaceName}()");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (Context.TryGetCached({cacheKey}, out var cached))");
            sb.AppendLine($"                return ({fullTypeName})cached!;");
            sb.AppendLine();
            sb.AppendLine("            object wrapper;");
            sb.AppendLine("            if (Context.IsServer)");
            sb.AppendLine("            {");
            sb.AppendLine($"                // Server: Create Recorder wrapper");
            sb.AppendLine($"                var realImpl = Context.ResolveService<{fullTypeName}>();");
            sb.AppendLine($"                wrapper = new {depNamespace}.Server.{baseName}Recorder(realImpl, (IServerRecordContext)Context);");
            sb.AppendLine("            }");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            sb.AppendLine($"                // Client: Create Replayer wrapper");
            sb.AppendLine($"                wrapper = new {depNamespace}.Client.{baseName}Replayer((IClientReplayContext)Context);");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine($"            Context.CacheService({cacheKey}, wrapper);");
            sb.AppendLine($"            return ({fullTypeName})wrapper;");
            sb.AppendLine("        }");
        }

        /// <summary>
        /// Generate async EntityCaller interface for cross-entity calls.
        /// Methods are async versions of the original interface methods.
        /// </summary>
        private static void GenerateEntityCallerInterface(StringBuilder sb, INamedTypeSymbol interfaceSymbol, string containingNamespace)
        {
            var interfaceName = interfaceSymbol.Name;
            var interfaceFqn = interfaceSymbol.ToDisplayString();
            var entityCallerInterface = $"{interfaceName}EntityCaller";

            sb.AppendLine();
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Async interface for cross-entity calls to {interfaceName}.");
            sb.AppendLine($"    /// All methods are async to support inter-entity RPC.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public interface {entityCallerInterface}");
            sb.AppendLine("    {");

            foreach (var member in interfaceSymbol.GetMembers().OfType<IMethodSymbol>())
            {
                if (member.MethodKind == MethodKind.Ordinary)
                {
                    GenerateEntityCallerInterfaceMethod(sb, member, interfaceFqn);
                }
            }

            sb.AppendLine("    }");
        }

        private static void GenerateEntityCallerInterfaceMethod(StringBuilder sb, IMethodSymbol method, string interfaceFqn)
        {
            var methodName = method.Name;
            var returnType = method.ReturnType.ToDisplayString();
            var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"));

            var (isAsync, innerType) = ParseReturnType(returnType);

            // 0.22.0+: Mode = ExecutionMode.Notification flips this to a void cross-entity call
            // (entity → entity fire-and-forget, peer of Signal on the cross-entity axis). Async
            // variant is suppressed — the caller pattern becomes `GetIClanService(id).AddPower(delta);`
            // (no await), forcing any existing `await ...` call site to be updated.
            if (IsNotificationMode(method))
            {
                if (innerType != null && (isAsync == false || returnType != "System.Threading.Tasks.Task" && returnType != "Task"))
                {
                    sb.AppendLine($"#error SharedMeta: '{interfaceFqn}.{methodName}' has Mode = ExecutionMode.Notification but returns a value. Notification methods must return Task or void.");
                }
                sb.AppendLine($"        [global::SharedMeta.Core.GeneratedFromMetaMethod(typeof(global::{interfaceFqn}), \"{methodName}\")]");
                sb.AppendLine($"        void {methodName}({parameters});");
                return;
            }

            // Generate async version of the method
            string asyncReturnType;
            string asyncMethodName;

            if (isAsync)
            {
                // Already async - keep as is
                asyncReturnType = returnType;
                asyncMethodName = methodName;
            }
            else if (returnType == "void")
            {
                // void -> Task, add Async suffix
                asyncReturnType = "Task";
                asyncMethodName = methodName + "Async";
            }
            else
            {
                // T -> Task<T>, add Async suffix
                asyncReturnType = $"Task<{returnType}>";
                asyncMethodName = methodName + "Async";
            }

            sb.AppendLine($"        [global::SharedMeta.Core.GeneratedFromMetaMethod(typeof(global::{interfaceFqn}), \"{methodName}\")]");
            sb.AppendLine($"        {asyncReturnType} {asyncMethodName}({parameters});");
        }

        /// <summary>
        /// 0.22.0+: True when the method carries <c>[MetaMethod(Mode = ExecutionMode.Notification)]</c>.
        /// Cross-entity callers for Notification methods receive a void fire-and-forget variant
        /// on the EntityCaller interface instead of the async one — the source grain dispatches
        /// via the Orleans <c>[OneWay]</c> entry on the target and continues without awaiting.
        /// ExecutionMode.Notification = 8 (after Local=0, Optimistic=1, Server=2, CrossOptimistic=3,
        /// ServerPatch=4, ServerReplace=5, Query=6, Signal=7).
        /// </summary>
        private static bool IsNotificationMode(IMethodSymbol method)
        {
            var attr = method.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaMethodAttribute");
            if (attr == null) return false;
            var modeArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "Mode");
            return !modeArg.Value.IsNull && modeArg.Value.Value is int m && m == 8;
        }

        /// <summary>
        /// Generate entity recorder class for cross-entity calls.
        /// Implements the EntityCaller interface and calls via IServerRecordContext.
        /// </summary>
        private static void GenerateEntityRecorderClass(StringBuilder sb, INamedTypeSymbol interfaceSymbol, string containingNamespace, DetectedSerializer serializer)
        {
            var interfaceName = interfaceSymbol.Name;
            var interfaceFqn = interfaceSymbol.ToDisplayString();
            var entityCallerInterface = $"{interfaceName}EntityCaller";

            var baseName = interfaceName;
            if (baseName.StartsWith("I") && baseName.Length > 1 && char.IsUpper(baseName[1]))
            {
                baseName = baseName.Substring(1);
            }

            sb.AppendLine();
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Server-side recorder for cross-entity calls to {interfaceName}.");
            sb.AppendLine($"    /// Packs arguments and calls IServerRecordContext.CallEntityAsync.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    internal class {baseName}EntityRecorder : {entityCallerInterface}");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly string _entityId;");
            sb.AppendLine("        private readonly IServerRecordContext _context;");
            sb.AppendLine();
            sb.AppendLine($"        public {baseName}EntityRecorder(string entityId, IServerRecordContext context)");
            sb.AppendLine("        {");
            sb.AppendLine("            _entityId = entityId;");
            sb.AppendLine("            _context = context;");
            sb.AppendLine("        }");

            // Generate methods
            foreach (var member in interfaceSymbol.GetMembers().OfType<IMethodSymbol>())
            {
                if (member.MethodKind == MethodKind.Ordinary)
                {
                    GenerateEntityRecorderMethod(sb, member, interfaceName, interfaceFqn, serializer);
                }
            }

            sb.AppendLine("    }");
        }

        private static void GenerateEntityRecorderMethod(StringBuilder sb, IMethodSymbol method, string interfaceName, string interfaceFqn, DetectedSerializer serializer)
        {
            var methodName = method.Name;
            var returnType = method.ReturnType.ToDisplayString();

            // Get method alias from MetaMethod attribute if available
            var methodAlias = methodName;
            var metaMethodAttr = method.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaMethodAttribute");
            if (metaMethodAttr != null)
            {
                var aliasArg = metaMethodAttr.NamedArguments.FirstOrDefault(a => a.Key == "Alias");
                if (!aliasArg.Value.IsNull && aliasArg.Value.Value is string alias && !string.IsNullOrEmpty(alias))
                {
                    methodAlias = alias;
                }
            }

            // Build parameter list
            var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"));
            var paramNames = method.Parameters.Select(p => p.Name).ToList();

            var (isAsync, innerType) = ParseReturnType(returnType);

            // 0.22.0+: OneWay variant — emit void method that packs args and fires
            // _context.CallEntityOneWay(...) without awaiting or recording any result.
            if (IsNotificationMode(method))
            {
                sb.AppendLine();
                sb.AppendLine($"        [global::SharedMeta.Core.GeneratedFromMetaMethod(typeof(global::{interfaceFqn}), \"{methodName}\")]");
                sb.AppendLine($"        public void {methodName}({parameters})");
                sb.AppendLine("        {");
                GenerateArgumentPacking(sb, method.Parameters, paramNames, serializer);
                sb.AppendLine();
                sb.AppendLine($"            _context.CallEntityOneWay(_entityId, \"{interfaceName}\", \"{methodAlias}\", argsBytes);");
                sb.AppendLine("        }");
                return;
            }

            // Determine async method signature
            string asyncReturnType;
            string asyncMethodName;

            if (isAsync)
            {
                asyncReturnType = returnType;
                asyncMethodName = methodName;
            }
            else if (returnType == "void")
            {
                asyncReturnType = "Task";
                asyncMethodName = methodName + "Async";
            }
            else
            {
                asyncReturnType = $"Task<{returnType}>";
                asyncMethodName = methodName + "Async";
                innerType = returnType; // For non-async methods with return value
            }

            sb.AppendLine();
            sb.AppendLine($"        [global::SharedMeta.Core.GeneratedFromMetaMethod(typeof(global::{interfaceFqn}), \"{methodName}\")]");
            sb.AppendLine($"        public async {asyncReturnType} {asyncMethodName}({parameters})");
            sb.AppendLine("        {");

            // Serialize arguments based on detected serializer
            GenerateArgumentPacking(sb, method.Parameters, paramNames, serializer);

            // Call remote entity via context's CallEntityAsync
            // Errors are thrown as exceptions by the handler
            sb.AppendLine();
            sb.AppendLine($"            var resultBytes = await _context.CallEntityAsync(");
            sb.AppendLine($"                _entityId, \"{interfaceName}\", \"{methodAlias}\", argsBytes);");

            if (innerType != null)
            {
                // Has return value - deserialize and record
                sb.AppendLine();
                GenerateResultDeserialization(sb, innerType, serializer);
                sb.AppendLine("            _context.Writer.Write(result);");
                sb.AppendLine("            return result;");
            }
            // void async - nothing to return

            sb.AppendLine("        }");
        }

        /// <summary>
        /// Generate result deserialization code based on serializer type.
        /// </summary>
        private static void GenerateResultDeserialization(StringBuilder sb, string resultType, DetectedSerializer serializer)
        {
            if (serializer == DetectedSerializer.MemoryPack)
            {
                sb.AppendLine($"            var result = MemoryPackSerializer.Deserialize<{resultType}>(resultBytes)!;");
            }
            else
            {
                sb.AppendLine($"            var result = _context.Serializer.Unpack<{resultType}>(resultBytes)!;");
            }
        }

        /// <summary>
        /// Generate entity replayer class for cross-entity calls.
        /// Implements the EntityCaller interface and reads from replay payload.
        /// </summary>
        private static void GenerateEntityReplayerClass(StringBuilder sb, INamedTypeSymbol interfaceSymbol, string containingNamespace)
        {
            var interfaceName = interfaceSymbol.Name;
            var interfaceFqn = interfaceSymbol.ToDisplayString();
            var entityCallerInterface = $"{interfaceName}EntityCaller";

            var baseName = interfaceName;
            if (baseName.StartsWith("I") && baseName.Length > 1 && char.IsUpper(baseName[1]))
            {
                baseName = baseName.Substring(1);
            }

            sb.AppendLine();
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Client-side replayer for cross-entity calls to {interfaceName}.");
            sb.AppendLine($"    /// Reads results from the replay payload.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    internal class {baseName}EntityReplayer : {entityCallerInterface}");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly IClientReplayContext _context;");
            sb.AppendLine();
            sb.AppendLine($"        public {baseName}EntityReplayer(IClientReplayContext context)");
            sb.AppendLine("        {");
            sb.AppendLine("            _context = context;");
            sb.AppendLine("        }");

            // Generate methods
            foreach (var member in interfaceSymbol.GetMembers().OfType<IMethodSymbol>())
            {
                if (member.MethodKind == MethodKind.Ordinary)
                {
                    GenerateEntityReplayerMethod(sb, member, interfaceFqn);
                }
            }

            sb.AppendLine("    }");
        }

        private static void GenerateEntityReplayerMethod(StringBuilder sb, IMethodSymbol method, string interfaceFqn)
        {
            var methodName = method.Name;
            var returnType = method.ReturnType.ToDisplayString();
            var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"));

            var (isAsync, innerType) = ParseReturnType(returnType);

            // 0.22.0+: OneWay → emit void method that does nothing on replay. The server did
            // not record anything for this call (it was fire-and-forget), so the client-side
            // replay simply skips. Generated body intentionally consumes no payload bytes.
            if (IsNotificationMode(method))
            {
                sb.AppendLine();
                sb.AppendLine($"        [global::SharedMeta.Core.GeneratedFromMetaMethod(typeof(global::{interfaceFqn}), \"{methodName}\")]");
                sb.AppendLine($"        public void {methodName}({parameters})");
                sb.AppendLine("        {");
                sb.AppendLine("            // OneWay: nothing recorded server-side → nothing to replay.");
                sb.AppendLine("        }");
                return;
            }

            // Determine async method signature
            string asyncReturnType;
            string asyncMethodName;

            if (isAsync)
            {
                asyncReturnType = returnType;
                asyncMethodName = methodName;
            }
            else if (returnType == "void")
            {
                asyncReturnType = "Task";
                asyncMethodName = methodName + "Async";
            }
            else
            {
                asyncReturnType = $"Task<{returnType}>";
                asyncMethodName = methodName + "Async";
                innerType = returnType;
            }

            sb.AppendLine();
            sb.AppendLine($"        [global::SharedMeta.Core.GeneratedFromMetaMethod(typeof(global::{interfaceFqn}), \"{methodName}\")]");
            sb.AppendLine($"        public {asyncReturnType} {asyncMethodName}({parameters})");
            sb.AppendLine("        {");

            if (innerType != null)
            {
                // Has return value - read from replay
                sb.AppendLine($"            var result = _context.Reader.Read<{innerType}>();");
                sb.AppendLine("            return Task.FromResult(result);");
            }
            else
            {
                // void - nothing to read
                sb.AppendLine("            return Task.CompletedTask;");
            }

            sb.AppendLine("        }");
        }

        /// <summary>
        /// Generate local entity caller class for CrossOptimistic mode.
        /// Executes methods locally on the target entity's state and records results.
        /// </summary>
        private static void GenerateLocalEntityCallerClass(StringBuilder sb, INamedTypeSymbol interfaceSymbol, string containingNamespace, string callerStateTypeName)
        {
            var interfaceName = interfaceSymbol.Name;
            var interfaceFqn = interfaceSymbol.ToDisplayString();
            var entityCallerInterface = $"{interfaceName}EntityCaller";

            var baseName = interfaceName;
            if (baseName.StartsWith("I") && baseName.Length > 1 && char.IsUpper(baseName[1]))
            {
                baseName = baseName.Substring(1);
            }

            // Get target state type from [MetaService(StateType = ...)] attribute
            var metaServiceAttr = interfaceSymbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceAttribute");
            string? targetStateType = null;
            if (metaServiceAttr != null)
            {
                var stateTypeArg = metaServiceAttr.NamedArguments.FirstOrDefault(a => a.Key == "StateType");
                if (stateTypeArg.Value.Value is INamedTypeSymbol stateType)
                {
                    targetStateType = stateType.ToDisplayString();
                }
            }

            // Fallback: infer state type from interface name
            if (targetStateType == null)
            {
                var ifaceName = interfaceName.StartsWith("I") ? interfaceName.Substring(1) : interfaceName;
                if (ifaceName.EndsWith("Service"))
                {
                    targetStateType = interfaceSymbol.ContainingNamespace.ToDisplayString() + "." +
                        ifaceName.Substring(0, ifaceName.Length - 7) + "State";
                }
            }

            if (targetStateType == null) return;

            var implNamespace = interfaceSymbol.ContainingNamespace.ToDisplayString();

            sb.AppendLine();
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Client-side local entity caller for {interfaceName} (CrossOptimistic mode).");
            sb.AppendLine($"    /// Executes methods locally on the target entity's state.");
            sb.AppendLine($"    /// Records results for desync comparison.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    internal class {baseName}LocalEntityCaller : {entityCallerInterface}");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly string _entityId;");
            sb.AppendLine("        private readonly ICrossEntityResolver _resolver;");
            sb.AppendLine();
            sb.AppendLine($"        public {baseName}LocalEntityCaller(string entityId, ICrossEntityResolver resolver)");
            sb.AppendLine("        {");
            sb.AppendLine("            _entityId = entityId;");
            sb.AppendLine("            _resolver = resolver;");
            sb.AppendLine("        }");

            // Generate methods
            foreach (var member in interfaceSymbol.GetMembers().OfType<IMethodSymbol>())
            {
                if (member.MethodKind == MethodKind.Ordinary)
                {
                    GenerateLocalEntityCallerMethod(sb, member, interfaceName, interfaceFqn, baseName, targetStateType, implNamespace);
                }
            }

            sb.AppendLine("    }");
        }

        private static void GenerateLocalEntityCallerMethod(StringBuilder sb, IMethodSymbol method,
            string interfaceName, string interfaceFqn, string baseName, string targetStateType, string implNamespace)
        {
            var methodName = method.Name;
            var returnType = method.ReturnType.ToDisplayString();
            var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"));
            var paramNames = method.Parameters.Select(p => p.Name).ToList();
            var callArgs = string.Join(", ", paramNames);

            var (isAsync, innerType) = ParseReturnType(returnType);

            // 0.22.0+: OneWay variant for CrossOptimistic mode is a void no-op locally — the
            // server-side dispatch happens via the optimistic→server confirm flow as usual,
            // but the caller doesn't observe a result, so the local-side call body is just empty.
            // Keep the subscription gate so CrossOptimistic continues to treat unknown entities
            // as a soft-fail (no exception, no state mutation).
            if (IsNotificationMode(method))
            {
                sb.AppendLine();
                sb.AppendLine($"        [global::SharedMeta.Core.GeneratedFromMetaMethod(typeof(global::{interfaceFqn}), \"{methodName}\")]");
                sb.AppendLine($"        public void {methodName}({parameters})");
                sb.AppendLine("        {");
                sb.AppendLine("            // OneWay + CrossOptimistic: no local execution. The server-side path");
                sb.AppendLine("            // fires the cross-entity OneWay; the client observes nothing here.");
                sb.AppendLine("        }");
                return;
            }

            string asyncReturnType;
            string asyncMethodName;

            if (isAsync)
            {
                asyncReturnType = returnType;
                asyncMethodName = methodName;
            }
            else if (returnType == "void")
            {
                asyncReturnType = "Task";
                asyncMethodName = methodName + "Async";
            }
            else
            {
                asyncReturnType = $"Task<{returnType}>";
                asyncMethodName = methodName + "Async";
                innerType = returnType;
            }

            string awaitPrefix = isAsync ? "await " : "";

            // Get method alias from MetaMethod attribute if available
            var methodAlias = methodName;
            var metaMethodAttr = method.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaMethodAttribute");
            if (metaMethodAttr != null)
            {
                var aliasArg = metaMethodAttr.NamedArguments.FirstOrDefault(a => a.Key == "Alias");
                if (!aliasArg.Value.IsNull && aliasArg.Value.Value is string alias && !string.IsNullOrEmpty(alias))
                {
                    methodAlias = alias;
                }
            }

            sb.AppendLine();
            sb.AppendLine($"        [global::SharedMeta.Core.GeneratedFromMetaMethod(typeof(global::{interfaceFqn}), \"{methodName}\")]");
            sb.AppendLine($"        public {asyncReturnType} {asyncMethodName}({parameters})");
            sb.AppendLine("        {");

            // Check subscription synchronously — no network calls allowed.
            // If not subscribed, silently return default. The CrossOptimistic method
            // continues execution — other cross-entity calls to subscribed entities still work.
            sb.AppendLine("            if (!_resolver.IsSubscribed(_entityId))");
            if (innerType != null)
            {
                sb.AppendLine($"                return Task.FromResult(default({innerType})!);");
            }
            else
            {
                sb.AppendLine("                return Task.CompletedTask;");
            }
            sb.AppendLine($"            var state = ({targetStateType})_resolver.GetEntityState(_entityId);");
            sb.AppendLine();

            // Save and set context (inherit ServerTimeTicks from parent for deterministic time)
            sb.AppendLine("            var prevCtx = MetaContextAccessor.Current;");
            sb.AppendLine($"            var ctx = new CrossOptimisticMetaContext<{targetStateType}>(state);");
            sb.AppendLine("            ctx.CrossEntityResolver = _resolver;");
            sb.AppendLine("            ctx.ServerTimeTicks = prevCtx?.ServerTimeTicks ?? 0;");
            sb.AppendLine("            ctx.Log = prevCtx?.Log ?? SharedMeta.Core.Logging.NullMetaLogger.Instance;");
            sb.AppendLine("            ctx.Config = _resolver.GetEntityConfig(_entityId);");
            sb.AppendLine("            MetaContextAccessor.Current = ctx;");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                var service = new {implNamespace}.{baseName}() {{ Context = ctx }};");

            if (innerType != null)
            {
                if (isAsync)
                {
                    // Service method returns Task<T> — call and extract result synchronously.
                    // All cross-entity calls within complete synchronously (LocalEntityCaller/EntityReplayer),
                    // so the Task is guaranteed to be completed.
                    sb.AppendLine($"                var task = service.{methodName}({callArgs});");
                    sb.AppendLine($"                var result = task.GetAwaiter().GetResult();");
                }
                else
                {
                    sb.AppendLine($"                var result = service.{methodName}({callArgs});");
                }
                sb.AppendLine($"                _resolver.RecordCrossEntityResult(_entityId, \"{interfaceName}\", \"{methodAlias}\", result);");
                sb.AppendLine($"                return Task.FromResult(result);");
            }
            else
            {
                if (isAsync)
                {
                    sb.AppendLine($"                service.{methodName}({callArgs}).GetAwaiter().GetResult();");
                }
                else
                {
                    sb.AppendLine($"                service.{methodName}({callArgs});");
                }
                sb.AppendLine($"                _resolver.RecordCrossEntityResult(_entityId, \"{interfaceName}\", \"{methodAlias}\", null);");
                sb.AppendLine("                return Task.CompletedTask;");
            }

            sb.AppendLine("            }");
            sb.AppendLine("            finally");
            sb.AppendLine("            {");
            sb.AppendLine("                MetaContextAccessor.Current = prevCtx;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        /// <summary>
        /// Generate argument packing code based on serializer type.
        /// </summary>
        private static void GenerateArgumentPacking(
            StringBuilder sb,
            System.Collections.Immutable.ImmutableArray<IParameterSymbol> parameters,
            List<string> paramNames,
            DetectedSerializer serializer)
        {
            if (paramNames.Count == 0)
            {
                sb.AppendLine("            var argsBytes = Array.Empty<byte>();");
                return;
            }

            if (serializer == DetectedSerializer.MemoryPack)
            {
                // MemoryPack: use MemoryPackSerializer for direct serialization
                if (paramNames.Count == 1)
                {
                    sb.AppendLine($"            var argsBytes = MemoryPackSerializer.Serialize({paramNames[0]});");
                }
                else
                {
                    // Multiple parameters: serialize to ArrayBufferWriter sequentially
                    sb.AppendLine("            var buffer = new ArrayBufferWriter<byte>();");
                    foreach (var paramName in paramNames)
                    {
                        sb.AppendLine($"            MemoryPackSerializer.Serialize(buffer, {paramName});");
                    }
                    sb.AppendLine("            var argsBytes = buffer.WrittenSpan.ToArray();");
                }
            }
            else
            {
                // Generic: always use IPayloadWriter for consistent length-prefixed format.
                // Server dispatcher reads with CreateReader() which expects length-prefixed data.
                sb.AppendLine("            using var writer = _context.Serializer.CreateWriter();");
                foreach (var paramName in paramNames)
                {
                    sb.AppendLine($"            writer.Write({paramName});");
                }
                sb.AppendLine("            var argsBytes = writer.Complete();");
            }
        }

        /// <summary>
        /// Parse async return type. Returns (isAsync, innerType).
        /// Task -> (true, null), Task&lt;bool&gt; -> (true, "bool"), int -> (false, "int")
        /// </summary>
        private static (bool isAsync, string? innerType) ParseReturnType(string returnType)
        {
            if (returnType == "System.Threading.Tasks.Task" || returnType == "Task")
                return (true, null);

            var match = Regex.Match(returnType, @"^(?:System\.Threading\.Tasks\.)?Task<(.+)>$");
            if (match.Success)
                return (true, match.Groups[1].Value);

            if (returnType == "void")
                return (false, null);

            return (false, returnType);
        }

        /// <summary>
        /// Check if a type has properties with serialization ordinal attributes
        /// ([Id], [Key], [MemoryPackOrder]) — same set StatePatchGenerator uses.
        /// </summary>
        private static string? FindDefaultConfigType(Compilation compilation)
        {
            // Search source types
            var result = FindDefaultConfigTypeInNamespace(compilation.Assembly.GlobalNamespace);
            if (result != null) return result;

            // Search referenced assemblies
            foreach (var reference in compilation.References)
            {
                var assemblySymbol = compilation.GetAssemblyOrModuleSymbol(reference) as IAssemblySymbol;
                if (assemblySymbol == null) continue;
                var name = assemblySymbol.Name;
                if (name.StartsWith("System") || name.StartsWith("Microsoft") ||
                    name.StartsWith("netstandard") || name.StartsWith("SharedMeta"))
                    continue;

                result = FindDefaultConfigTypeInNamespace(assemblySymbol.GlobalNamespace);
                if (result != null) return result;
            }
            return null;
        }

        /// <summary>
        /// 0.20.0: Read the dep entity-service's TState directly from
        /// <c>[MetaService(StateType = typeof(...))]</c> on the interface symbol — no compilation
        /// scan, attribute is already on the symbol. Every entity service is bound to a TState
        /// (no entity service can exist without one — that's where it lives), so this lookup
        /// must succeed for any well-formed entity service. Returns null only when the attribute
        /// is missing or doesn't set <c>StateType</c> — caller emits a generator error.
        /// </summary>
        private static string? ReadDepStateType(INamedTypeSymbol depInterface)
        {
            var metaServiceAttr = depInterface.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceAttribute");
            if (metaServiceAttr == null) return null;
            var stateTypeArg = metaServiceAttr.NamedArguments.FirstOrDefault(a => a.Key == "StateType");
            if (stateTypeArg.Value.Value is INamedTypeSymbol stateType)
                return stateType.ToDisplayString();
            return null;
        }

        private static string? FindDefaultConfigTypeInNamespace(INamespaceSymbol ns)
        {
            foreach (var type in ns.GetTypeMembers())
            {
                var attr = type.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaConfigAttribute");
                if (attr != null)
                {
                    var defaultArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "Default");
                    if (!defaultArg.Value.IsNull && defaultArg.Value.Value is true)
                        return type.ToDisplayString();
                }
            }
            foreach (var childNs in ns.GetNamespaceMembers())
            {
                var result = FindDefaultConfigTypeInNamespace(childNs);
                if (result != null) return result;
            }
            return null;
        }

        private static bool HasSerializationOrdinalAttributes(INamedTypeSymbol type)
        {
            return type.GetMembers().OfType<IPropertySymbol>().Any(p =>
                p.DeclaredAccessibility == Accessibility.Public &&
                !p.IsStatic &&
                p.GetMethod != null && p.SetMethod != null &&
                p.GetAttributes().Any(a =>
                {
                    var name = a.AttributeClass?.Name;
                    var ns = a.AttributeClass?.ContainingNamespace.ToDisplayString();
                    return (name == "IdAttribute" && ns == "Orleans") ||
                           (name == "KeyAttribute" && ns == "MessagePack") ||
                           (name == "MemoryPackOrderAttribute" && ns == "MemoryPack");
                }));
        }
    }
}
