using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Emits <c>MetaDescribe</c> overloads for the result types of every <c>[MetaService]</c>
    /// method in the assembly.
    /// </summary>
    /// <remarks>
    /// A desync message interpolates the two result values. For a DTO that does not override
    /// <c>ToString()</c> that prints the type name — twice, identically — so the log says a
    /// desync happened but not what diverged. Reflection would answer it at runtime, but the
    /// clients that need this most are IL2CPP builds where member reflection is exactly what
    /// gets stripped. So the dump is resolved at compile time instead.
    ///
    /// The generated overloads land in the same namespace as the runtime generic fallback and
    /// are found through extension-method lookup: call sites always write
    /// <c>value.MetaDescribe()</c>, and overload resolution prefers the concrete overload when
    /// one was generated. Types that already override <c>ToString()</c> (records included) get
    /// no overload — their own rendering wins.
    ///
    /// The class is internal on purpose. Two meta assemblies referenced by one project would
    /// otherwise both offer a public overload for a shared DTO and every call would be an
    /// ambiguous-match compile error.
    /// </remarks>
    internal static class DesyncFormatterGenerator
    {
        private const string MetaServiceAttribute = "SharedMeta.Core.MetaServiceAttribute";
        private const string MetaMethodAttribute = "SharedMeta.Core.MetaMethodAttribute";
        private const string OptionsAttribute = "SharedMeta.Core.SharedMetaDiagnosticsOptionsAttribute";

        /// <summary>Mirrors <c>MetaDescribeFallback.MaxDepth</c> — a type first reachable at this
        /// nesting level can only ever be rendered by the runtime depth guard, so no formatter
        /// is emitted for it.</summary>
        private const int MaxDepth = 3;

        private enum Detail { Full, Short }

        public static string? Generate(Compilation compilation)
        {
            var detail = ReadDetail(compilation);
            var roots = CollectResultTypes(compilation);
            if (roots.Count == 0) return null;

            var plans = BuildPlans(compilation, roots, detail);
            if (plans.Count == 0) return null;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace SharedMeta.Core.Diagnostics.Formatting");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Compile-time value dumps for meta method result types — desync diagnostics print");
            sb.AppendLine($"    /// these instead of a bare type name. Detail level: {detail}.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    internal static class MetaDescribeGenerated_{Sanitize(compilation.AssemblyName ?? "Assembly")}");
            sb.AppendLine("    {");

            foreach (var plan in plans)
            {
                if (plan.Element != null)
                    EmitSequenceFormatter(sb, plan, detail);
                else
                    EmitTypeFormatter(sb, plan, detail);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ───────────────────────── options ─────────────────────────

        private static Detail ReadDetail(Compilation compilation)
        {
            foreach (var attr in compilation.Assembly.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() != OptionsAttribute) continue;
                foreach (var named in attr.NamedArguments)
                {
                    if (named.Key != "DesyncValues" || named.Value.IsNull) continue;
                    // Enum arrives as its underlying int; match by member name so a reordered
                    // enum cannot silently flip the meaning.
                    if (named.Value.Value is int value &&
                        EnumMemberName(named.Value.Type, value) == "Short")
                    {
                        return Detail.Short;
                    }
                }
            }
            return Detail.Full;
        }

        private static string? EnumMemberName(ITypeSymbol? enumType, int value)
        {
            if (enumType == null) return null;
            foreach (var field in enumType.GetMembers().OfType<IFieldSymbol>())
            {
                if (field.HasConstantValue && field.ConstantValue is int fieldValue && fieldValue == value)
                    return field.Name;
            }
            return null;
        }

        // ───────────────────────── discovery ─────────────────────────

        private static List<ITypeSymbol> CollectResultTypes(Compilation compilation)
        {
            var result = new List<ITypeSymbol>();
            var seen = new HashSet<string>();

            foreach (var type in EnumerateTypes(compilation.Assembly.GlobalNamespace))
            {
                if (type.TypeKind != TypeKind.Interface) continue;
                if (!type.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == MetaServiceAttribute))
                    continue;

                var methods = type.GetMembers().OfType<IMethodSymbol>()
                    .Concat(type.AllInterfaces.SelectMany(i => i.GetMembers().OfType<IMethodSymbol>()));

                foreach (var method in methods)
                {
                    if (SkipsResultComparison(method)) continue;

                    var returnType = UnwrapTask(method.ReturnType);
                    if (returnType == null) continue;
                    if (seen.Add(Fq(returnType))) result.Add(returnType);
                }
            }
            return result;
        }

        private static IEnumerable<INamedTypeSymbol> EnumerateTypes(INamespaceSymbol ns)
        {
            foreach (var member in ns.GetMembers())
            {
                if (member is INamespaceSymbol child)
                {
                    foreach (var nested in EnumerateTypes(child)) yield return nested;
                }
                else if (member is INamedTypeSymbol type)
                {
                    yield return type;
                    foreach (var nested in type.GetTypeMembers()) yield return nested;
                }
            }
        }

        /// <summary>Query reads never compare a local result against the server's — nothing to describe.</summary>
        private static bool SkipsResultComparison(IMethodSymbol method)
        {
            var attr = method.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == MetaMethodAttribute);
            if (attr == null) return false;

            foreach (var named in attr.NamedArguments)
            {
                if (named.Key == "Query" && !named.Value.IsNull && named.Value.Value is true)
                    return true;
                if (named.Key == "Mode" && !named.Value.IsNull && named.Value.Value is int mode)
                {
                    var name = EnumMemberName(named.Value.Type, mode);
                    if (name == "Query" || name == "LocalQuery") return true;
                }
            }
            return false;
        }

        private static ITypeSymbol? UnwrapTask(ITypeSymbol returnType)
        {
            if (returnType.SpecialType == SpecialType.System_Void) return null;

            if (returnType is INamedTypeSymbol named &&
                (named.Name == "Task" || named.Name == "ValueTask") &&
                named.ContainingNamespace?.ToDisplayString() == "System.Threading.Tasks")
            {
                if (!named.IsGenericType || named.TypeArguments.Length == 0) return null;
                return named.TypeArguments[0];
            }
            return returnType;
        }

        // ───────────────────────── planning ─────────────────────────

        private sealed class FormatterPlan
        {
            public ITypeSymbol Type = null!;
            /// <summary>Set when the type is a collection — the formatter lists elements instead of members.</summary>
            public ITypeSymbol? Element;
        }

        private static List<FormatterPlan> BuildPlans(Compilation compilation, List<ITypeSymbol> roots, Detail detail)
        {
            var plans = new List<FormatterPlan>();
            var seen = new HashSet<string>();
            var queue = new Queue<(ITypeSymbol Type, int Hop)>(roots.Select(r => (r, 0)));

            while (queue.Count > 0)
            {
                var (type, hop) = queue.Dequeue();
                if (hop >= MaxDepth) continue;
                if (!seen.Add(Fq(type))) continue;

                var element = ElementType(type);
                if (element != null)
                {
                    // Collections only need their own formatter when they are the described value
                    // itself; as a member they are rendered inline by the owning formatter.
                    if (hop == 0 && IsAccessible(compilation, type))
                    {
                        plans.Add(new FormatterPlan { Type = type, Element = element });
                        if (detail == Detail.Full) queue.Enqueue((element, hop + 1));
                    }
                    continue;
                }

                if (!NeedsFormatter(compilation, type)) continue;

                plans.Add(new FormatterPlan { Type = type });
                if (detail == Detail.Short) continue;

                foreach (var (_, memberType) in DescribableMembers((INamedTypeSymbol)type))
                {
                    var memberElement = ElementType(memberType);
                    queue.Enqueue((memberElement ?? memberType, hop + 1));
                }
            }
            return plans;
        }

        private static bool NeedsFormatter(Compilation compilation, ITypeSymbol type)
        {
            if (type is not INamedTypeSymbol named) return false;
            if (named.TypeKind != TypeKind.Class && named.TypeKind != TypeKind.Struct) return false;
            if (IsScalar(named)) return false;
            if (named.IsRecord) return false;           // compiler-synthesized ToString prints members
            if (HasToStringOverride(named)) return false;
            if (!IsAccessible(compilation, named)) return false;
            return DescribableMembers(named).Any();
        }

        private static bool HasToStringOverride(INamedTypeSymbol type)
        {
            for (var current = type; current != null && current.SpecialType != SpecialType.System_Object; current = current.BaseType)
            {
                foreach (var member in current.GetMembers("ToString").OfType<IMethodSymbol>())
                {
                    if (!member.IsStatic && member.Parameters.Length == 0) return true;
                }
            }
            return false;
        }

        private static bool IsAccessible(Compilation compilation, ITypeSymbol type)
        {
            if (type is IArrayTypeSymbol array) return IsAccessible(compilation, array.ElementType);

            for (var current = type; current != null; current = current.ContainingType)
            {
                switch (current.DeclaredAccessibility)
                {
                    case Accessibility.Public:
                        break;
                    case Accessibility.Internal:
                        if (!SymbolEqualityComparer.Default.Equals(current.ContainingAssembly, compilation.Assembly))
                            return false;
                        break;
                    default:
                        return false;
                }
            }

            if (type is INamedTypeSymbol named)
            {
                foreach (var argument in named.TypeArguments)
                    if (!IsAccessible(compilation, argument)) return false;
            }
            return true;
        }

        private static IEnumerable<(string Name, ITypeSymbol Type)> DescribableMembers(INamedTypeSymbol type)
        {
            var emitted = new HashSet<string>();
            for (var current = type; current != null && current.SpecialType != SpecialType.System_Object; current = current.BaseType)
            {
                foreach (var member in current.GetMembers())
                {
                    if (member.IsStatic || member.DeclaredAccessibility != Accessibility.Public) continue;

                    if (member is IPropertySymbol property)
                    {
                        if (property.GetMethod == null || property.Parameters.Length > 0) continue;
                        if (emitted.Add(property.Name)) yield return (property.Name, property.Type);
                    }
                    else if (member is IFieldSymbol field)
                    {
                        if (field.IsImplicitlyDeclared || field.IsConst) continue;
                        if (emitted.Add(field.Name)) yield return (field.Name, field.Type);
                    }
                }
            }
        }

        // ───────────────────────── emission ─────────────────────────

        private static void EmitTypeFormatter(StringBuilder sb, FormatterPlan plan, Detail detail)
        {
            var named = (INamedTypeSymbol)plan.Type;
            var isStruct = named.TypeKind == TypeKind.Struct;
            var fq = Fq(named);

            var parts = new List<string>();
            foreach (var (name, memberType) in DescribableMembers(named))
                parts.Add($"\"{name} = \" + {MemberExpression(memberType, "value." + name, detail)}");
            if (parts.Count == 0) return;

            sb.AppendLine();
            sb.AppendLine($"        public static string MetaDescribe(this {fq}{(isStruct ? "" : "?")} value, int depth = 0)");
            sb.AppendLine("        {");
            if (!isStruct) sb.AppendLine("            if (value is null) return \"<null>\";");
            sb.AppendLine($"            if (depth >= MetaDescribeFallback.MaxDepth) return \"<{named.Name}>\";");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine($"                return \"{named.Name} {{ \"");
            for (int i = 0; i < parts.Count; i++)
            {
                var separator = i == 0 ? "" : "\", \" + ";
                sb.AppendLine($"                    + {separator}{parts[i]}");
            }
            sb.AppendLine("                    + \" }\";");
            sb.AppendLine("            }");
            // A computed member can throw on a half-built value; a diagnostics dump must never
            // replace the desync it is reporting with an exception of its own.
            sb.AppendLine($"            catch (System.Exception ex) {{ return \"<{named.Name}: \" + ex.GetType().Name + \">\"; }}");
            sb.AppendLine("        }");

            if (isStruct)
            {
                sb.AppendLine();
                sb.AppendLine($"        public static string MetaDescribe(this {fq}? value, int depth = 0)");
                sb.AppendLine($"            => value is null ? \"<null>\" : value.Value.MetaDescribe(depth);");
            }
        }

        private static void EmitSequenceFormatter(StringBuilder sb, FormatterPlan plan, Detail detail)
        {
            var fq = Fq(plan.Type);
            var suffix = plan.Type.IsValueType ? "" : "?";

            sb.AppendLine();
            sb.AppendLine($"        public static string MetaDescribe(this {fq}{suffix} value, int depth = 0)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return {SequenceExpression(plan.Element!, "value", detail)};");
            sb.AppendLine("        }");
        }

        private static string MemberExpression(ITypeSymbol memberType, string access, Detail detail)
        {
            var element = ElementType(memberType);
            if (element != null) return SequenceExpression(element, access, detail);

            if (detail == Detail.Short && !IsScalar(memberType))
                return $"\"<{memberType.Name}>\"";

            return $"{access}.MetaDescribe(depth + 1)";
        }

        private static string SequenceExpression(ITypeSymbol element, string access, Detail detail)
        {
            if (detail == Detail.Short)
                return $"MetaDescribeFallback.MetaDescribeCount({access})";

            // Cast to the exact IEnumerable<T> being described: a type implementing the interface
            // more than once binds ambiguously otherwise.
            var sequence = $"((global::System.Collections.Generic.IEnumerable<{Fq(element)}>?){access})";
            var pair = AsKeyValuePair(element);
            return pair != null
                ? $"{sequence}.MetaDescribeSeq(x => x.Key.MetaDescribe(depth + 1) + \"=\" + x.Value.MetaDescribe(depth + 1))"
                : $"{sequence}.MetaDescribeSeq(x => x.MetaDescribe(depth + 1))";
        }

        // ───────────────────────── type facts ─────────────────────────

        private static bool IsScalar(ITypeSymbol type)
        {
            if (type.TypeKind == TypeKind.Enum) return true;

            switch (type.SpecialType)
            {
                case SpecialType.System_Boolean:
                case SpecialType.System_Char:
                case SpecialType.System_SByte:
                case SpecialType.System_Byte:
                case SpecialType.System_Int16:
                case SpecialType.System_UInt16:
                case SpecialType.System_Int32:
                case SpecialType.System_UInt32:
                case SpecialType.System_Int64:
                case SpecialType.System_UInt64:
                case SpecialType.System_Decimal:
                case SpecialType.System_Single:
                case SpecialType.System_Double:
                case SpecialType.System_String:
                case SpecialType.System_DateTime:
                case SpecialType.System_Object:
                case SpecialType.System_IntPtr:
                case SpecialType.System_UIntPtr:
                    return true;
            }

            if (type is INamedTypeSymbol named)
            {
                if (named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T && named.TypeArguments.Length == 1)
                    return IsScalar(named.TypeArguments[0]);

                switch (named.ToDisplayString())
                {
                    case "System.Guid":
                    case "System.TimeSpan":
                    case "System.DateTimeOffset":
                        return true;
                }
            }
            return false;
        }

        /// <summary>Element type when <paramref name="type"/> is a collection; <c>null</c> otherwise.
        /// Strings are scalars here, not sequences of char.</summary>
        private static ITypeSymbol? ElementType(ITypeSymbol type)
        {
            if (IsScalar(type)) return null;
            if (type is IArrayTypeSymbol array) return array.ElementType;
            if (type is not INamedTypeSymbol named) return null;

            if (named.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T &&
                named.TypeArguments.Length == 1)
            {
                return named.TypeArguments[0];
            }

            foreach (var candidate in named.AllInterfaces)
            {
                if (candidate.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T &&
                    candidate.TypeArguments.Length == 1)
                {
                    return candidate.TypeArguments[0];
                }
            }
            return null;
        }

        private static INamedTypeSymbol? AsKeyValuePair(ITypeSymbol type)
        {
            if (type is INamedTypeSymbol named &&
                named.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.KeyValuePair<TKey, TValue>")
            {
                return named;
            }
            return null;
        }

        private static string Fq(ITypeSymbol type)
            => type.WithNullableAnnotation(NullableAnnotation.None)
                   .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        private static string Sanitize(string name)
        {
            var sb = new StringBuilder(name.Length);
            foreach (var c in name) sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            return sb.ToString();
        }
    }
}
