using System.Text;
using System.Linq;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Generates a static class that configures MetaMessagePackOptions with CompositeResolver
    /// composed from source-generated resolvers of all assemblies containing [MessagePackObject] types.
    ///
    /// Output: GeneratedMetaMessagePackConfiguration.Configure()
    ///
    /// The generator scans referenced assemblies for [assembly: GeneratedAssemblyMessagePackResolverAttribute]
    /// (placed by MessagePack's source generator) and picks a representative type from each assembly
    /// to generate typeof(X).Assembly references for MetaMessagePackOptions.Configure().
    /// </summary>
    public static class MessagePackConfigurationGenerator
    {
        private static readonly SymbolDisplayFormat QualifiedFormatNoGenerics = new SymbolDisplayFormat(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.None);

        private static readonly SymbolDisplayFormat QualifiedFormat = new SymbolDisplayFormat(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces);

        public static string? Generate(Compilation compilation)
        {
            // Only generate if MetaMessagePackOptions is accessible
            var metaOptionsType = compilation.GetTypeByMetadataName(
                "SharedMeta.Serialization.MessagePack.MetaMessagePackOptions");
            if (metaOptionsType == null)
            {
                return null;
            }

            // Skip if we're compiling the serializer assembly itself
            // (MetaMessagePackOptions is defined here, not just referenced)
            if (SymbolEqualityComparer.Default.Equals(
                    metaOptionsType.ContainingAssembly, compilation.Assembly))
            {
                return null;
            }

            var messagePackObjectAttr = "MessagePack.MessagePackObjectAttribute";
            var resolverAssemblyAttr = "MessagePack.Internal.GeneratedAssemblyMessagePackResolverAttribute";

            var entries = new List<AssemblyEntry>();

            // Scan referenced assemblies for generated MessagePack resolvers
            foreach (var reference in compilation.References)
            {
                var asm = compilation.GetAssemblyOrModuleSymbol(reference) as IAssemblySymbol;
                if (asm == null) continue;

                var name = asm.Name;
                if (name.StartsWith("System") || name.StartsWith("Microsoft") ||
                    name.StartsWith("netstandard") || name == "mscorlib")
                    continue;

                // Check if assembly has [assembly: GeneratedAssemblyMessagePackResolverAttribute]
                var hasResolver = asm.GetAttributes().Any(a =>
                    a.AttributeClass?.ToDisplayString() == resolverAssemblyAttr);
                if (!hasResolver) continue;

                // Find a representative public type with [MessagePackObject]
                var rep = FindFirstMessagePackType(asm.GlobalNamespace, messagePackObjectAttr);
                if (rep != null)
                {
                    entries.Add(new AssemblyEntry { AssemblyName = name, TypeofExpression = GetTypeofExpression(rep) });
                }
            }

            // Also check current compilation for [MessagePackObject] types
            var currentRep = FindFirstMessagePackType(compilation.Assembly.GlobalNamespace, messagePackObjectAttr);
            if (currentRep != null)
            {
                entries.Insert(0, new AssemblyEntry
                {
                    AssemblyName = compilation.AssemblyName ?? "current",
                    TypeofExpression = GetTypeofExpression(currentRep)
                });
            }

            if (entries.Count == 0) return null;

            // Generate the configuration class
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using SharedMeta.Serialization.MessagePack;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Generated MessagePack resolver configuration.");
            sb.AppendLine("/// Composes source-generated resolvers from all referenced assemblies");
            sb.AppendLine("/// containing [MessagePackObject] types into a CompositeResolver.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("internal static class GeneratedMetaMessagePackConfiguration");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Configure MetaMessagePackOptions with CompositeResolver.");
            sb.AppendLine("    /// Call this at startup before creating MessagePackMetaSerializer or configuring SignalR.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static void Configure()");
            sb.AppendLine("    {");
            sb.AppendLine("        MetaMessagePackOptions.Configure(");

            for (int i = 0; i < entries.Count; i++)
            {
                var entry = entries[i];
                var comma = i < entries.Count - 1 ? "," : "";
                sb.AppendLine($"            {entry.TypeofExpression}.Assembly{comma} // {entry.AssemblyName}");
            }

            sb.AppendLine("        );");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string GetTypeofExpression(INamedTypeSymbol type)
        {
            if (!type.IsGenericType)
            {
                return $"typeof({type.ToDisplayString(QualifiedFormat)})";
            }

            // For generic types: EntityGrainState<TState> → typeof(EntityGrainState<>)
            var baseName = type.OriginalDefinition.ToDisplayString(QualifiedFormatNoGenerics);
            var commas = new string(',', type.Arity - 1);
            return $"typeof({baseName}<{commas}>)";
        }

        private static INamedTypeSymbol? FindFirstMessagePackType(INamespaceSymbol ns, string attrName)
        {
            foreach (var type in ns.GetTypeMembers())
            {
                if (type.DeclaredAccessibility == Accessibility.Public &&
                    type.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == attrName))
                {
                    return type;
                }
            }

            foreach (var childNs in ns.GetNamespaceMembers())
            {
                var result = FindFirstMessagePackType(childNs, attrName);
                if (result != null) return result;
            }

            return null;
        }

        private class AssemblyEntry
        {
            public string AssemblyName { get; set; } = "";
            public string TypeofExpression { get; set; } = "";
        }
    }
}
