using System.Text;
using System.Linq;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Information about a service for MetaProviderBase generation.
    /// </summary>
    public class ServiceForProviderInfo
    {
        public string InterfaceName { get; set; } = "";
        public string InterfaceFullName { get; set; } = "";
        public string StateTypeName { get; set; } = "";
        public string StateTypeFullName { get; set; } = "";
        public string Namespace { get; set; } = "";
        public List<string> SubscriberInterfaces { get; set; } = new();
    }

    /// <summary>
    /// Generates abstract MetaProviderBase classes that provide:
    /// - Direct switch-based routing to services (no reflection/delegates at runtime)
    /// - Abstract methods for service/serializer resolution
    /// - IMetaProvider implementation with async HandleCallAsync
    ///
    /// Example output:
    /// <code>
    /// public abstract class GameMetaProviderBase : IMetaProvider&lt;GameState&gt;
    /// {
    ///     public async Task&lt;HandleCallResult&gt; HandleCallAsync(RpcCall call)
    ///     {
    ///         return call.ServiceName switch
    ///         {
    ///             "ICardGameService" => await DispatchCardGameServiceAsync(call),
    ///             "IProfileService" => await DispatchProfileServiceAsync(call),
    ///             _ => throw new UnknownServiceException(call.ServiceName)
    ///         };
    ///     }
    ///     protected abstract ICardGameService GetCardGameService();
    ///     protected abstract IProfileService GetProfileService();
    ///     protected abstract IMetaSerializer GetSerializer();
    /// }
    /// </code>
    /// </summary>
    public static class MetaProviderBaseGenerator
    {
        /// <summary>
        /// Analyze a [MetaService] interface and extract info for MetaProviderBase generation.
        /// </summary>
        public static ServiceForProviderInfo? Analyze(INamedTypeSymbol symbol)
        {
            // Check for [MetaService] attribute
            var attr = symbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceAttribute");
            if (attr == null) return null;

            // Get state type from attribute
            var stateTypeArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "StateType");
            if (stateTypeArg.Value.Value is not INamedTypeSymbol stateType)
            {
                return null; // No state type, can't generate provider
            }

            var info = new ServiceForProviderInfo
            {
                InterfaceName = symbol.Name,
                InterfaceFullName = symbol.ToDisplayString(),
                StateTypeName = stateType.Name,
                StateTypeFullName = stateType.ToDisplayString(),
                Namespace = symbol.ContainingNamespace.ToDisplayString()
            };

            // Get subscriber interfaces
            var subscriberInterfacesArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "SubscriberInterfaces");
            if (!subscriberInterfacesArg.Value.IsNull && subscriberInterfacesArg.Value.Values.Length > 0)
            {
                foreach (var val in subscriberInterfacesArg.Value.Values)
                {
                    if (val.Value is INamedTypeSymbol subscriberType)
                    {
                        info.SubscriberInterfaces.Add(subscriberType.ToDisplayString());
                    }
                }
            }

            return info;
        }

        /// <summary>
        /// Generate MetaProviderBase classes grouped by state type.
        /// </summary>
        public static string? Generate(string rootNamespace, IEnumerable<ServiceForProviderInfo> services)
        {
            var serviceList = services.ToList();
            if (serviceList.Count == 0) return null;

            // Group services by state type
            var byStateType = serviceList
                .GroupBy(s => s.StateTypeFullName)
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Orleans;");
            sb.AppendLine("using SharedMeta.Core;");
            sb.AppendLine("using SharedMeta.Core.Transport;");
            sb.AppendLine("using SharedMeta.Server;");
            sb.AppendLine("using SharedMeta.Server.Core;");
            sb.AppendLine("using SharedMeta.Server.Core.Grains;");
            sb.AppendLine();

            // Collect all unique namespaces
            var namespaces = serviceList
                .Select(s => s.Namespace)
                .Distinct()
                .OrderBy(n => n);
            foreach (var ns in namespaces)
            {
                sb.AppendLine($"using {ns};");
                sb.AppendLine($"using {ns}.Server;"); // For dispatchers
            }

            sb.AppendLine();
            sb.AppendLine($"namespace {rootNamespace}.Server");
            sb.AppendLine("{");

            // Generate a MetaProviderBase for each state type
            foreach (var group in byStateType)
            {
                var stateTypeFullName = group.Key;
                var stateTypeName = group.First().StateTypeName;
                var servicesForState = group.ToList();

                GenerateProviderBase(sb, stateTypeName, stateTypeFullName, servicesForState);
                sb.AppendLine();
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void GenerateProviderBase(
            StringBuilder sb,
            string stateTypeName,
            string stateTypeFullName,
            List<ServiceForProviderInfo> services)
        {
            var className = $"{stateTypeName}MetaProviderBase";

            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Abstract base class for {stateTypeName} entity providers.");
            sb.AppendLine($"    /// Implements IMetaProvider with direct routing to service dispatchers.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public abstract class {className} : IMetaProvider<{stateTypeFullName}>");
            sb.AppendLine("    {");

            // Protected fields
            sb.AppendLine("        protected IMetaProviderContext? Context { get; private set; }");
            sb.AppendLine($"        protected {stateTypeFullName} State {{ get; private set; }} = null!;");
            sb.AppendLine($"        protected ServerMetaContext<{stateTypeFullName}>? MetaContext {{ get; private set; }}");
            sb.AppendLine();

            // Service instance cache
            sb.AppendLine("        // Cached service instances");
            foreach (var service in services)
            {
                var serviceName = GetBaseName(service.InterfaceName);
                sb.AppendLine($"        private {service.InterfaceName}? _{serviceName.ToLower()}Service;");
            }
            sb.AppendLine();

            // Initialize method
            sb.AppendLine($"        public virtual void Initialize(IMetaProviderContext context, {stateTypeFullName} state)");
            sb.AppendLine("        {");
            sb.AppendLine("            Context = context;");
            sb.AppendLine("            State = state;");
            sb.AppendLine($"            MetaContext = new ServerMetaContext<{stateTypeFullName}>(state, context.Serializer);");
            sb.AppendLine("            MetaContextAccessor.Current = MetaContext;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // HandleCallAsync - main routing method
            GenerateHandleCallAsync(sb, services);
            sb.AppendLine();

            // HandleExternalEventAsync
            GenerateHandleExternalEventAsync(sb, services);
            sb.AppendLine();

            // GetStateBytes
            sb.AppendLine("        public byte[] GetStateBytes()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (Context == null) return Array.Empty<byte>();");
            sb.AppendLine("            return Context.Serializer.Pack(State);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // OnDeactivating
            sb.AppendLine("        public virtual void OnDeactivating()");
            sb.AppendLine("        {");
            foreach (var service in services)
            {
                var serviceName = GetBaseName(service.InterfaceName);
                sb.AppendLine($"            _{serviceName.ToLower()}Service = null;");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // Service dispatch methods
            foreach (var service in services)
            {
                GenerateServiceDispatchMethod(sb, service);
                sb.AppendLine();
            }

            // Abstract methods for service creation
            sb.AppendLine("        // Abstract methods - implement in concrete class");
            foreach (var service in services)
            {
                var baseName = GetBaseName(service.InterfaceName);
                sb.AppendLine($"        /// <summary>Create instance of {service.InterfaceName}.</summary>");
                sb.AppendLine($"        protected abstract {service.InterfaceName} Create{baseName}Service();");
            }
            sb.AppendLine();

            // Service getter methods (cached)
            sb.AppendLine("        // Cached service getters");
            foreach (var service in services)
            {
                var baseName = GetBaseName(service.InterfaceName);
                var fieldName = $"_{baseName.ToLower()}Service";
                sb.AppendLine($"        protected {service.InterfaceName} Get{baseName}Service()");
                sb.AppendLine("        {");
                sb.AppendLine($"            return {fieldName} ??= Create{baseName}Service();");
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
        }

        private static void GenerateHandleCallAsync(StringBuilder sb, List<ServiceForProviderInfo> services)
        {
            sb.AppendLine("        public async Task<HandleCallResult> HandleCallAsync(RpcCall call)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (MetaContext == null || Context == null)");
            sb.AppendLine("            {");
            sb.AppendLine("                return new HandleCallResult");
            sb.AppendLine("                {");
            sb.AppendLine("                    Response = new RpcResponse { Error = \"Provider not initialized\" }");
            sb.AppendLine("                };");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                // Set context");
            sb.AppendLine("                MetaContext.CallerId = call.CallerId;");
            sb.AppendLine("                MetaContextAccessor.Current = MetaContext;");
            sb.AppendLine();
            sb.AppendLine("                // Begin recording");
            sb.AppendLine("                MetaContext.BeginOperation();");
            sb.AppendLine();
            sb.AppendLine("                // Direct service routing");
            sb.AppendLine("                var serviceName = call.ServiceName ?? \"\";");
            sb.AppendLine("                var methodName = call.MethodName ?? \"\";");
            sb.AppendLine("                var methodVersion = call.MethodVersion;  // 0.22.0+: route (Alias, Version) tuple");
            sb.AppendLine("                var payloadBytes = call.Payload ?? Array.Empty<byte>();");
            sb.AppendLine();
            sb.AppendLine("                DispatchResult result = serviceName switch");
            sb.AppendLine("                {");

            foreach (var service in services)
            {
                var baseName = GetBaseName(service.InterfaceName);
                sb.AppendLine($"                    \"{service.InterfaceName}\" => await Dispatch{baseName}Async(methodName, payloadBytes, methodVersion),");
            }

            sb.AppendLine("                    _ => throw new InvalidOperationException($\"Unknown service: {serviceName}\")");
            sb.AppendLine("                };");
            sb.AppendLine();
            sb.AppendLine("                // End recording");
            sb.AppendLine("                var replayBytes = MetaContext.EndOperation();");
            sb.AppendLine();
            sb.AppendLine("                // Build broadcast");
            sb.AppendLine("                var broadcasts = new List<EntityBroadcast>();");
            sb.AppendLine("                broadcasts.Add(new EntityBroadcast");
            sb.AppendLine("                {");
            sb.AppendLine("                    ServiceName = serviceName,");
            sb.AppendLine("                    MethodName = methodName,");
            sb.AppendLine("                    Payload = payloadBytes,");
            sb.AppendLine("                    ReplayPayload = replayBytes,");
            sb.AppendLine("                    ExcludePlayerId = call.CallerId");
            sb.AppendLine("                });");
            sb.AppendLine();
            sb.AppendLine("                // Execute triggers if any");
            sb.AppendLine("                if (result.TriggersToExecute != null)");
            sb.AppendLine("                {");
            sb.AppendLine("                    await ExecuteTriggersAsync(serviceName, result.TriggersToExecute, broadcasts);");
            sb.AppendLine("                }");
            sb.AppendLine();
            sb.AppendLine("                return new HandleCallResult");
            sb.AppendLine("                {");
            sb.AppendLine("                    Response = new RpcResponse");
            sb.AppendLine("                    {");
            sb.AppendLine("                        ResultBytes = result.ResultBytes,");
            sb.AppendLine("                        ReplayPayload = replayBytes");
            sb.AppendLine("                    },");
            sb.AppendLine("                    Broadcasts = broadcasts");
            sb.AppendLine("                };");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine("                Console.Error.WriteLine($\"[MetaProviderBase] Error handling call {call.ServiceName}.{call.MethodName}: {ex.Message}\");");
            sb.AppendLine("                return new HandleCallResult");
            sb.AppendLine("                {");
            sb.AppendLine("                    Response = new RpcResponse { Error = ex.Message }");
            sb.AppendLine("                };");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // ExecuteTriggersAsync
            sb.AppendLine("        protected virtual Task ExecuteTriggersAsync(string serviceName, List<string> triggers, List<EntityBroadcast> broadcasts)");
            sb.AppendLine("        {");
            sb.AppendLine("            // Override in concrete class to execute triggers");
            sb.AppendLine("            return Task.CompletedTask;");
            sb.AppendLine("        }");
        }

        private static void GenerateHandleExternalEventAsync(StringBuilder sb, List<ServiceForProviderInfo> services)
        {
            // Collect all subscriber interfaces across services
            var allSubscribers = services
                .SelectMany(s => s.SubscriberInterfaces.Select(sub => new { Service = s, Subscriber = sub }))
                .ToList();

            sb.AppendLine("        public async Task<HandleEventResult> HandleExternalEventAsync(");
            sb.AppendLine("            string subscriberInterface,");
            sb.AppendLine("            string methodName,");
            sb.AppendLine("            byte[] eventData,");
            sb.AppendLine("            string? callerId = null)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (MetaContext == null || Context == null)");
            sb.AppendLine("            {");
            sb.AppendLine("                return new HandleEventResult();");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                // Set context");
            sb.AppendLine("                MetaContext.CallerId = callerId;");
            sb.AppendLine("                MetaContextAccessor.Current = MetaContext;");
            sb.AppendLine();
            sb.AppendLine("                // Begin recording");
            sb.AppendLine("                MetaContext.BeginOperation();");
            sb.AppendLine();

            if (allSubscribers.Count > 0)
            {
                sb.AppendLine("                // Route to subscriber dispatcher");
                sb.AppendLine("                switch (subscriberInterface)");
                sb.AppendLine("                {");
                foreach (var sub in allSubscribers)
                {
                    var baseName = GetBaseName(sub.Service.InterfaceName);
                    var subscriberName = sub.Subscriber.Split('.').Last();
                    sb.AppendLine($"                    case \"{subscriberName}\":");
                    sb.AppendLine($"                    case \"{sub.Subscriber}\":");
                    sb.AppendLine($"                        {baseName}SubscriberDispatcher.Dispatch(Get{baseName}Service(), subscriberInterface, methodName, eventData, Context.Serializer);");
                    sb.AppendLine("                        break;");
                }
                sb.AppendLine("                    default:");
                sb.AppendLine("                        Console.Error.WriteLine($\"[MetaProviderBase] Unknown subscriber interface: {subscriberInterface}\");");
                sb.AppendLine("                        break;");
                sb.AppendLine("                }");
            }
            else
            {
                sb.AppendLine("                // No subscriber interfaces registered");
                sb.AppendLine("                Console.Error.WriteLine($\"[MetaProviderBase] Unknown subscriber interface: {subscriberInterface}\");");
            }

            sb.AppendLine();
            sb.AppendLine("                // End recording");
            sb.AppendLine("                var replayBytes = MetaContext.EndOperation();");
            sb.AppendLine();
            sb.AppendLine("                // Build broadcast");
            sb.AppendLine("                var broadcasts = new List<EntityBroadcast>();");
            sb.AppendLine("                broadcasts.Add(new EntityBroadcast");
            sb.AppendLine("                {");
            sb.AppendLine("                    ServiceName = subscriberInterface,");
            sb.AppendLine("                    MethodName = methodName,");
            sb.AppendLine("                    Payload = eventData,");
            sb.AppendLine("                    ReplayPayload = replayBytes");
            sb.AppendLine("                });");
            sb.AppendLine();
            sb.AppendLine("                return new HandleEventResult { Broadcasts = broadcasts };");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception ex)");
            sb.AppendLine("            {");
            sb.AppendLine("                Console.Error.WriteLine($\"[MetaProviderBase] Error handling external event {subscriberInterface}.{methodName}: {ex.Message}\");");
            sb.AppendLine("                return new HandleEventResult();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        private static void GenerateServiceDispatchMethod(StringBuilder sb, ServiceForProviderInfo service)
        {
            var baseName = GetBaseName(service.InterfaceName);

            sb.AppendLine($"        private async Task<DispatchResult> Dispatch{baseName}Async(string methodName, byte[] payloadBytes, int methodVersion)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var service = Get{baseName}Service();");
            sb.AppendLine($"            return await {service.InterfaceName}Dispatcher.Dispatch(service, methodName, payloadBytes, methodVersion, Context!.Serializer);");
            sb.AppendLine("        }");
        }

        private static string GetBaseName(string interfaceName)
        {
            // Remove leading 'I' for method names
            if (interfaceName.StartsWith("I") && interfaceName.Length > 1 && char.IsUpper(interfaceName[1]))
            {
                return interfaceName.Substring(1);
            }
            return interfaceName;
        }
    }
}
