using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Emits <c>I{Contract}ServerApi</c> — the awaitable mirror of a
    /// <c>[MetaServiceContract]</c> interface — into the contract's own assembly.
    /// </summary>
    /// <remarks>
    /// The mirror exists so code that cannot reference the game can still make a typed call into
    /// a player's entity: a framework grain names the contract, and whichever
    /// <c>{Service}ServerApi</c> belongs to the service inheriting it satisfies the mirror. That
    /// only works if the mirror is compiled beside the contract, which is why this runs off the
    /// contract's declaration rather than off the service's.
    /// <para>
    /// Every member becomes <c>Task</c> / <c>Task&lt;T&gt;</c> with an <c>Async</c> suffix,
    /// matching what <c>ServerApiGenerator</c> already emits — a server-originated call is always
    /// a grain hop, so there is no synchronous form to mirror.
    /// </para>
    /// </remarks>
    public static class MetaServiceContractApiGenerator
    {
        public static string? Generate(INamedTypeSymbol contract)
        {
            var methods = contract.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(m => m.MethodKind == MethodKind.Ordinary)
                .ToList();
            if (methods.Count == 0) return null;

            var apiName = ApiNameFor(contract);
            var ns = contract.ContainingNamespace.ToDisplayString();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// Awaitable server-side view of <see cref=\"{contract.Name}\"/>. Inject it and call any");
            sb.AppendLine("    /// entity through it — the entity id is an argument, not a binding, so one instance");
            sb.AppendLine("    /// serves every target. Registered by the generated meta configuration; resolve as");
            sb.AppendLine("    /// optional, since a game need not inherit the contract at all.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    /// <remarks>");
            sb.AppendLine("    /// Calls run under the entity owner's app version. Pin a different one by going through");
            sb.AppendLine("    /// the service's own <c>{Service}ServerApi</c> instead.");
            sb.AppendLine("    /// </remarks>");
            sb.AppendLine($"    public interface {apiName}");
            sb.AppendLine("    {");

            foreach (var method in methods)
            {
                var declared = method.Parameters.Select(p => $"{p.Type.ToDisplayString()} @{p.Name}");
                var parameters = string.Join(", ", new[] { "string entityId" }.Concat(declared));
                var returnType = MirrorReturnType(method.ReturnType);
                var name = MirrorMethodName(method);
                sb.AppendLine($"        /// <inheritdoc cref=\"{contract.Name}.{method.Name}\"/>");
                sb.AppendLine($"        /// <param name=\"entityId\">Entity to dispatch on.</param>");
                sb.AppendLine($"        {returnType} {name}({parameters});");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>
        /// Name the mirror after the contract without doubling the interface prefix. Shared with
        /// ServerApiGenerator: both sides must agree or the generated class implements nothing.
        /// </summary>
        public static string ApiNameFor(INamedTypeSymbol contract)
        {
            var name = contract.Name;
            var trimmed = name.Length > 1 && name[0] == 'I' && char.IsUpper(name[1]) ? name.Substring(1) : name;
            return "I" + trimmed + "ServerApi";
        }

        /// <summary>Fully-qualified mirror name, for use in a base list.</summary>
        public static string ApiFqnFor(INamedTypeSymbol contract) =>
            "global::" + contract.ContainingNamespace.ToDisplayString() + "." + ApiNameFor(contract);

        /// <summary>Mirror member name for a contract member.</summary>
        public static string MirrorMethodName(IMethodSymbol method) =>
            method.Name.EndsWith("Async") ? method.Name : method.Name + "Async";

        /// <summary>Ordinary members of a contract, in declaration order.</summary>
        public static List<IMethodSymbol> MembersOf(INamedTypeSymbol contract) =>
            contract.GetMembers().OfType<IMethodSymbol>()
                .Where(m => m.MethodKind == MethodKind.Ordinary)
                .ToList();

        /// <summary>The <c>[MetaServiceContract]</c> interfaces a service inherits.</summary>
        public static List<INamedTypeSymbol> ContractsOf(INamedTypeSymbol service) =>
            service.AllInterfaces
                .Where(i => i.GetAttributes().Any(a =>
                    a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceContractAttribute"))
                .ToList();

        public static string MirrorReturnType(ITypeSymbol returnType)
        {
            var text = returnType.ToDisplayString();
            if (text is "void" or "System.Threading.Tasks.Task") return "Task";

            // A contract member may already be declared awaitable; mirror its payload, not its shell.
            if (returnType is INamedTypeSymbol { IsGenericType: true } named
                && named.ConstructedFrom.ToDisplayString() is "System.Threading.Tasks.Task<T>"
                    or "System.Threading.Tasks.ValueTask<T>")
            {
                return $"Task<{named.TypeArguments[0].ToDisplayString()}>";
            }
            if (text == "System.Threading.Tasks.ValueTask") return "Task";

            return $"Task<{text}>";
        }
    }
}
