using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Generates a _PatchTracked copy of a [MetaServiceImpl] class. The copy is identical to the
    /// original but routes State access through PatchWrapper, so a normal <c>State.X = …</c> write
    /// transparently records a field-level mutation.
    ///
    /// Original: protected GameState State => Context.State;
    /// Copy:     protected GameStatePatchWrapper State => PatchState;
    ///
    /// Emitted when the service is force-patch-able (version-fallback band or config boundary) and
    /// opted in, OR when [MetaServiceImpl(DeepDesync = true)] requests it — see PatchTrackingPolicy.
    /// The server dispatcher routes to this copy whenever MetaContext.PatchWrapper != null (force
    /// patch, ServerPatch, or deep desync); otherwise it uses the original (zero overhead).
    /// </summary>
    public static class PatchTrackedClassGenerator
    {
        public static string? Generate(ClassDeclarationSyntax node, INamedTypeSymbol symbol, Compilation compilation)
        {
            var attr = symbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceImplAttribute");
            if (attr == null) return null;

            // Get state type
            if (attr.ConstructorArguments.Length < 2) return null;
            var stateTypeSymbol = attr.ConstructorArguments[1].Value as INamedTypeSymbol;
            if (stateTypeSymbol == null) return null;
            var stateTypeName = stateTypeSymbol.ToDisplayString();

            // Get the service interface from the attribute
            var serviceInterfaceSymbol = attr.ConstructorArguments[0].Value as INamedTypeSymbol;
            var serviceInterfaceName = serviceInterfaceSymbol?.ToDisplayString() ?? "";

            // 0.24.2+ Decoupled from DeepDesync, evaluated at STATE level: emit the copy for every
            // service on a state if any service on that state needs patch tracking (force-patch-able
            // or DeepDesync). This covers siblings — a force-patched call fanning out to a sibling
            // service on the same state must run the sibling's tracked copy too, or its mutations
            // bypass the wrapper and go missing from the diff.
            var deepDesyncArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "DeepDesync");
            bool deepDesync = !deepDesyncArg.Value.IsNull && deepDesyncArg.Value.Value is true;
            bool shouldGenerate = deepDesync || PatchTrackingPolicy.StateNeedsPatchCopy(stateTypeSymbol);
            if (!shouldGenerate) return null;

            var namespaceName = symbol.ContainingNamespace.ToDisplayString();
            var originalClassName = symbol.Name;
            var patchTrackedClassName = originalClassName + "_PatchTracked";

            // Collect all method bodies from the syntax tree
            var methods = node.Members.OfType<MethodDeclarationSyntax>().ToList();
            var fields = node.Members.OfType<FieldDeclarationSyntax>().ToList();
            var properties = node.Members.OfType<PropertyDeclarationSyntax>().ToList();

            // Collect using directives from the source file
            var root = node.SyntaxTree.GetRoot();
            var usings = root.DescendantNodes().OfType<UsingDirectiveSyntax>()
                .Select(u => u.ToFullString().Trim())
                .Distinct()
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Deep desync PatchTracked copy of " + originalClassName);
            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable CS0108 // hides inherited member");

            // Emit all usings from original file + required ones (deduplicated)
            var allUsings = new HashSet<string>(usings);
            allUsings.Add("using SharedMeta.Core;");
            allUsings.Add("using SharedMeta.Core.Patch;");
            allUsings.Add("using SharedMeta.Core.Random;");
            foreach (var u in allUsings)
                sb.AppendLine(u);
            sb.AppendLine();

            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");

            // Class declaration — implements same interface as original
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// PatchTracked copy of {originalClassName}.");
            sb.AppendLine($"    /// All State access routes through PatchWrapper for mutation tracking.");
            sb.AppendLine($"    /// </summary>");
            // Implement interface — needed for dispatcher compatibility
            if (!string.IsNullOrEmpty(serviceInterfaceName))
                sb.AppendLine($"    public class {patchTrackedClassName} : {serviceInterfaceName}");
            else
                sb.AppendLine($"    public class {patchTrackedClassName}");
            sb.AppendLine("    {");

            // 0.20.0: Context is a typed instance property; user-code hot path no longer
            // needs AsyncLocal. Provider's lazy Get{Name}PatchTracked() sets it on server,
            // client-side ApiClient SetContext() before invocation, sibling getters on
            // transient impls. AsyncLocal fallback retained for framework-internal generated
            // paths (foreign-service entity replay, signal/trigger/subscriber dispatchers,
            // ServerPatch appliers) — appropriate ambient-execution-context primitive there.
            sb.AppendLine($"        private MetaContext<{stateTypeName}>? _context;");
            sb.AppendLine($"        public MetaContext<{stateTypeName}> Context");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            get => _context ?? MetaContextAccessor.Get<{stateTypeName}>();");
            sb.AppendLine($"            set => _context = value;");
            sb.AppendLine($"        }}");
            sb.AppendLine($"        protected {stateTypeName}PatchWrapper State");
            sb.AppendLine("        {");
            sb.AppendLine("            get");
            sb.AppendLine("            {");
            sb.AppendLine($"                if (Context.PatchWrapper is {stateTypeName}PatchWrapper existing)");
            sb.AppendLine("                    return existing;");
            sb.AppendLine($"                var wrapper = new {stateTypeName}PatchWrapper(");
            sb.AppendLine("                    Context.State, null, Context.MetaSerializer);");
            sb.AppendLine("                Context.PatchWrapper = wrapper;");
            sb.AppendLine("                return wrapper;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Config accessor — same as original
            if (serviceInterfaceSymbol != null)
            {
                var metaServiceAttr = serviceInterfaceSymbol.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceAttribute");
                if (metaServiceAttr != null)
                {
                    string? configTypeName = null;
                    var configTypeArg = metaServiceAttr.NamedArguments.FirstOrDefault(a => a.Key == "ConfigType");
                    if (!configTypeArg.Value.IsNull && configTypeArg.Value.Value is INamedTypeSymbol configTypeSymbol)
                        configTypeName = configTypeSymbol.ToDisplayString();
                    else
                    {
                        var defaultConfigArg = metaServiceAttr.NamedArguments.FirstOrDefault(a => a.Key == "DefaultConfig");
                        if (!defaultConfigArg.Value.IsNull && defaultConfigArg.Value.Value is true)
                            configTypeName = FindDefaultConfigType(compilation);
                    }
                    if (configTypeName != null)
                    {
                        sb.AppendLine($"        protected {configTypeName} Config => ({configTypeName})Context.Config!;");
                        sb.AppendLine();
                    }
                }
            }

            // Named random accessors — must mirror ContextInjectionGenerator so method bodies copy cleanly
            var namedRandoms = stateTypeSymbol.GetAttributes()
                .Where(a => a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.NamedRandomAttribute")
                .Select(a => a.ConstructorArguments.Length > 0 ? a.ConstructorArguments[0].Value as string : null)
                .Where(n => !string.IsNullOrEmpty(n))
                .ToList();
            for (int i = 0; i < namedRandoms.Count; i++)
            {
                sb.AppendLine($"        protected IMetaRandom {namedRandoms[i]}Random => Context.NamedRandoms![{i}];");
            }
            if (namedRandoms.Count > 0) sb.AppendLine();

            // Copy fields (private backing fields, etc.)
            foreach (var field in fields)
            {
                sb.AppendLine("        " + field.ToFullString().Trim());
            }
            if (fields.Count > 0) sb.AppendLine();

            // Copy properties — rewrite any expression-bodied property that returns the State
            // accessor to return the wrapper type. Covers both the canonical
            // `protected GameState State => Context.State;` and user aliases like
            // `private ClanState S => State;`. Without this the copy fails to compile: the body
            // `State` resolves to the wrapper but the declared type is the concrete state. Routing
            // the alias through the wrapper also keeps `S.Field = …` writes tracked.
            foreach (var prop in properties)
            {
                var propName = prop.Identifier.Text;
                var exprBody = prop.ExpressionBody?.Expression.ToString().Trim();
                bool returnsStateAccessor =
                    exprBody == "State" || exprBody == "state" || exprBody == "Context.State";
                if (returnsStateAccessor)
                {
                    var modifiers = prop.Modifiers.ToString();
                    var mod = string.IsNullOrEmpty(modifiers) ? "private" : modifiers;
                    sb.AppendLine($"        {mod} {stateTypeName}PatchWrapper {propName} => State;");
                    continue;
                }
                sb.AppendLine("        " + prop.ToFullString().Trim());
            }

            // Generate entity service getters (cross-entity call proxies)
            // These are generated in Context.g.cs for the original class; we need them here too
            if (attr.ConstructorArguments.Length > 2)
            {
                var depsArg = attr.ConstructorArguments[2];
                if (!depsArg.IsNull && depsArg.Values.Length > 0)
                {
                    foreach (var dep in depsArg.Values)
                    {
                        if (dep.Value is INamedTypeSymbol depSymbol)
                        {
                            GenerateDependencyGetter(sb, depSymbol);

                            // Sibling = an entity service hosted on the SAME state. The original
                            // impl gets a Get{Iface}SiblingAsync() accessor from ContextInjection;
                            // the copied method bodies may call it, so emit the same accessor here
                            // (the copy is a separate class and doesn't inherit the original's
                            // generated members). Reuses ContextInjectionGenerator so both stay
                            // byte-identical (incl. the #if SHAREDMETA_SERVER / client branches).
                            var depState = ContextInjectionGenerator.ReadDepStateType(depSymbol);
                            if (depState != null && depState == stateTypeName)
                            {
                                ContextInjectionGenerator.GenerateSiblingAsyncGetter(
                                    sb, depSymbol, stateTypeName,
                                    ContextInjectionGenerator.ReadDepConfigType(depSymbol),
                                    ContextInjectionGenerator.ReadDepServiceConfigTypes(depSymbol));
                            }
                        }
                    }
                }
            }

            // Build set of methods to skip (server-only, MetaInit, IsAuthorized)
            var skipMethods = new HashSet<string> { "IsAuthorized" };
            if (serviceInterfaceSymbol != null)
            {
                foreach (var member in serviceInterfaceSymbol.GetMembers().OfType<IMethodSymbol>())
                {
                    // Check for [MetaInit] on implementation
                    // Check for GenerateClientApi = false on interface method
                    var metaMethodAttr = member.GetAttributes().FirstOrDefault(a =>
                        a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaMethodAttribute");
                    if (metaMethodAttr != null)
                    {
                        var genApiArg = metaMethodAttr.NamedArguments.FirstOrDefault(a => a.Key == "GenerateClientApi");
                        if (!genApiArg.Value.IsNull && genApiArg.Value.Value is false)
                            skipMethods.Add(member.Name);
                    }
                }
            }

            // Copy method bodies — skip server-only methods that never run on client
            var skippedMethods = new HashSet<string>();
            foreach (var method in methods)
            {
                var methodName = method.Identifier.Text;

                // Check attributes on the implementation
                var methodAttrs = method.AttributeLists.SelectMany(a => a.Attributes).ToList();

                // Skip [MetaInit] — initialization, not replayed on client
                if (methodAttrs.Any(a => a.Name.ToString().Contains("MetaInit")))
                {
                    skippedMethods.Add(methodName);
                    continue;
                }

                // Skip methods marked as server-only in the interface
                if (skipMethods.Contains(methodName))
                {
                    skippedMethods.Add(methodName);
                    continue;
                }

                sb.AppendLine();
                // Strip attributes from the copy
                var methodWithoutAttrs = method.WithAttributeLists(SyntaxFactory.List<AttributeListSyntax>());
                sb.AppendLine("        " + methodWithoutAttrs.ToFullString().Trim());
            }

            // Server-only and MetaInit methods: copy verbatim (they run on server, not replayed on client)
            // These need to exist for interface compliance and cross-entity calls
            foreach (var method in methods)
            {
                var methodName = method.Identifier.Text;
                if (!skippedMethods.Contains(methodName)) continue;

                sb.AppendLine();
                var methodWithoutAttrs = method.WithAttributeLists(SyntaxFactory.List<AttributeListSyntax>());
                sb.AppendLine("        " + methodWithoutAttrs.ToFullString().Trim());
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void GenerateDependencyGetter(StringBuilder sb, INamedTypeSymbol depSymbol)
        {
            var interfaceName = depSymbol.Name;
            var baseName = interfaceName;
            if (baseName.StartsWith("I") && baseName.Length > 1 && char.IsUpper(baseName[1]))
                baseName = baseName.Substring(1);

            // Check if entity service (IMetaService) or server service
            bool isEntityService = depSymbol.AllInterfaces.Any(i => i.ToDisplayString() == "SharedMeta.Core.IMetaService")
                || depSymbol.Interfaces.Any(i => i.ToDisplayString() == "SharedMeta.Core.IMetaService");

            var ns = depSymbol.ContainingNamespace.ToDisplayString();
            var entityCallerInterface = $"{interfaceName}EntityCaller";

            if (isEntityService)
            {
                // Same pattern as ContextInjectionGenerator.GenerateEntityServiceGetter
                sb.AppendLine();
                sb.AppendLine($"        protected {entityCallerInterface} Get{interfaceName}(string entityId)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (Context.IsServer)");
                sb.AppendLine($"                return new {baseName}EntityRecorder(entityId, (IServerRecordContext)Context);");
                sb.AppendLine("            else if (Context.CrossEntityResolver != null)");
                sb.AppendLine($"                return new {baseName}LocalEntityCaller(entityId, Context.CrossEntityResolver);");
                sb.AppendLine("            else");
                sb.AppendLine($"                return new {baseName}EntityReplayer((IClientReplayContext)Context);");
                sb.AppendLine("        }");
            }
            else
            {
                sb.AppendLine();
                sb.AppendLine($"        protected {depSymbol.ToDisplayString()} Get{interfaceName}()");
                sb.AppendLine("        {");
                sb.AppendLine($"            return Context.GetService<{depSymbol.ToDisplayString()}>();");
                sb.AppendLine("        }");
            }
        }

        private static string? FindDefaultConfigType(Compilation compilation)
        {
            // Walk current compilation AND referenced assemblies. Prior to 0.20.2 this only
            // scanned compilation.SyntaxTrees, so a config class declared in a referenced
            // project was invisible — see the matching fix in ServiceRegistrationGenerator.
            var result = FindDefaultConfigTypeInNamespace(compilation.Assembly.GlobalNamespace);
            if (result != null) return result;

            foreach (var reference in compilation.References)
            {
                if (compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol asm) continue;
                var name = asm.Name;
                if (name.StartsWith("System") || name.StartsWith("Microsoft") ||
                    name.StartsWith("netstandard") || name == "mscorlib" ||
                    name.StartsWith("Orleans") || name == "MemoryPack" ||
                    name == "MemoryPack.Core" || name == "MessagePack" ||
                    name == "MessagePack.Annotations")
                    continue;

                result = FindDefaultConfigTypeInNamespace(asm.GlobalNamespace);
                if (result != null) return result;
            }
            return null;
        }

        private static string? FindDefaultConfigTypeInNamespace(INamespaceSymbol ns)
        {
            foreach (var type in ns.GetTypeMembers())
            {
                var attr = type.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaConfigAttribute");
                if (attr != null)
                {
                    var defaultArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "Default");
                    if (!defaultArg.Value.IsNull && defaultArg.Value.Value is true)
                        return type.ToDisplayString();
                }
            }
            foreach (var childNs in ns.GetNamespaceMembers())
            {
                var result = FindDefaultConfigTypeInNamespace(childNs);
                if (result != null) return result;
            }
            return null;
        }
    }
}
