using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Generates <c>{State}PatchSchema.g.cs</c> alongside the PatchWrapper for every ISharedState.
    /// The schema lets <c>PatchTextRenderer</c> turn raw PatchNode trees into human-readable JSON
    /// (field names + typed decoded values) — used only by diagnostic / desync-reporting paths.
    ///
    /// Reuses the analysis output from <see cref="StatePatchGenerator.Analyze"/>.
    /// </summary>
    public static class PatchSchemaGenerator
    {
        public static string? Generate(PatchGenerationInfo info)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using SharedMeta.Core;");
            sb.AppendLine("using SharedMeta.Core.Patch;");
            sb.AppendLine();

            var targetNs = info.RootType.Namespace;
            var extraNamespaces = info.SubTypes
                .Select(s => s.Namespace)
                .Where(ns => ns != targetNs)
                .Distinct()
                .OrderBy(ns => ns);
            foreach (var ns in extraNamespaces)
                sb.AppendLine($"using {ns};");

            sb.AppendLine($"namespace {targetNs}");
            sb.AppendLine("{");

            // Root schema (sub-schemas are nested inside as separate classes)
            EmitSchemaClass(sb, info.RootType, info.SubTypes, "    ");

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void EmitSchemaClass(
            StringBuilder sb,
            PatchTypeInfo typeInfo,
            List<PatchTypeInfo> subTypes,
            string indent)
        {
            var className = typeInfo.TypeName + "PatchSchema";
            var ii = indent + "    ";

            sb.AppendLine($"{indent}/// <summary>");
            sb.AppendLine($"{indent}/// PatchNode field schema for {typeInfo.TypeName}.");
            sb.AppendLine($"{indent}/// Used by <see cref=\"SharedMeta.Core.Patch.PatchTextRenderer\"/> for diagnostic output.");
            sb.AppendLine($"{indent}/// </summary>");
            sb.AppendLine($"{indent}public sealed class {className} : SharedMeta.Core.Patch.IPatchSchema");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{ii}public static readonly {className} Instance = new();");
            sb.AppendLine();

            // GetFieldName
            sb.AppendLine($"{ii}public string GetFieldName(int fieldId) => fieldId switch");
            sb.AppendLine($"{ii}{{");
            foreach (var f in typeInfo.Fields)
                sb.AppendLine($"{ii}    {f.FieldId} => \"{f.Name}\",");
            sb.AppendLine($"{ii}    _ => \"#\" + fieldId");
            sb.AppendLine($"{ii}}};");
            sb.AppendLine();

            // DecodeLeaf
            sb.AppendLine($"{ii}public object? DecodeLeaf(int fieldId, byte[] bytes, IMetaSerializer serializer) => fieldId switch");
            sb.AppendLine($"{ii}{{");
            foreach (var f in typeInfo.Fields)
            {
                var decodeType = ResolveDecodeType(f);
                if (decodeType != null)
                    sb.AppendLine($"{ii}    {f.FieldId} => serializer.Unpack<{decodeType}>(bytes),");
            }
            sb.AppendLine($"{ii}    _ => bytes");
            sb.AppendLine($"{ii}}};");
            sb.AppendLine();

            // GetNestedSchema
            sb.AppendLine($"{ii}public IPatchSchema? GetNestedSchema(int fieldId) => fieldId switch");
            sb.AppendLine($"{ii}{{");
            foreach (var f in typeInfo.Fields)
            {
                if (f.Kind == PatchFieldKind.SubWrappable && f.SubTypeName != null)
                {
                    sb.AppendLine($"{ii}    {f.FieldId} => {f.SubTypeName}PatchSchema.Instance,");
                }
            }
            sb.AppendLine($"{ii}    _ => null");
            sb.AppendLine($"{ii}}};");

            sb.AppendLine($"{indent}}}");

            // Emit a sibling schema class for every distinct sub-type referenced by this type
            var generated = new HashSet<string>();
            foreach (var f in typeInfo.Fields.Where(f => f.Kind == PatchFieldKind.SubWrappable))
            {
                if (f.SubTypeFullName == null || generated.Contains(f.SubTypeFullName)) continue;
                generated.Add(f.SubTypeFullName);

                var sub = subTypes.FirstOrDefault(s => s.TypeFullName == f.SubTypeFullName);
                if (sub != null)
                {
                    sb.AppendLine();
                    EmitSchemaClass(sb, sub, subTypes, indent);
                }
            }
        }

        /// <summary>
        /// Resolve the type used for terminal-leaf deserialization. For collection fields,
        /// the whole collection is replaced as a single terminal blob, so we decode the base type.
        /// </summary>
        private static string? ResolveDecodeType(PatchFieldInfo f)
        {
            switch (f.Kind)
            {
                case PatchFieldKind.Terminal:
                case PatchFieldKind.SubWrappable:
                    // SubWrappable terminal = entire sub-state replaced; decode the full type
                    return f.TypeFullName;
                case PatchFieldKind.Collection:
                    return f.CollectionBaseType;
                default:
                    return null;
            }
        }
    }
}
