using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using SharedMeta.Generator.Utilities;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Generates QueryApi classes for services with [MetaMethod(Query = true)] methods.
    /// Produces two classes:
    /// - {Service}QueryApi — factory, created once with IConnection + IMetaSerializer
    /// - {Service}EntityQueryApi — per-entity proxy with typed query methods
    /// </summary>
    public static class QueryClientGenerator
    {
        public static SourceText? Generate(InterfaceDeclarationSyntax node, INamedTypeSymbol symbol, Compilation compilation)
        {
            var interfaceName = symbol.Name;
            var namespaceName = symbol.ContainingNamespace.ToDisplayString();

            // Find StateType from MetaService attribute
            var metaServiceAttr = symbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceAttribute");
            if (metaServiceAttr == null) return null;

            // Collect query methods
            var queryMethods = new List<QueryMethodInfo>();
            foreach (var member in symbol.GetMembers().OfType<IMethodSymbol>())
            {
                if (member.MethodKind != MethodKind.Ordinary) continue;

                var metaMethodAttr = member.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaMethodAttribute");
                if (metaMethodAttr == null) continue;

                // Accept both legacy [MetaMethod(Query = true)] and canonical [MetaMethod(Mode = ExecutionMode.Query)].
                // Mode is stored as the enum's integer value: Query = 6 (see ExecutionMode declaration).
                var queryArg = metaMethodAttr.NamedArguments.FirstOrDefault(a => a.Key == "Query");
                bool legacyQuery = !queryArg.Value.IsNull && queryArg.Value.Value is true;
                var modeArg = metaMethodAttr.NamedArguments.FirstOrDefault(a => a.Key == "Mode");
                bool modeIsQuery = !modeArg.Value.IsNull && modeArg.Value.Value is int m && m == 6;
                if (!legacyQuery && !modeIsQuery) continue;

                var aliasArg = metaMethodAttr.NamedArguments.FirstOrDefault(a => a.Key == "Alias");
                var methodAlias = (!aliasArg.Value.IsNull && aliasArg.Value.Value is string alias && !string.IsNullOrEmpty(alias))
                    ? alias
                    : member.Name;

                // 0.22.0: [MetaMethod(Version = N)] stamped onto QueryCallRequest.MethodVersion
                // for (MethodName, Version) dispatch on the server query dispatcher.
                var versionArg = metaMethodAttr.NamedArguments.FirstOrDefault(a => a.Key == "Version");
                int methodVersion = (!versionArg.Value.IsNull && versionArg.Value.Value is int vv) ? vv : 0;

                queryMethods.Add(new QueryMethodInfo
                {
                    Name = member.Name,
                    Alias = methodAlias,
                    Version = methodVersion,
                    ReturnType = member.ReturnType,
                    Parameters = member.Parameters
                });
            }

            if (queryMethods.Count == 0) return null;

            var baseName = interfaceName.StartsWith("I") && interfaceName.Length > 1 && char.IsUpper(interfaceName[1])
                ? interfaceName.Substring(1)
                : interfaceName;

            var serializer = SerializerDetector.Detect(compilation);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using SharedMeta.Core;");
            sb.AppendLine("using SharedMeta.Core.Transport;");
            if (serializer == DetectedSerializer.MemoryPack)
            {
                sb.AppendLine("using MemoryPack;");
            }
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}.Client");
            sb.AppendLine("{");

            // --- QueryApi class (factory) ---
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Query factory for {interfaceName}. Create once, call EntityApi(entityId) per target.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public class {baseName}QueryApi");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly IConnection _connection;");
            sb.AppendLine("        private readonly IMetaSerializer _serializer;");
            sb.AppendLine();
            sb.AppendLine($"        public {baseName}QueryApi(IConnection connection, IMetaSerializer serializer)");
            sb.AppendLine("        {");
            sb.AppendLine("            _connection = connection;");
            sb.AppendLine("            _serializer = serializer;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        /// <summary>Get a query proxy bound to a specific entity.</summary>");
            sb.AppendLine($"        public {baseName}EntityQueryApi EntityApi(string entityId)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return new {baseName}EntityQueryApi(_connection, _serializer, entityId);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // --- EntityQueryApi class (per-entity proxy) ---
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Per-entity query proxy for {interfaceName}. Read-only methods, no subscription required.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public class {baseName}EntityQueryApi");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly IConnection _connection;");
            sb.AppendLine("        private readonly IMetaSerializer _serializer;");
            sb.AppendLine("        private readonly string _entityId;");
            sb.AppendLine($"        private const string ServiceName = \"{interfaceName}\";");
            sb.AppendLine();
            sb.AppendLine($"        public {baseName}EntityQueryApi(IConnection connection, IMetaSerializer serializer, string entityId)");
            sb.AppendLine("        {");
            sb.AppendLine("            _connection = connection;");
            sb.AppendLine("            _serializer = serializer;");
            sb.AppendLine("            _entityId = entityId;");
            sb.AppendLine("        }");

            foreach (var method in queryMethods)
            {
                sb.AppendLine();
                GenerateQueryMethod(sb, method, namespaceName, interfaceName, serializer, compilation);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return SourceText.From(sb.ToString(), Encoding.UTF8);
        }

        private static void GenerateQueryMethod(StringBuilder sb, QueryMethodInfo method,
            string namespaceName, string interfaceName, DetectedSerializer serializer, Compilation compilation)
        {
            // Extract inner type from Task<T>
            var returnTypeStr = method.ReturnType.ToDisplayString();
            bool isVoidReturn = returnTypeStr == "System.Threading.Tasks.Task" || returnTypeStr == "void";
            string innerType;
            if (returnTypeStr.StartsWith("System.Threading.Tasks.Task<"))
                innerType = returnTypeStr.Substring("System.Threading.Tasks.Task<".Length, returnTypeStr.Length - "System.Threading.Tasks.Task<".Length - 1);
            else if (returnTypeStr.StartsWith("Task<"))
                innerType = returnTypeStr.Substring("Task<".Length, returnTypeStr.Length - "Task<".Length - 1);
            else
                innerType = returnTypeStr;

            var asyncReturnType = isVoidReturn ? "Task" : $"Task<{innerType}>";

            // Build parameter list (original method params)
            var paramList = string.Join(", ", method.Parameters.Select(p =>
                $"{p.Type.ToDisplayString()} {p.Name}"));

            sb.AppendLine($"        [global::SharedMeta.Core.GeneratedFromMetaMethod(typeof(global::{namespaceName}.{interfaceName}), \"{method.Name}\")]");
            sb.AppendLine($"        public async {asyncReturnType} {method.Name}Async({paramList})");
            sb.AppendLine("        {");

            // Query arguments go through the same dispatcher as any other RPC, so they must be
            // framed the way that dispatcher reads them — which is serializer-dependent. Under
            // MemoryPack it deserializes positionally from raw bytes; the length-prefixed writer
            // would leave it reading a length header out of member data.
            var transforms = TransformerAnalysis.Analyze(method.Parameters, compilation);
            foreach (var t in transforms.Where(t => t.Transformed))
                sb.AppendLine($"            var {t.WireLocal} = {TransformerAnalysis.BoxExpr(t, t.Name, TransformerAnalysis.AmbientStateExpr(t))};");
            string Arg(ParameterTransform t) => t.Transformed ? t.WireLocal : t.Name;

            if (method.Parameters.Length == 0)
            {
                sb.AppendLine("            System.ReadOnlyMemory<byte> argsBytes = System.ReadOnlyMemory<byte>.Empty;");
            }
            else if (serializer == DetectedSerializer.MemoryPack)
            {
                if (transforms.Count == 1)
                {
                    sb.AppendLine($"            System.ReadOnlyMemory<byte> argsBytes = MemoryPackSerializer.Serialize({Arg(transforms[0])});");
                }
                else
                {
                    sb.AppendLine("            var argsBuffer = new System.Buffers.ArrayBufferWriter<byte>();");
                    foreach (var t in transforms)
                        sb.AppendLine($"            MemoryPackSerializer.Serialize(argsBuffer, {Arg(t)});");
                    sb.AppendLine("            System.ReadOnlyMemory<byte> argsBytes = argsBuffer.WrittenMemory;");
                }
            }
            else
            {
                // Pooled writer: container-owned, no `using`. Reset() before write, the ROM
                // returned from Complete() stays valid until the next Reset on this writer
                // — long enough for the awaited QueryCallAsync to complete and the codec
                // to send the bytes on the wire.
                sb.AppendLine("            var payloadWriter = _serializer.CreateWriter();");
                sb.AppendLine("            payloadWriter.Reset();");
                foreach (var t in transforms)
                    sb.AppendLine($"            payloadWriter.Write({Arg(t)});");
                sb.AppendLine("            System.ReadOnlyMemory<byte> argsBytes = payloadWriter.Complete();");
            }

            sb.AppendLine();
            sb.AppendLine("            var response = await _connection.QueryCallAsync(new QueryCallRequest");
            sb.AppendLine("            {");
            sb.AppendLine("                EntityId = _entityId,");
            sb.AppendLine($"                MethodId = global::{namespaceName}.Generated.GameMethodIds.{SignatureHashGenerator.MakeMethodIdConstName(interfaceName, method.Alias, method.Version)},");
            sb.AppendLine("                Payload = argsBytes");
            sb.AppendLine("            });");
            sb.AppendLine();
            sb.AppendLine("            if (!response.Success)");
            sb.AppendLine("                throw new InvalidOperationException($\"Query failed: {response.Error}\");");

            if (!isVoidReturn)
            {
                sb.AppendLine();
                if (serializer == DetectedSerializer.MemoryPack)
                    sb.AppendLine($"            return MemoryPackSerializer.Deserialize<{innerType}>(response.ResultBytes.Span)!;");
                else
                    sb.AppendLine($"            return _serializer.Unpack<{innerType}>(response.ResultBytes)!;");
            }

            sb.AppendLine("        }");
        }

        private class QueryMethodInfo
        {
            public string Name { get; set; } = "";
            public string Alias { get; set; } = "";
            public int Version { get; set; }
            public ITypeSymbol ReturnType { get; set; } = null!;
            public System.Collections.Immutable.ImmutableArray<IParameterSymbol> Parameters { get; set; }
        }
    }
}
