using System.Text;
using System.Linq;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SharedMeta.Generator.Utilities;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Generates server-side dispatcher classes that route method calls.
    /// Supports argument transformers (explicit and auto-discovery).
    /// Generates trigger execution code after method calls.
    /// </summary>
    public static class ServerDispatcherGenerator
    {
        /// <summary>
        /// Represents a trigger method with its on-method and condition.
        /// </summary>
        private class TriggerInfo
        {
            public string TriggerMethodName { get; set; } = "";
            public string OnMethod { get; set; } = "";
            public string? Condition { get; set; }
        }

        public static string Generate(string symbol, string namespaceName, InterfaceDeclarationSyntax node, INamedTypeSymbol? interfaceSymbol = null, Compilation? compilation = null)
        {
            var methods = node.Members.OfType<MethodDeclarationSyntax>().ToList();

            // Detect serializer type
            var serializer = compilation != null ? SerializerDetector.Detect(compilation) : DetectedSerializer.Generic;

            // Collect triggers from interface and implementation
            var triggersByMethod = CollectTriggers(interfaceSymbol, compilation);

            // Collect multi-parameter arities for MemoryPack UnpackArgs helpers
            var multiParamArities = new HashSet<int>();
            if (serializer == DetectedSerializer.MemoryPack)
            {
                foreach (var m in methods)
                {
                    var pCount = m.ParameterList.Parameters.Count;
                    var hasTransformers = m.ParameterList.Parameters.Any(p =>
                        p.AttributeLists.SelectMany(a => a.Attributes).Any(a => a.Name.ToString().Contains("Transform")));
                    if (pCount >= 2 && !hasTransformers)
                        multiParamArities.Add(pCount);
                }
            }

            var sbServer = new StringBuilder();
            sbServer.AppendLine("// <auto-generated/>");
            sbServer.AppendLine("#pragma warning disable CS1998");
            sbServer.AppendLine("#nullable enable");
            sbServer.AppendLine("using System;");
            sbServer.AppendLine("using System.Collections.Generic;");
            sbServer.AppendLine("using System.Threading.Tasks;");
            sbServer.AppendLine("using SharedMeta.Core;");
            if (serializer == DetectedSerializer.MemoryPack)
            {
                sbServer.AppendLine("using MemoryPack;");
            }
            sbServer.AppendLine($"using {namespaceName};");
            sbServer.AppendLine($"namespace {namespaceName}.Server");
            sbServer.AppendLine("{");
            sbServer.AppendLine($"    public static class {symbol}Dispatcher");
            sbServer.AppendLine("    {");

            // Generate static UnpackArgs helpers for each arity (non-async, so ref struct MemoryPackReader is allowed)
            foreach (var arity in multiParamArities.OrderBy(a => a))
            {
                GenerateUnpackArgsHelper(sbServer, arity);
            }

            // Generate dispatch method signature - returns DispatchResult for trigger support
            sbServer.AppendLine($"        public static async Task<DispatchResult> Dispatch({symbol} service, string method, byte[] payload, IMetaSerializer serializer)");
            sbServer.AppendLine("        {");

            // Always get context for auto-discovery support
            sbServer.AppendLine("            var context = MetaContextAccessor.Current ?? throw new InvalidOperationException(\"MetaContext not set. Ensure MetaContextAccessor.Current is set before calling Dispatch.\");");

            sbServer.AppendLine("            switch (method)");
            sbServer.AppendLine("            {");

            foreach (var method in methods)
            {
                var methodName = method.Identifier.Text;
                var returnType = method.ReturnType.ToString();
                var paramCount = method.ParameterList.Parameters.Count;

                var methodAlias = methodName;
                var forcePersist = false;
                var attributes = method.AttributeLists.SelectMany(a => a.Attributes);
                var metaMethod = attributes.FirstOrDefault(a => a.Name.ToString().Contains("MetaMethod"));
                if (metaMethod != null)
                {
                    var aliasArg = metaMethod.ArgumentList?.Arguments.FirstOrDefault(arg => arg.NameEquals != null && arg.NameEquals.Name.Identifier.Text == "Alias");
                    if (aliasArg != null && aliasArg.Expression is LiteralExpressionSyntax literal)
                    {
                        methodAlias = literal.Token.ValueText;
                    }

                    var forcePersistArg = metaMethod.ArgumentList?.Arguments.FirstOrDefault(arg => arg.NameEquals != null && arg.NameEquals.Name.Identifier.Text == "ForcePersist");
                    if (forcePersistArg != null && forcePersistArg.Expression is LiteralExpressionSyntax fpLiteral)
                    {
                        forcePersist = fpLiteral.Token.ValueText == "true";
                    }
                }

                sbServer.AppendLine($"                case \"{methodAlias}\":");
                sbServer.AppendLine("                {");

                // Unpack args sequentially
                if (paramCount > 0)
                {
                    // Check if any parameter has transformers (need generic mode for those)
                    var hasTransformers = method.ParameterList.Parameters.Any(p =>
                    {
                        var attrs = p.AttributeLists.SelectMany(a => a.Attributes).ToList();
                        return attrs.Any(a => a.Name.ToString().Contains("Transform"));
                    });

                    // Use MemoryPack direct deserialization when available and no transformers
                    if (serializer == DetectedSerializer.MemoryPack && !hasTransformers)
                    {
                        GenerateMemoryPackArgumentUnpacking(sbServer, method, out var argNames);
                        var callArgs = string.Join(", ", argNames);
                        GenerateMethodCallWithTriggers(sbServer, methodName, callArgs, returnType, triggersByMethod, serializer, forcePersist);
                    }
                    else
                    {
                        // Generic mode with IPayloadReader
                        sbServer.AppendLine("                    using var reader = serializer.CreateReader(payload);");

                        var argNames = new System.Collections.Generic.List<string>();
                        foreach (var param in method.ParameterList.Parameters)
                        {
                            var paramType = param.Type!.ToString();
                            var paramName = param.Identifier.Text;
                            var paramAttrs = param.AttributeLists.SelectMany(a => a.Attributes).ToList();

                            var hasSkipTransform = paramAttrs.Any(a => a.Name.ToString().Contains("SkipTransform"));
                            var transformAttr = paramAttrs.FirstOrDefault(a =>
                                a.Name.ToString().Contains("Transform") && !a.Name.ToString().Contains("SkipTransform"));

                            if (hasSkipTransform)
                            {
                                // [SkipTransform] - read as-is
                                sbServer.AppendLine($"                    var {paramName} = reader.Read<{paramType}>();");
                            }
                            else if (transformAttr != null && transformAttr.ArgumentList?.Arguments.Count > 0)
                            {
                                // [Transform(typeof(T))] - use explicit transformer
                                var transformerTypeArg = transformAttr.ArgumentList.Arguments.First();
                                if (transformerTypeArg.Expression is TypeOfExpressionSyntax typeOf)
                                {
                                    var transformerTypeName = typeOf.Type.ToString();
                                    sbServer.AppendLine($"                    // Unbox {paramName} using explicit {transformerTypeName}");
                                    sbServer.AppendLine($"                    var boxedBytes_{paramName} = reader.Read<byte[]>();");
                                    sbServer.AppendLine($"                    var simpleType_{paramName} = MetaContext.GetSimpleType(typeof({transformerTypeName}));");
                                    sbServer.AppendLine($"                    var boxed_{paramName} = serializer.Unpack(simpleType_{paramName}, boxedBytes_{paramName});");
                                    sbServer.AppendLine($"                    var {paramName} = ({paramType})context.UnboxValue(typeof({transformerTypeName}), boxed_{paramName}!);");
                                }
                                else
                                {
                                    sbServer.AppendLine($"                    var {paramName} = reader.Read<{paramType}>();");
                                }
                            }
                            else
                            {
                                // Auto-discovery - use compact helper
                                sbServer.AppendLine($"                    var {paramName} = context.ReadWithAutoUnbox<{paramType}>(reader, serializer);");
                            }

                            argNames.Add(paramName);
                        }

                        var callArgs = string.Join(", ", argNames);
                        GenerateMethodCallWithTriggers(sbServer, methodName, callArgs, returnType, triggersByMethod, serializer, forcePersist);
                    }
                }
                else
                {
                    // No args
                    GenerateMethodCallWithTriggers(sbServer, methodName, "", returnType, triggersByMethod, serializer, forcePersist);
                }

                sbServer.AppendLine("                }");
            }
            sbServer.AppendLine("                default: throw new MissingMethodException(method);");
            sbServer.AppendLine("            }");
            sbServer.AppendLine("        }");
            sbServer.AppendLine("    }");
            sbServer.AppendLine("}");
            return sbServer.ToString();
        }

        /// <summary>
        /// Generates MemoryPack-specific argument unpacking code.
        /// </summary>
        private static void GenerateMemoryPackArgumentUnpacking(StringBuilder sb, MethodDeclarationSyntax method, out List<string> argNames)
        {
            argNames = new List<string>();
            var parameters = method.ParameterList.Parameters;

            if (parameters.Count == 1)
            {
                // Single parameter - direct deserialization
                var param = parameters[0];
                var paramType = param.Type!.ToString();
                var paramName = param.Identifier.Text;
                sb.AppendLine($"                    var {paramName} = MemoryPackSerializer.Deserialize<{paramType}>(payload)!;");
                argNames.Add(paramName);
            }
            else
            {
                // Multiple parameters - use static UnpackArgs helper (non-async, so ref struct MemoryPackReader is safe)
                var typeArgs = string.Join(", ", parameters.Select(p => p.Type!.ToString()));
                var names = parameters.Select(p => p.Identifier.Text).ToList();
                var namesList = string.Join(", ", names);
                sb.AppendLine($"                    var ({namesList}) = UnpackArgs<{typeArgs}>(payload);");
                argNames.AddRange(names);
            }
        }

        /// <summary>
        /// Generates a static UnpackArgs helper method for a given arity.
        /// Non-async method, so ref struct MemoryPackReader is allowed in all C# versions.
        /// </summary>
        private static void GenerateUnpackArgsHelper(StringBuilder sb, int arity)
        {
            var typeParams = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"T{i}"));
            var returnType = $"({typeParams})";
            sb.AppendLine();
            sb.AppendLine($"        private static {returnType} UnpackArgs<{typeParams}>(byte[] payload)");
            sb.AppendLine("        {");
            sb.AppendLine("            var mpState = MemoryPackReaderOptionalStatePool.Rent(null);");
            sb.AppendLine("            var mpReader = new MemoryPackReader(payload, mpState);");
            for (int i = 1; i <= arity; i++)
            {
                sb.AppendLine($"            var v{i} = mpReader.ReadValue<T{i}>()!;");
            }
            sb.AppendLine("            mpReader.Dispose();");
            var returnValues = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"v{i}"));
            sb.AppendLine($"            return ({returnValues});");
            sb.AppendLine("        }");
        }

        /// <summary>
        /// Collects trigger information from both interface and implementation classes.
        /// </summary>
        private static Dictionary<string, List<TriggerInfo>> CollectTriggers(INamedTypeSymbol? interfaceSymbol, Compilation? compilation)
        {
            var result = new Dictionary<string, List<TriggerInfo>>();

            if (interfaceSymbol == null || compilation == null)
                return result;

            // 1. Collect triggers from interface methods
            CollectTriggersFromType(interfaceSymbol, result);

            // 2. Find implementation classes and collect their triggers
            foreach (var syntaxTree in compilation.SyntaxTrees)
            {
                var semanticModel = compilation.GetSemanticModel(syntaxTree);
                var root = syntaxTree.GetRoot();

                foreach (var classDecl in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
                {
                    var classSymbol = semanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                    if (classSymbol == null) continue;

                    // Check if this class implements the interface
                    if (classSymbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, interfaceSymbol)))
                    {
                        CollectTriggersFromType(classSymbol, result);
                    }
                }
            }

            return result;
        }

        /// <summary>
        /// Collects triggers from a type's methods.
        /// </summary>
        private static void CollectTriggersFromType(INamedTypeSymbol typeSymbol, Dictionary<string, List<TriggerInfo>> result)
        {
            foreach (var member in typeSymbol.GetMembers().OfType<IMethodSymbol>())
            {
                foreach (var attr in member.GetAttributes())
                {
                    if (attr.AttributeClass?.Name == "TriggerAttribute" ||
                        attr.AttributeClass?.ToDisplayString() == "SharedMeta.Core.TriggerAttribute")
                    {
                        var triggerInfo = new TriggerInfo
                        {
                            TriggerMethodName = member.Name
                        };

                        // Extract "On" and "Condition" properties
                        foreach (var arg in attr.NamedArguments)
                        {
                            if (arg.Key == "On" && arg.Value.Value is string onValue)
                            {
                                triggerInfo.OnMethod = onValue;
                            }
                            else if (arg.Key == "Condition" && arg.Value.Value is string conditionValue)
                            {
                                triggerInfo.Condition = conditionValue;
                            }
                        }

                        if (!string.IsNullOrEmpty(triggerInfo.OnMethod))
                        {
                            if (!result.ContainsKey(triggerInfo.OnMethod))
                                result[triggerInfo.OnMethod] = new List<TriggerInfo>();

                            // Avoid duplicates (same trigger might be found on interface and implementation)
                            if (!result[triggerInfo.OnMethod].Any(t => t.TriggerMethodName == triggerInfo.TriggerMethodName))
                            {
                                result[triggerInfo.OnMethod].Add(triggerInfo);
                            }
                        }
                    }
                }
            }
        }

        /// <summary>
        /// Generates code to collect triggers that should execute (evaluates conditions, does NOT execute).
        /// Returns the variable name containing the trigger list, or null if no triggers.
        /// </summary>
        private static string? GenerateTriggerCollection(StringBuilder sb, string methodName, Dictionary<string, List<TriggerInfo>> triggersByMethod, string indent)
        {
            if (!triggersByMethod.TryGetValue(methodName, out var triggers) || triggers.Count == 0)
                return null;

            sb.AppendLine($"{indent}// Collect triggers for {methodName}");
            sb.AppendLine($"{indent}var triggers = new List<string>();");

            foreach (var trigger in triggers)
            {
                if (!string.IsNullOrEmpty(trigger.Condition))
                {
                    // Has condition - check it first
                    sb.AppendLine($"{indent}if (service.{trigger.Condition}())");
                    sb.AppendLine($"{indent}{{");
                    sb.AppendLine($"{indent}    triggers.Add(\"{trigger.TriggerMethodName}\");");
                    sb.AppendLine($"{indent}}}");
                }
                else
                {
                    // No condition - always execute
                    sb.AppendLine($"{indent}triggers.Add(\"{trigger.TriggerMethodName}\");");
                }
            }

            return "triggers";
        }

        /// <summary>
        /// Generates method call code and returns DispatchResult with triggers to execute.
        /// </summary>
        private static void GenerateMethodCallWithTriggers(StringBuilder sb, string methodName, string callArgs, string returnType, Dictionary<string, List<TriggerInfo>> triggersByMethod, DetectedSerializer serializer = DetectedSerializer.Generic, bool forcePersist = false)
        {
            const string indent = "                    ";

            // Determine how to pack results based on serializer
            string GetResultPacking(string resultVar)
            {
                if (serializer == DetectedSerializer.MemoryPack)
                    return $"MemoryPackSerializer.Serialize({resultVar})";
                else
                    return $"serializer.Pack({resultVar})";
            }

            if (returnType == "System.Threading.Tasks.Task" || returnType == "Task")
            {
                sb.AppendLine($"{indent}await service.{methodName}({callArgs});");
                var triggersVar = GenerateTriggerCollection(sb, methodName, triggersByMethod, indent);
                GenerateDispatchResultReturn(sb, indent, "null", triggersVar, forcePersist);
            }
            else if (returnType.StartsWith("System.Threading.Tasks.Task<") || returnType.StartsWith("Task<"))
            {
                sb.AppendLine($"{indent}var result = await service.{methodName}({callArgs});");
                var triggersVar = GenerateTriggerCollection(sb, methodName, triggersByMethod, indent);
                GenerateDispatchResultReturn(sb, indent, GetResultPacking("result"), triggersVar, forcePersist);
            }
            else if (returnType == "void")
            {
                sb.AppendLine($"{indent}service.{methodName}({callArgs});");
                var triggersVar = GenerateTriggerCollection(sb, methodName, triggersByMethod, indent);
                GenerateDispatchResultReturn(sb, indent, "null", triggersVar, forcePersist);
            }
            else
            {
                sb.AppendLine($"{indent}var result = service.{methodName}({callArgs});");
                var triggersVar = GenerateTriggerCollection(sb, methodName, triggersByMethod, indent);
                GenerateDispatchResultReturn(sb, indent, GetResultPacking("result"), triggersVar, forcePersist);
            }
        }

        /// <summary>
        /// Generates the return statement for DispatchResult.
        /// </summary>
        private static void GenerateDispatchResultReturn(StringBuilder sb, string indent, string resultBytesExpr, string? triggersVar, bool forcePersist = false)
        {
            var forcePersistPart = forcePersist ? ", ForcePersist = true" : "";

            if (triggersVar != null)
            {
                sb.AppendLine($"{indent}return new DispatchResult {{ ResultBytes = {resultBytesExpr}, TriggersToExecute = {triggersVar}.Count > 0 ? {triggersVar} : null{forcePersistPart} }};");
            }
            else
            {
                sb.AppendLine($"{indent}return new DispatchResult {{ ResultBytes = {resultBytesExpr}{forcePersistPart} }};");
            }
        }
    }
}
