using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SharedMeta.Generator.Utilities;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Generates <c>{Service}ServerApi</c> — a typed entry point for invoking a service's meta
    /// methods from server code that is not itself running inside a meta call: admin tooling,
    /// framework grains, background jobs.
    /// </summary>
    /// <remarks>
    /// Routes through <c>IEntityGrainBase.HandleCallFromEntityAsync</c>, the same server-internal
    /// entry cross-entity calls use, so a server-originated call is an ordinary dispatch: replay
    /// recording, broadcast to every subscriber, persistence and sequence advance all happen. The
    /// entity does not need an active subscriber — a cold entity activates, migrates and persists.
    /// <para>
    /// Distinct from <c>{Service}EntityRecorder</c>, which implements the same shape but records
    /// into an enclosing call's replay tape. This one IS the origin, so there is nothing to record
    /// into and no <c>IServerRecordContext</c> to borrow buffers from.
    /// </para>
    /// <para>
    /// Callable methods deliberately include those with <c>GenerateClientApi = false</c>: the whole
    /// point is a surface clients cannot reach. Authorization is the caller's responsibility —
    /// reaching this class already means running inside the silo.
    /// </para>
    /// </remarks>
    public static class ServerApiGenerator
    {
        /// <param name="emitServerGuard">
        /// True in a shared project, where the file must be fenced off from Unity / client builds
        /// that have no Orleans. False in a server project, which defines the symbol anyway and
        /// generates this from referenced metadata.
        /// </param>
        public static string? Generate(INamedTypeSymbol symbol, Compilation compilation, bool emitServerGuard = true)
        {
            var attr = symbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceAttribute");
            if (attr == null) return null;

            // The grain reference is typed on the state, so a service without one has no entity to
            // address and no server API to offer.
            var stateTypeArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "StateType");
            if (stateTypeArg.Value.IsNull || stateTypeArg.Value.Value is not INamedTypeSymbol stateType)
                return null;

            var methods = CollectMethods(symbol, compilation);
            if (methods.Count == 0) return null;

            var interfaceName = symbol.Name;
            var namespaceName = symbol.ContainingNamespace.ToDisplayString();
            var baseName = interfaceName.StartsWith("I") && interfaceName.Length > 1 && char.IsUpper(interfaceName[1])
                ? interfaceName.Substring(1)
                : interfaceName;
            // Keyed to the declaring assembly, not this compilation: the dispatcher that unpacks
            // these arguments was generated there, and a server project can reference MemoryPack
            // while its shared assembly does not.
            var serializer = SerializerDetector.DetectForAssembly(symbol.ContainingAssembly, compilation);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            if (emitServerGuard)
            {
                sb.AppendLine("// Server-side service API — only compiled when SHAREDMETA_SERVER is defined.");
                sb.AppendLine("#if SHAREDMETA_SERVER");
            }
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using SharedMeta.Core;");
            sb.AppendLine("using SharedMeta.Server.Core.Grains;");
            if (serializer == DetectedSerializer.MemoryPack)
                sb.AppendLine("using MemoryPack;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}.Server");
            sb.AppendLine("{");

            EmitApiClass(sb, symbol, stateType, methods, baseName, interfaceName, namespaceName, serializer);
            EmitExtension(sb, baseName, interfaceName, namespaceName, serializer);

            sb.AppendLine("}");
            if (emitServerGuard) sb.AppendLine("#endif // SHAREDMETA_SERVER");
            return sb.ToString();
        }

        /// <summary>
        /// The service's full method surface: interface declarations plus methods whose contract is
        /// inherited and whose <c>[MetaMethod]</c> therefore sits on the implementing class.
        /// </summary>
        private static List<IMethodSymbol> CollectMethods(INamedTypeSymbol symbol, Compilation compilation)
        {
            var methods = symbol.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(m => m.MethodKind == MethodKind.Ordinary)
                .ToList();

            methods.AddRange(ImplDeclaredMethods.SymbolsForService(symbol, compilation));

            // Query and LocalQuery run through their own entry points and never produce a
            // broadcast; routing them through the cross-entity path would misreport them as
            // state-advancing operations.
            return methods.Where(m => !IsMode(m, "Query") && !IsMode(m, "LocalQuery")).ToList();
        }

        private static void EmitApiClass(
            StringBuilder sb, INamedTypeSymbol symbol, INamedTypeSymbol stateType, List<IMethodSymbol> methods,
            string baseName, string interfaceName, string namespaceName, DetectedSerializer serializer)
        {
            var stateFqn = stateType.ToDisplayString();

            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Invokes {interfaceName} meta methods on an entity from server code.");
            sb.AppendLine($"    /// Each call dispatches through the entity grain, so state changes are recorded,");
            sb.AppendLine($"    /// broadcast to subscribers and persisted exactly as for a client-originated call.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public sealed class {baseName}ServerApi");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly IEntityGrainBase _grain;");
            sb.AppendLine("        private readonly string? _callerClientVersion;");
            if (serializer != DetectedSerializer.MemoryPack)
                sb.AppendLine("        private readonly IMetaSerializer _serializer;");
            sb.AppendLine();
            sb.AppendLine("        /// <param name=\"callerClientVersion\">");
            sb.AppendLine("        /// App version to run the call under, deciding which config branch the body executes");
            sb.AppendLine("        /// against and how far state migration may advance. Leave null to let the entity");
            sb.AppendLine("        /// resolve it — pass a value only to deliberately act as a specific client build,");
            sb.AppendLine("        /// e.g. driving a staged migration ahead of the owning player's version.");
            sb.AppendLine("        /// </param>");
            sb.Append($"        public {baseName}ServerApi(Orleans.IGrainFactory grainFactory, string entityId");
            sb.Append(serializer != DetectedSerializer.MemoryPack ? ", IMetaSerializer serializer" : "");
            sb.AppendLine(", string? callerClientVersion = null)");
            sb.AppendLine("        {");
            sb.AppendLine($"            _grain = grainFactory.GetGrain<IEntityGrain<{stateFqn}>>(entityId);");
            sb.AppendLine("            _callerClientVersion = callerClientVersion;");
            if (serializer != DetectedSerializer.MemoryPack)
                sb.AppendLine("            _serializer = serializer;");
            sb.AppendLine("        }");

            foreach (var method in methods)
                EmitMethod(sb, method, symbol, interfaceName, namespaceName, serializer);

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void EmitMethod(
            StringBuilder sb, IMethodSymbol method, INamedTypeSymbol symbol,
            string interfaceName, string namespaceName, DetectedSerializer serializer)
        {
            var (alias, version) = ReadAliasAndVersion(method);
            var methodIdConst = "global::" + namespaceName + ".Generated.GameMethodIds."
                + SignatureHashGenerator.MakeMethodIdConstName(interfaceName, alias, version);

            // Symbol names carry no @ escape, so a parameter legitimately called `event` or
            // `params` in source would emit a keyword here. Escaping unconditionally is valid for
            // ordinary identifiers too, which keeps this free of a keyword table.
            var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type.ToDisplayString()} @{p.Name}"));
            var paramNames = method.Parameters.Select(p => "@" + p.Name).ToList();
            var (_, innerType) = ParseReturnType(method.ReturnType.ToDisplayString());

            var methodName = method.Name.EndsWith("Async") ? method.Name : method.Name + "Async";

            sb.AppendLine();
            sb.AppendLine($"        [global::SharedMeta.Core.GeneratedFromMetaMethod(typeof(global::{symbol.ToDisplayString()}), \"{method.Name}\")]");

            // Notification is fire-and-forget by declaration: the [OneWay] grain entry suppresses
            // the reply envelope, so the returned Task completes on dispatch, not on completion.
            if (IsMode(method, "Notification"))
            {
                sb.AppendLine($"        public Task {methodName}({parameters})");
                sb.AppendLine("        {");
                EmitArgumentPacking(sb, paramNames, serializer);
                sb.AppendLine($"            return _grain.HandleCallFromEntityOneWayAsync(new RpcCall");
                sb.AppendLine("            {");
                sb.AppendLine($"                MethodId = {methodIdConst},");
                sb.AppendLine("                Payload = __argsBytes,");
                sb.AppendLine("                ServerTimeTicks = DateTime.UtcNow.Ticks,");
                sb.AppendLine("                CallerClientVersion = _callerClientVersion,");
                sb.AppendLine("            });");
                sb.AppendLine("        }");
                return;
            }

            var returnType = innerType != null ? $"Task<{innerType}>" : "Task";
            sb.AppendLine($"        public async {returnType} {methodName}({parameters})");
            sb.AppendLine("        {");
            EmitArgumentPacking(sb, paramNames, serializer);
            // Locals are __-prefixed: user parameter names share this scope, and a service method
            // taking a parameter called "result" or "buffer" must not collide with generated code.
            sb.AppendLine("            var __call = await _grain.HandleCallFromEntityAsync(new RpcCall");
            sb.AppendLine("            {");
            sb.AppendLine($"                MethodId = {methodIdConst},");
            sb.AppendLine("                Payload = __argsBytes,");
            sb.AppendLine("                ServerTimeTicks = DateTime.UtcNow.Ticks,");
            sb.AppendLine("                CallerClientVersion = _callerClientVersion,");
            sb.AppendLine("            });");
            sb.AppendLine();
            // Surface the failure rather than returning a default: a server-originated call has no
            // client response channel to carry the error, so swallowing it would lose it entirely.
            sb.AppendLine("            if (__call.HasError)");
            sb.AppendLine($"                throw new InvalidOperationException($\"{interfaceName}.{alias} on entity failed: {{__call.Error}}\");");

            if (innerType != null)
            {
                sb.AppendLine();
                sb.AppendLine(serializer == DetectedSerializer.MemoryPack
                    ? $"            return MemoryPackSerializer.Deserialize<{innerType}>(__call.ResultBytes.Span)!;"
                    : $"            return _serializer.Unpack<{innerType}>(__call.ResultBytes)!;");
            }

            sb.AppendLine("        }");
        }

        /// <summary>
        /// Packs arguments into the same wire shape the dispatcher reads. Buffers are local rather
        /// than pooled: a server-originated call is a cold path (admin action, match notification),
        /// not the per-RPC hot path the recorder's cached writers exist for.
        /// </summary>
        private static void EmitArgumentPacking(StringBuilder sb, List<string> paramNames, DetectedSerializer serializer)
        {
            if (paramNames.Count == 0)
            {
                sb.AppendLine("            System.ReadOnlyMemory<byte> __argsBytes = Array.Empty<byte>();");
                return;
            }

            if (serializer == DetectedSerializer.MemoryPack)
            {
                if (paramNames.Count == 1)
                {
                    sb.AppendLine($"            System.ReadOnlyMemory<byte> __argsBytes = MemoryPackSerializer.Serialize({paramNames[0]});");
                }
                else
                {
                    sb.AppendLine("            var __buffer = new System.Buffers.ArrayBufferWriter<byte>();");
                    foreach (var paramName in paramNames)
                        sb.AppendLine($"            MemoryPackSerializer.Serialize(__buffer, {paramName});");
                    sb.AppendLine("            System.ReadOnlyMemory<byte> __argsBytes = __buffer.WrittenMemory;");
                }
            }
            else
            {
                sb.AppendLine("            using var __writer = _serializer.CreateWriter();");
                foreach (var paramName in paramNames)
                    sb.AppendLine($"            __writer.Write({paramName});");
                sb.AppendLine("            System.ReadOnlyMemory<byte> __argsBytes = __writer.Complete();");
            }
        }

        /// <summary>
        /// <c>grainFactory.GetServerApi&lt;IProfileService&gt;(entityId)</c>. Constrained to the
        /// service interface so the type argument names the service and the compiler picks the one
        /// generated overload — a compile-time selection, no runtime type dispatch.
        /// </summary>
        private static void EmitExtension(StringBuilder sb, string baseName, string interfaceName, string namespaceName, DetectedSerializer serializer)
        {
            // The generic serializer path needs an IMetaSerializer the extension has no way to
            // obtain, so the convenience accessor is MemoryPack-only; those projects construct the
            // API class directly and hand it their serializer.
            bool needsSerializer = serializer != DetectedSerializer.MemoryPack;

            sb.AppendLine($"    public static class {baseName}ServerApiExtensions");
            sb.AppendLine("    {");
            sb.AppendLine($"        /// <summary>Typed server-side API for {interfaceName} on <paramref name=\"entityId\"/>.</summary>");
            sb.AppendLine("        /// <param name=\"callerClientVersion\">");
            sb.AppendLine("        /// App version to run calls under — decides the config branch the method body executes");
            sb.AppendLine("        /// against and how far state migration may advance. Leave null to let the entity resolve");
            sb.AppendLine("        /// it; pass a value only to deliberately act as a specific client build.");
            sb.AppendLine("        /// </param>");
            var serializerParam = needsSerializer ? "IMetaSerializer serializer, " : "";
            var serializerArg = needsSerializer ? "serializer, " : "";
            sb.AppendLine($"        public static {baseName}ServerApi GetServerApi<TService>(this Orleans.IGrainFactory grainFactory, string entityId, {serializerParam}string? callerClientVersion = null)");
            sb.AppendLine($"            where TService : global::{namespaceName}.{interfaceName}");
            sb.AppendLine($"            => new {baseName}ServerApi(grainFactory, entityId, {serializerArg}callerClientVersion);");
            sb.AppendLine();

            // Same accessor over the DI handle. Identical shape whichever serializer the service's
            // assembly declared — the generic path's serializer comes from the handle instead of
            // from the call site.
            var factoryArg = needsSerializer ? "factory.Serializer, " : "";
            sb.AppendLine($"        /// <summary>Typed server-side API for {interfaceName}, with the serializer taken from DI.</summary>");
            sb.AppendLine($"        public static {baseName}ServerApi GetServerApi<TService>(this global::SharedMeta.Server.Core.IMetaServerApiFactory factory, string entityId, string? callerClientVersion = null)");
            sb.AppendLine($"            where TService : global::{namespaceName}.{interfaceName}");
            sb.AppendLine($"            => new {baseName}ServerApi(factory.GrainFactory, entityId, {factoryArg}callerClientVersion);");
            sb.AppendLine("    }");
        }

        private static (string alias, int version) ReadAliasAndVersion(IMethodSymbol method)
        {
            var alias = method.Name;
            var version = 0;
            var attr = method.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaMethodAttribute");
            if (attr == null) return (alias, version);

            var aliasArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "Alias");
            if (!aliasArg.Value.IsNull && aliasArg.Value.Value is string a2 && !string.IsNullOrEmpty(a2))
                alias = a2;

            var versionArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "Version");
            if (!versionArg.Value.IsNull && versionArg.Value.Value is int v)
                version = v;

            return (alias, version);
        }

        private static bool IsMode(IMethodSymbol method, string modeName)
        {
            var attr = method.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaMethodAttribute");
            if (attr == null) return false;

            foreach (var named in attr.NamedArguments)
            {
                if (named.Key != "Mode" || named.Value.IsNull) continue;
                if (named.Value.Value is not int value) continue;
                foreach (var field in named.Value.Type?.GetMembers().OfType<IFieldSymbol>() ?? Enumerable.Empty<IFieldSymbol>())
                {
                    if (field.HasConstantValue && field.ConstantValue is int fv && fv == value)
                        return field.Name == modeName;
                }
            }
            return false;
        }

        /// <summary>
        /// Unwraps the awaitable shell so the generated method returns <c>Task</c> /
        /// <c>Task&lt;T&gt;</c> over the value the dispatcher actually serializes. Service methods
        /// may be declared sync, <c>Task</c> or <c>ValueTask</c>; only the payload type differs.
        /// </summary>
        private static (bool isAsync, string? innerType) ParseReturnType(string returnType)
        {
            if (returnType is "System.Threading.Tasks.Task" or "Task"
                or "System.Threading.Tasks.ValueTask" or "ValueTask")
            {
                return (true, null);
            }

            var match = Regex.Match(returnType, @"^(?:System\.Threading\.Tasks\.)?(?:Task|ValueTask)<(.+)>$");
            if (match.Success) return (true, match.Groups[1].Value);

            return (false, returnType == "void" ? null : returnType);
        }
    }
}
