using System.Text;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Generates AddXxxServices() extension methods for DI registration.
    /// Creates MetaServiceConfig registrations for IMetaServiceResolver.
    /// </summary>
    public static class ServiceRegistrationGenerator
    {
        public static string? Generate(InterfaceDeclarationSyntax node, INamedTypeSymbol symbol)
        {
            // Check for [MetaService] attribute with state type
            var attr = symbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceAttribute");
            if (attr == null) return null;

            // Get state type from attribute if available
            var stateTypeArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "StateType");
            string? stateTypeName = null;
            string? stateTypeFullName = null;

            if (stateTypeArg.Value.Value is INamedTypeSymbol stateType)
            {
                stateTypeName = stateType.Name;
                stateTypeFullName = stateType.ToDisplayString();
            }

            // If no state type in attribute, we can't generate registration
            // The service registration will need to be done manually
            if (stateTypeName == null)
            {
                return null;
            }

            var interfaceName = symbol.Name;
            var namespaceName = symbol.ContainingNamespace.ToDisplayString();

            // Remove leading 'I' for class names
            var baseName = interfaceName;
            if (baseName.StartsWith("I") && baseName.Length > 1 && char.IsUpper(baseName[1]))
            {
                baseName = baseName.Substring(1);
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using SharedMeta.Core;");
            sb.AppendLine("using SharedMeta.Core.Network;");
            sb.AppendLine("using SharedMeta.Core.Diagnostics;");
            sb.AppendLine("using SharedMeta.Core.Random;");
            sb.AppendLine($"using {namespaceName};");
            sb.AppendLine($"using {namespaceName}.Client;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}.DependencyInjection");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// DI registration extensions for {interfaceName}.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public static class {baseName}ServiceExtensions");
            sb.AppendLine("    {");
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Register {baseName}ApiClient with IMetaServiceResolver.");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public static TResolver Add{baseName}Services<TResolver>(this TResolver resolver) where TResolver : IMetaServiceResolver");
            sb.AppendLine("        {");
            sb.AppendLine($"            resolver.RegisterService<{baseName}ApiClient>(new MetaServiceConfig");
            sb.AppendLine("            {");
            sb.AppendLine($"                ServiceName = \"{interfaceName}\",");
            sb.AppendLine($"                ApiClientType = typeof({baseName}ApiClient),");
            sb.AppendLine($"                StateType = typeof({stateTypeFullName}),");
            sb.AppendLine($"                LocalServiceType = typeof({baseName}),");
            sb.AppendLine($"                ApiClientFactory = (network, serializer, state, modeProvider, diagnostics, crossResolver, optimisticRandom) =>");
            sb.AppendLine($"                    new {baseName}ApiClient(network, serializer, ({stateTypeFullName})state, modeProvider, diagnostics, crossResolver, optimisticRandom),");
            sb.AppendLine($"                StateRefresher = (apiClient, state, random) =>");
            sb.AppendLine($"                    (({baseName}ApiClient)apiClient).RefreshState(({stateTypeFullName})state, random)");
            sb.AppendLine("            });");
            sb.AppendLine("            return resolver;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Get MetaServiceConfig for {baseName}ApiClient.");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public static MetaServiceConfig Get{baseName}ServiceConfig()");
            sb.AppendLine("        {");
            sb.AppendLine($"            return new MetaServiceConfig");
            sb.AppendLine("            {");
            sb.AppendLine($"                ServiceName = \"{interfaceName}\",");
            sb.AppendLine($"                ApiClientType = typeof({baseName}ApiClient),");
            sb.AppendLine($"                StateType = typeof({stateTypeFullName}),");
            sb.AppendLine($"                LocalServiceType = typeof({baseName}),");
            sb.AppendLine($"                ApiClientFactory = (network, serializer, state, modeProvider, diagnostics, crossResolver, optimisticRandom) =>");
            sb.AppendLine($"                    new {baseName}ApiClient(network, serializer, ({stateTypeFullName})state, modeProvider, diagnostics, crossResolver, optimisticRandom),");
            sb.AppendLine($"                StateRefresher = (apiClient, state, random) =>");
            sb.AppendLine($"                    (({baseName}ApiClient)apiClient).RefreshState(({stateTypeFullName})state, random)");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
