using System.Text;
using System.Linq;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SharedMeta.Generator.Utilities;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Generates server-side dispatcher classes that route method calls.
    /// Supports argument transformers (explicit and auto-discovery).
    /// Generates trigger execution code after method calls.
    /// </summary>
    public static class ServerDispatcherGenerator
    {
        /// <summary>
        /// Represents a trigger method with its on-method and condition.
        /// </summary>
        private class TriggerInfo
        {
            public string TriggerMethodName { get; set; } = "";
            public string TriggerMethodAlias { get; set; } = "";
            public int TriggerMethodVersion { get; set; }
            public string OnMethod { get; set; } = "";
            public string? Condition { get; set; }
        }

        public static string Generate(string symbol, string namespaceName, InterfaceDeclarationSyntax node, INamedTypeSymbol? interfaceSymbol = null, Compilation? compilation = null)
        {
            var methods = node.Members.OfType<MethodDeclarationSyntax>().ToList();

            // Detect serializer type
            var serializer = compilation != null ? SerializerDetector.Detect(compilation) : DetectedSerializer.Generic;

            // 0.26.6+ Resolve the service's state type from [MetaService(StateType = typeof(TState))].
            // Required by the deep-state-check emit (per-method snapshot of MetaContext<TState>.State).
            // Null when interfaceSymbol is unavailable — DeepStateCheck emit is skipped in that case.
            string? stateTypeFullName = null;
            if (interfaceSymbol != null)
            {
                var msAttr = interfaceSymbol.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceAttribute");
                if (msAttr != null)
                {
                    var stArg = msAttr.NamedArguments.FirstOrDefault(a => a.Key == "StateType");
                    if (!stArg.Value.IsNull && stArg.Value.Value is INamedTypeSymbol stSym)
                        stateTypeFullName = stSym.ToDisplayString();
                }
            }

            // Collect triggers from interface and implementation
            var triggersByMethod = CollectTriggers(interfaceSymbol, compilation);

            // Collect multi-parameter arities for MemoryPack UnpackArgs helpers
            var multiParamArities = new HashSet<int>();
            if (serializer == DetectedSerializer.MemoryPack)
            {
                foreach (var m in methods)
                {
                    var pCount = m.ParameterList.Parameters.Count;
                    var hasTransformers = m.ParameterList.Parameters.Any(p =>
                        p.AttributeLists.SelectMany(a => a.Attributes).Any(a => a.Name.ToString().Contains("Transform")));
                    if (pCount >= 2 && !hasTransformers)
                        multiParamArities.Add(pCount);
                }
            }

            var sbServer = new StringBuilder();
            sbServer.AppendLine("// <auto-generated/>");
            sbServer.AppendLine("#pragma warning disable CS1998");
            sbServer.AppendLine("#nullable enable");
            sbServer.AppendLine("using System;");
            sbServer.AppendLine("using System.Collections.Generic;");
            sbServer.AppendLine("using System.Threading.Tasks;");
            sbServer.AppendLine("using SharedMeta.Core;");
            if (serializer == DetectedSerializer.MemoryPack)
            {
                sbServer.AppendLine("using MemoryPack;");
            }
            sbServer.AppendLine($"using {namespaceName};");
            // Dispatcher results are packed via Context.Serializer (GrainScopedSerializer on
            // the server path) — serializer.Pack<T>(T) returns ROM<byte> over per-grain scratch.
            sbServer.AppendLine($"namespace {namespaceName}.Server");
            sbServer.AppendLine("{");
            sbServer.AppendLine($"    public static class {symbol}Dispatcher");
            sbServer.AppendLine("    {");

            // Generate static UnpackArgs helpers for each arity (non-async, so ref struct MemoryPackReader is allowed)
            foreach (var arity in multiParamArities.OrderBy(a => a))
            {
                GenerateUnpackArgsHelper(sbServer, arity);
            }

            // Async tails for genuinely-async service methods. Sync-completed methods build their
            // DispatchResult inline in the case body; methods that suspend hand the pending Task
            // off to a per-method tail helper. Accumulated during method emission, appended after
            // the main switch closes.
            var asyncTails = new StringBuilder();

            // Generate dispatch method signature - returns DispatchResult for trigger support.
            // 0.22.0: 'methodVersion' selects between coexisting [MetaMethod(Alias = X, Version = N)]
            // declarations sharing an alias. Callers pass 0 for legacy/unversioned dispatch, which
            // resolves to the lowest declared Version under the alias.
            // 0.23.0+ Non-async ValueTask entry. Sync-completed service methods skip the async
            // state-machine box entirely (`<Dispatch>d__0` was ~12 MB/s of allocation at 25K RPS).
            // Tasks that actually suspend fall through to a per-method `Await_{alias}_v{version}`
            // helper emitted after the switch.
            sbServer.AppendLine($"        public static ValueTask<DispatchResult> Dispatch({symbol} service, ushort methodId, System.ReadOnlyMemory<byte> payload, IMetaSerializer serializer)");
            sbServer.AppendLine("        {");
            sbServer.AppendLine("            var context = MetaContextAccessor.Current ?? throw new InvalidOperationException(\"MetaContext not set. Ensure MetaContextAccessor.Current is set before calling Dispatch.\");");

            // 0.24.0+ Switch on global ushort method id from GameMethodIds. Each (alias, version)
            // tuple is its own case label — version is encoded into the index, no nested switch.
            // Jump table on ushort lowers to a computed branch (much faster than string-pair match).
            var flatMethods = methods
                .Select(m => new { Method = m, Info = ReadMetaMethodInfo(m) })
                .ToList();

            sbServer.AppendLine("            switch (methodId)");
            sbServer.AppendLine("            {");

            foreach (var entry in flatMethods)
            {
                var alias = entry.Info.Alias;
                var version = entry.Info.Version;
                var idConst = "global::" + namespaceName + ".Generated.GameMethodIds." + SignatureHashGenerator.MakeMethodIdConstName(symbol, alias, version);
                sbServer.AppendLine($"                case {idConst}:");
                sbServer.AppendLine("                {");
                EmitMethodBody(sbServer, asyncTails, entry.Method, entry.Info, symbol, namespaceName, triggersByMethod, serializer, stateTypeFullName);
                sbServer.AppendLine("                }");
            }
            sbServer.AppendLine($"                default: throw new MissingMethodException($\"Method id {{methodId}} not registered on {symbol}\");");
            sbServer.AppendLine("            }");
            sbServer.AppendLine("        }");

            // Emit per-method async tail helpers collected during the main switch. Each helper
            // awaits the pending Task / Task<T> returned by a service method that didn't complete
            // synchronously, then builds the same DispatchResult the sync fast-path would have.
            sbServer.Append(asyncTails);

            sbServer.AppendLine("    }");

            // Signal dispatcher companion — only emitted when at least one [MetaMethod(Signal = true)]
            // is present. Separate static class with its own switch so the main dispatcher stays
            // focused on regular RPC routing (void return, no DispatchResult, no trigger logic,
            // no forcePersist flags — signals bypass all of that by contract).
            GenerateSignalDispatcherClass(sbServer, symbol, namespaceName, methods, serializer);

            sbServer.AppendLine("}");
            return sbServer.ToString();
        }

        /// <summary>
        /// Emits <c>public static class {Service}SignalDispatcher</c> with a <c>Dispatch(svc, method, payload, serializer)</c>
        /// that returns <see cref="System.Threading.Tasks.Task"/>. Route target is each interface method
        /// marked with <c>[MetaMethod(Signal = true)]</c>. Argument deserialization matches the main
        /// dispatcher's serializer contract so the same bytes shipped by the generated ApiClient land
        /// as typed parameters in the impl.
        /// </summary>
        private static void GenerateSignalDispatcherClass(StringBuilder sb, string symbol, string namespaceName,
            System.Collections.Generic.List<MethodDeclarationSyntax> methods, DetectedSerializer serializer)
        {
            var signalMethods = methods.Where(IsSignalMethod).ToList();
            if (signalMethods.Count == 0) return;

            sb.AppendLine();
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Server-side dispatcher for <c>[MetaMethod(Mode = ExecutionMode.Signal)]</c> methods on {symbol}.");
            sb.AppendLine($"    /// Called from the generated MetaProvider's DispatchSignal override.");
            sb.AppendLine($"    /// 0.24.0+ keyed by client-local <c>ushort MethodId</c> — each (alias, version) tuple");
            sb.AppendLine($"    /// is a distinct constant in <c>GameMethodIds</c>, so no inner version switch is needed.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public static class {symbol}SignalDispatcher");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static async Task Dispatch({symbol} service, ushort methodId, System.ReadOnlyMemory<byte> payload, IMetaSerializer serializer)");
            sb.AppendLine("        {");
            // MetaContext must be set by MetaProviderBase.HandleSignalAsync before calling here.
            sb.AppendLine("            var _ctx = MetaContextAccessor.Current ?? throw new InvalidOperationException(\"MetaContext not set for signal dispatch.\");");

            sb.AppendLine("            switch (methodId)");
            sb.AppendLine("            {");

            foreach (var method in signalMethods)
            {
                var info = ReadMetaMethodInfo(method);
                var idConst = "global::" + namespaceName + ".Generated.GameMethodIds." +
                    SignatureHashGenerator.MakeMethodIdConstName(symbol, info.Alias, info.Version);
                sb.AppendLine($"                case {idConst}:");
                sb.AppendLine("                {");
                EmitSignalBody(sb, method, info, symbol, serializer);
                sb.AppendLine("                    break;");
                sb.AppendLine("                }");
            }
            sb.AppendLine($"                default: throw new MissingMethodException($\"Signal methodId {{methodId}} not found on {symbol}\");");
            sb.AppendLine("            }");
            sb.AppendLine("            await Task.CompletedTask;  // keeps the method async for future async bridge calls inside signal bodies");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// Emit a single signal method body inside a case block: the GenerateClientApi gate plus
        /// the synchronous void call. No return value, no DispatchResult — signals run read-only
        /// by contract. Mirrors <see cref="EmitMethodBody"/> for the regular dispatcher.
        /// </summary>
        private static void EmitSignalBody(StringBuilder sb, MethodDeclarationSyntax method, MetaMethodInfo info, string symbol, DetectedSerializer serializer)
        {
            var methodName = method.Identifier.Text;
            var paramCount = method.ParameterList.Parameters.Count;

            if (!info.GenerateClientApi)
            {
                sb.AppendLine("                    if (_ctx.IsClientCall)");
                sb.AppendLine($"                        throw new System.InvalidOperationException(\"Method '{symbol}.{info.Alias}' is not callable from clients\");");
            }

            if (paramCount == 0)
            {
                sb.AppendLine($"                    service.{methodName}();");
            }
            else if (serializer == DetectedSerializer.MemoryPack)
            {
                // Mirror the client's GenerateArgumentSerialization MemoryPack branch — single-arg
                // ships raw `MemoryPackSerializer.Serialize(value)` bytes; multi-arg uses
                // MemoryPackWriter into an ArrayBufferWriter, which the multi-arity UnpackArgs
                // helper reads back via MemoryPackReader. CreateReader/Read<T>() expects a
                // length-prefixed envelope and would misread either form.
                GenerateMemoryPackArgumentUnpacking(sb, method, out var argNames);
                var callArgs = string.Join(", ", argNames);
                sb.AppendLine($"                    service.{methodName}({callArgs});");
            }
            else
            {
                sb.AppendLine("                    using var reader = serializer.CreateReader(payload);");
                var argNames = new List<string>();
                foreach (var param in method.ParameterList.Parameters)
                {
                    var paramType = param.Type!.ToString();
                    var paramName = param.Identifier.Text;
                    sb.AppendLine($"                    var {paramName} = reader.Read<{paramType}>();");
                    argNames.Add(paramName);
                }
                var callArgs = string.Join(", ", argNames);
                sb.AppendLine($"                    service.{methodName}({callArgs});");
            }
        }

        /// <summary>
        /// True if this interface method is a signal method — either <c>[MetaMethod(Mode = ExecutionMode.Signal)]</c>
        /// (canonical form) or the legacy <c>[MetaMethod(Signal = true)]</c> bool flag.
        /// </summary>
        private static bool IsSignalMethod(MethodDeclarationSyntax method)
        {
            var metaMethod = method.AttributeLists.SelectMany(a => a.Attributes)
                .FirstOrDefault(a => a.Name.ToString().Contains("MetaMethod"));
            if (metaMethod == null) return false;

            foreach (var arg in metaMethod.ArgumentList?.Arguments ?? Enumerable.Empty<AttributeArgumentSyntax>())
            {
                if (arg.NameEquals == null) continue;
                var name = arg.NameEquals.Name.Identifier.Text;
                if (name == "Signal"
                    && arg.Expression is LiteralExpressionSyntax lit
                    && lit.Token.Text == "true")
                    return true;
                if (name == "Mode"
                    && arg.Expression is MemberAccessExpressionSyntax modeAccess
                    && modeAccess.Name.Identifier.Text == "Signal")
                    return true;
            }
            return false;
        }

        /// <summary>
        /// Generates MemoryPack-specific argument unpacking code.
        /// </summary>
        private static void GenerateMemoryPackArgumentUnpacking(StringBuilder sb, MethodDeclarationSyntax method, out List<string> argNames)
        {
            argNames = new List<string>();
            var parameters = method.ParameterList.Parameters;

            if (parameters.Count == 1)
            {
                // Single parameter - direct deserialization
                var param = parameters[0];
                var paramType = param.Type!.ToString();
                var paramName = param.Identifier.Text;
                sb.AppendLine($"                    var {paramName} = MemoryPackSerializer.Deserialize<{paramType}>(payload.Span)!;");
                argNames.Add(paramName);
            }
            else
            {
                // Multiple parameters - use static UnpackArgs helper (non-async, so ref struct MemoryPackReader is safe)
                var typeArgs = string.Join(", ", parameters.Select(p => p.Type!.ToString()));
                var names = parameters.Select(p => p.Identifier.Text).ToList();
                var namesList = string.Join(", ", names);
                sb.AppendLine($"                    var ({namesList}) = UnpackArgs<{typeArgs}>(payload);");
                argNames.AddRange(names);
            }
        }

        /// <summary>
        /// Generates a static UnpackArgs helper method for a given arity.
        /// Non-async method, so ref struct MemoryPackReader is allowed in all C# versions.
        /// </summary>
        private static void GenerateUnpackArgsHelper(StringBuilder sb, int arity)
        {
            var typeParams = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"T{i}"));
            var returnType = $"({typeParams})";
            sb.AppendLine();
            sb.AppendLine($"        private static {returnType} UnpackArgs<{typeParams}>(System.ReadOnlyMemory<byte> payload)");
            sb.AppendLine("        {");
            sb.AppendLine("            var mpState = MemoryPackReaderOptionalStatePool.Rent(null);");
            sb.AppendLine("            var mpReader = new MemoryPackReader(payload.Span, mpState);");
            for (int i = 1; i <= arity; i++)
            {
                sb.AppendLine($"            var v{i} = mpReader.ReadValue<T{i}>()!;");
            }
            sb.AppendLine("            mpReader.Dispose();");
            var returnValues = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"v{i}"));
            sb.AppendLine($"            return ({returnValues});");
            sb.AppendLine("        }");
        }

        /// <summary>
        /// Collects trigger information from both interface and implementation classes.
        /// </summary>
        private static Dictionary<string, List<TriggerInfo>> CollectTriggers(INamedTypeSymbol? interfaceSymbol, Compilation? compilation)
        {
            var result = new Dictionary<string, List<TriggerInfo>>();

            if (interfaceSymbol == null || compilation == null)
                return result;

            // 1. Collect triggers from interface methods
            CollectTriggersFromType(interfaceSymbol, result);

            // 2. Find implementation classes and collect their triggers
            foreach (var syntaxTree in compilation.SyntaxTrees)
            {
                var semanticModel = compilation.GetSemanticModel(syntaxTree);
                var root = syntaxTree.GetRoot();

                foreach (var classDecl in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
                {
                    var classSymbol = semanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                    if (classSymbol == null) continue;

                    // Check if this class implements the interface
                    if (classSymbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, interfaceSymbol)))
                    {
                        CollectTriggersFromType(classSymbol, result);
                    }
                }
            }

            return result;
        }

        /// <summary>
        /// Collects triggers from a type's methods.
        /// </summary>
        private static void CollectTriggersFromType(INamedTypeSymbol typeSymbol, Dictionary<string, List<TriggerInfo>> result)
        {
            foreach (var member in typeSymbol.GetMembers().OfType<IMethodSymbol>())
            {
                foreach (var attr in member.GetAttributes())
                {
                    if (attr.AttributeClass?.Name == "TriggerAttribute" ||
                        attr.AttributeClass?.ToDisplayString() == "SharedMeta.Core.TriggerAttribute")
                    {
                        // 0.24.0+ Capture alias + version from the trigger method's own [MetaMethod]
                        // so the dispatcher can emit the GameMethodIds constant directly. Default
                        // alias = C# method name, default version = 0 (matches the convention
                        // used everywhere else for method-id resolution).
                        var triggerAlias = member.Name;
                        var triggerVersion = 0;
                        var metaMethodAttr = member.GetAttributes().FirstOrDefault(a =>
                            a.AttributeClass?.Name == "MetaMethodAttribute" ||
                            a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaMethodAttribute");
                        if (metaMethodAttr != null)
                        {
                            foreach (var na in metaMethodAttr.NamedArguments)
                            {
                                if (na.Key == "Alias" && na.Value.Value is string aliasOverride && !string.IsNullOrEmpty(aliasOverride))
                                    triggerAlias = aliasOverride;
                                else if (na.Key == "Version" && na.Value.Value is int versionOverride)
                                    triggerVersion = versionOverride;
                            }
                        }

                        var triggerInfo = new TriggerInfo
                        {
                            TriggerMethodName = member.Name,
                            TriggerMethodAlias = triggerAlias,
                            TriggerMethodVersion = triggerVersion,
                        };

                        // Extract "On" and "Condition" properties
                        foreach (var arg in attr.NamedArguments)
                        {
                            if (arg.Key == "On" && arg.Value.Value is string onValue)
                            {
                                triggerInfo.OnMethod = onValue;
                            }
                            else if (arg.Key == "Condition" && arg.Value.Value is string conditionValue)
                            {
                                triggerInfo.Condition = conditionValue;
                            }
                        }

                        if (!string.IsNullOrEmpty(triggerInfo.OnMethod))
                        {
                            if (!result.ContainsKey(triggerInfo.OnMethod))
                                result[triggerInfo.OnMethod] = new List<TriggerInfo>();

                            // Avoid duplicates (same trigger might be found on interface and implementation)
                            if (!result[triggerInfo.OnMethod].Any(t => t.TriggerMethodName == triggerInfo.TriggerMethodName))
                            {
                                result[triggerInfo.OnMethod].Add(triggerInfo);
                            }
                        }
                    }
                }
            }
        }

        /// <summary>
        /// Generates code to collect triggers that should execute (evaluates conditions, does NOT execute).
        /// Returns the variable name containing the trigger list, or null if no triggers.
        /// 0.24.0+ Trigger entries are emitted as <c>ushort</c> ids from <c>GameMethodIds</c>
        /// so the provider's trigger loop dispatches via the same id-keyed jump table as the
        /// main call — no runtime alias-to-id lookup, no string allocation per trigger.
        /// </summary>
        private static string? GenerateTriggerCollection(StringBuilder sb, string methodName, Dictionary<string, List<TriggerInfo>> triggersByMethod, string indent,
            string interfaceName, string namespaceName)
        {
            if (!triggersByMethod.TryGetValue(methodName, out var triggers) || triggers.Count == 0)
                return null;

            sb.AppendLine($"{indent}// Collect triggers for {methodName}");
            sb.AppendLine($"{indent}var triggers = new List<ushort>();");

            foreach (var trigger in triggers)
            {
                var idConst = "global::" + namespaceName + ".Generated.GameMethodIds." +
                    SignatureHashGenerator.MakeMethodIdConstName(interfaceName, trigger.TriggerMethodAlias, trigger.TriggerMethodVersion);
                if (!string.IsNullOrEmpty(trigger.Condition))
                {
                    // Has condition - check it first
                    sb.AppendLine($"{indent}if (service.{trigger.Condition}())");
                    sb.AppendLine($"{indent}{{");
                    sb.AppendLine($"{indent}    triggers.Add({idConst});");
                    sb.AppendLine($"{indent}}}");
                }
                else
                {
                    // No condition - always execute
                    sb.AppendLine($"{indent}triggers.Add({idConst});");
                }
            }

            return "triggers";
        }

        /// <summary>
        /// Generates method call code and returns DispatchResult with triggers to execute.
        /// </summary>
        private static void GenerateMethodCallWithTriggers(StringBuilder sb, StringBuilder asyncTails, string symbol, MetaMethodInfo info, string methodName, string callArgs, string returnType, Dictionary<string, List<TriggerInfo>> triggersByMethod,
            string interfaceName, string namespaceName,
            DetectedSerializer serializer = DetectedSerializer.Generic, bool forcePersist = false,
            int deepStateCheck = 0, string? stateTypeFullName = null)
        {
            const string indent = "                    ";

            string forcePersistPart = forcePersist ? ", ForcePersist = true" : "";
            bool isTask = returnType == "System.Threading.Tasks.Task" || returnType == "Task";
            bool isTaskOfT = returnType.StartsWith("System.Threading.Tasks.Task<") || returnType.StartsWith("Task<");
            bool isVoid = returnType == "void";

            // 0.26.6+ Deep-state-check emit gating. When the method is annotated
            // [MetaMethod(DeepStateCheck = SnapshotTiming.X)] and we know the state type,
            // we wrap the impl call with a pre/post snapshot + CRC compare against
            // context.ClientDebug, then thread Debug onto DispatchResult.
            bool emitDsc = deepStateCheck != 0 && !string.IsNullOrEmpty(stateTypeFullName);
            string dsDebugPart = emitDsc ? ", Debug = _dsDebug" : "";

            if (isVoid)
            {
                if (emitDsc)
                {
                    EmitDeepStateCheckBlockOpen(sb, indent, deepStateCheck, stateTypeFullName!);
                    sb.AppendLine($"{indent}service.{methodName}({callArgs});");
                    EmitDeepStateCheckBlockPost(sb, indent, deepStateCheck);
                }
                else
                {
                    sb.AppendLine($"{indent}service.{methodName}({callArgs});");
                }
                var triggersVar = GenerateTriggerCollection(sb, methodName, triggersByMethod, indent, interfaceName, namespaceName);
                EmitSyncDispatchReturn(sb, indent, resultVar: null, returnType: null, triggersVar, forcePersistPart, dsDebugPart);
            }
            else if (isTask)
            {
                // async Task — sync-completion check, async tail fallback.
                sb.AppendLine($"{indent}{{");
                if (emitDsc)
                    EmitDeepStateCheckBlockOpen(sb, indent + "    ", deepStateCheck, stateTypeFullName!);
                sb.AppendLine($"{indent}    var __t = service.{methodName}({callArgs});");
                sb.AppendLine($"{indent}    if (__t.IsCompletedSuccessfully)");
                sb.AppendLine($"{indent}    {{");
                if (emitDsc)
                    EmitDeepStateCheckBlockPost(sb, indent + "        ", deepStateCheck);
                var triggersVar = GenerateTriggerCollection(sb, methodName, triggersByMethod, indent + "        ", interfaceName, namespaceName);
                EmitSyncDispatchReturn(sb, indent + "        ", resultVar: null, returnType: null, triggersVar, forcePersistPart, dsDebugPart);
                sb.AppendLine($"{indent}    }}");
                var tailName = AsyncTailName(info);
                // Async-tail path: deep-state-check is intentionally skipped for genuinely-suspending
                // calls (would require thread-state plumbing into the per-method tail). The async-tail
                // route is rare in practice; if a DeepStateCheck-annotated method goes async, the
                // server emits a compile-time warning so the user can decide.
                if (emitDsc)
                    sb.AppendLine($"{indent}    #warning SharedMeta: [MetaMethod(DeepStateCheck)] on async '{interfaceName}.{methodName}' — snapshot fires only when the impl completes synchronously. Convert to a sync return type for full coverage.");
                sb.AppendLine($"{indent}    return {tailName}(service, __t, serializer);");
                sb.AppendLine($"{indent}}}");
                EmitAsyncTail(asyncTails, symbol, info, methodName, triggersByMethod, interfaceName, namespaceName, taskGenericType: null, resultVar: null, forcePersistPart);
            }
            else if (isTaskOfT)
            {
                // async Task<T> — sync-completion check, async tail fallback.
                var taskGenericType = ExtractTaskGenericType(returnType);
                sb.AppendLine($"{indent}{{");
                if (emitDsc)
                    EmitDeepStateCheckBlockOpen(sb, indent + "    ", deepStateCheck, stateTypeFullName!);
                sb.AppendLine($"{indent}    var __t = service.{methodName}({callArgs});");
                sb.AppendLine($"{indent}    if (__t.IsCompletedSuccessfully)");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        var result = __t.Result;");
                if (emitDsc)
                    EmitDeepStateCheckBlockPost(sb, indent + "        ", deepStateCheck);
                var triggersVar = GenerateTriggerCollection(sb, methodName, triggersByMethod, indent + "        ", interfaceName, namespaceName);
                EmitSyncDispatchReturn(sb, indent + "        ", resultVar: "result", returnType: taskGenericType, triggersVar, forcePersistPart, dsDebugPart);
                sb.AppendLine($"{indent}    }}");
                var tailName = AsyncTailName(info);
                if (emitDsc)
                    sb.AppendLine($"{indent}    #warning SharedMeta: [MetaMethod(DeepStateCheck)] on async '{interfaceName}.{methodName}' — snapshot fires only when the impl completes synchronously. Convert to a sync return type for full coverage.");
                sb.AppendLine($"{indent}    return {tailName}(service, __t, serializer);");
                sb.AppendLine($"{indent}}}");
                EmitAsyncTail(asyncTails, symbol, info, methodName, triggersByMethod, interfaceName, namespaceName, taskGenericType, resultVar: "__result", forcePersistPart);
            }
            else
            {
                // Synchronous T return (e.g. int, MyDto). No Task wrapping.
                if (emitDsc)
                {
                    EmitDeepStateCheckBlockOpen(sb, indent, deepStateCheck, stateTypeFullName!);
                    sb.AppendLine($"{indent}var result = service.{methodName}({callArgs});");
                    EmitDeepStateCheckBlockPost(sb, indent, deepStateCheck);
                }
                else
                {
                    sb.AppendLine($"{indent}var result = service.{methodName}({callArgs});");
                }
                var triggersVar = GenerateTriggerCollection(sb, methodName, triggersByMethod, indent, interfaceName, namespaceName);
                EmitSyncDispatchReturn(sb, indent, resultVar: "result", returnType: returnType, triggersVar, forcePersistPart, dsDebugPart);
            }
        }

        /// <summary>
        /// 0.26.6+ Emit pre-dispatch part of deep-state-check: declare locals, capture client
        /// debug, and (if Before-flag set) snapshot State and seed _dsDebug on Before mismatch.
        /// </summary>
        private static void EmitDeepStateCheckBlockOpen(StringBuilder sb, string indent, int deepStateCheck, string stateTypeFullName)
        {
            sb.AppendLine($"{indent}var _dsCtxTyped = (global::SharedMeta.Core.MetaContext<{stateTypeFullName}>)context;");
            sb.AppendLine($"{indent}var _dsClientDebug = _dsCtxTyped.ClientDebug;");
            sb.AppendLine($"{indent}global::SharedMeta.Core.PayloadDebug? _dsDebug = null;");
            // 0.26.6+ Helper-call form so a breakpoint inside DeepStateHashing.CheckBefore/After
            // works for users debugging in Unity / IL2CPP where stepping into .g.cs is awkward.
            if ((deepStateCheck & 1) != 0)
            {
                sb.AppendLine($"{indent}_dsDebug = global::SharedMeta.Core.Diagnostics.DeepStateHashing.CheckBefore(serializer, _dsCtxTyped.State, _dsClientDebug);");
            }
        }

        /// <summary>
        /// 0.26.6+ Emit post-dispatch part of deep-state-check: invoke <c>CheckAfter</c> helper
        /// when (After-flag) is set AND no Before mismatch was already captured. Subsequent
        /// <c>EmitSyncDispatchReturn</c> picks up the resulting <c>_dsDebug</c>.
        /// </summary>
        private static void EmitDeepStateCheckBlockPost(StringBuilder sb, string indent, int deepStateCheck)
        {
            if ((deepStateCheck & 2) == 0) return;
            sb.AppendLine($"{indent}if (_dsDebug == null)");
            sb.AppendLine($"{indent}    _dsDebug = global::SharedMeta.Core.Diagnostics.DeepStateHashing.CheckAfter(serializer, _dsCtxTyped.State, _dsClientDebug);");
        }

        /// <summary>
        /// Emits the synchronous return statement for the sync fast-path, wrapping the
        /// DispatchResult in a sync-completed <see cref="ValueTask{T}"/> so the non-async outer
        /// <c>Dispatch</c> method skips any state-machine allocation.
        /// </summary>
        private static void EmitSyncDispatchReturn(StringBuilder sb, string indent, string? resultVar, string? returnType, string? triggersVar, string forcePersistPart, string dsDebugPart = "")
        {
            // Result serialization goes through Context.Serializer (GrainScopedSerializer);
            // BuildDispatchResultExpr fast-paths bool / int / void returns to the cached
            // DispatchResult tables (DispatchResult.True / False / Int / Void) when there
            // are no triggers + no ForcePersist, sidestepping the Pack call entirely.
            var expr = BuildDispatchResultExpr(resultVar, returnType, triggersVar, forcePersistPart, dsDebugPart);
            sb.AppendLine($"{indent}return new ValueTask<DispatchResult>({expr});");
        }

        /// <summary>
        /// Build the <c>DispatchResult</c> expression for a dispatcher return path. When the
        /// return type is <c>void</c>, <c>bool</c> or <c>int</c> (range [0, MaxCached)) AND
        /// the method has no triggers / no ForcePersist, returns the cached static instance
        /// directly. Otherwise falls back to constructing a fresh struct with
        /// <c>serializer.Pack(value)</c> (the regular per-call scratch write).
        /// </summary>
        private static string BuildDispatchResultExpr(string? resultVar, string? returnType, string? triggersVar, string forcePersistPart, string dsDebugPart = "")
        {
            string triggersPart = triggersVar != null ? $", TriggersToExecute = {triggersVar}.Count > 0 ? {triggersVar} : null" : "";
            // 0.26.6+ When deep-state-check is in play (dsDebugPart non-empty), we can't return
            // a cached static — the Debug field would be lost. Force fresh struct construction.
            bool canCacheStruct = triggersVar == null && string.IsNullOrEmpty(forcePersistPart) && string.IsNullOrEmpty(dsDebugPart);

            // Void / no-result
            if (resultVar == null)
            {
                return canCacheStruct
                    ? "DispatchResult.Void"
                    : $"new DispatchResult {{ ResultBytes = default{triggersPart}{forcePersistPart}{dsDebugPart} }}";
            }

            // bool fast-path
            if (returnType == "bool" || returnType == "System.Boolean" || returnType == "Boolean")
            {
                if (canCacheStruct)
                    return $"({resultVar} ? DispatchResult.True : DispatchResult.False)";
                return $"new DispatchResult {{ ResultBytes = ({resultVar} ? DispatchResult.True.ResultBytes : DispatchResult.False.ResultBytes){triggersPart}{forcePersistPart}{dsDebugPart} }}";
            }

            // int fast-path with range check; out-of-range falls back to Pack.
            if (returnType == "int" || returnType == "System.Int32" || returnType == "Int32")
            {
                if (canCacheStruct)
                    return $"((uint){resultVar} < (uint)DispatchResult.Int.Length ? DispatchResult.Int[{resultVar}] : new DispatchResult {{ ResultBytes = serializer.PackForExternalUsage({resultVar}) }})";
                return $"new DispatchResult {{ ResultBytes = ((uint){resultVar} < (uint)DispatchResult.Int.Length ? DispatchResult.Int[{resultVar}].ResultBytes : serializer.PackForExternalUsage({resultVar})){triggersPart}{forcePersistPart}{dsDebugPart} }}";
            }

            // Default: regular Pack.
            return $"new DispatchResult {{ ResultBytes = serializer.PackForExternalUsage({resultVar}){triggersPart}{forcePersistPart}{dsDebugPart} }}";
        }

        /// <summary>
        /// Name of the per-method async tail helper. Suffixed with the alias version so multi-version
        /// declarations sharing an alias each get a unique helper.
        /// </summary>
        private static string AsyncTailName(MetaMethodInfo info) => $"Await_{info.Alias}_v{info.Version}";

        /// <summary>
        /// Emits a private static async tail helper that awaits the pending Task / Task&lt;T&gt;
        /// returned by a service method that didn't complete synchronously, then constructs the
        /// same DispatchResult shape the sync fast-path would have. The trigger-collection block
        /// is duplicated here because trigger conditions are checked AFTER the user method
        /// returns — semantics must match the sync path.
        /// </summary>
        /// <param name="taskGenericType">Type T for Task&lt;T&gt;; <c>null</c> for plain Task.</param>
        /// <param name="resultBytesExpr">Expression producing serialized result bytes (uses <c>__result</c>
        ///   as the awaited value for Task&lt;T&gt;, or <c>"null"</c> for plain Task).</param>
        private static void EmitAsyncTail(StringBuilder asyncTails, string symbol, MetaMethodInfo info, string methodName,
            Dictionary<string, List<TriggerInfo>> triggersByMethod,
            string interfaceName, string namespaceName,
            string? taskGenericType, string? resultVar, string forcePersistPart)
        {
            var tailName = AsyncTailName(info);
            asyncTails.AppendLine();
            if (taskGenericType == null)
            {
                asyncTails.AppendLine($"        private static async System.Threading.Tasks.ValueTask<DispatchResult> {tailName}({symbol} service, System.Threading.Tasks.Task __t, IMetaSerializer serializer)");
                asyncTails.AppendLine("        {");
                asyncTails.AppendLine("            await __t;");
            }
            else
            {
                asyncTails.AppendLine($"        private static async System.Threading.Tasks.ValueTask<DispatchResult> {tailName}({symbol} service, System.Threading.Tasks.Task<{taskGenericType}> __t, IMetaSerializer serializer)");
                asyncTails.AppendLine("        {");
                asyncTails.AppendLine("            var __result = await __t;");
            }
            var triggersVar = GenerateTriggerCollection(asyncTails, methodName, triggersByMethod, "            ", interfaceName, namespaceName);

            // taskGenericType is the awaited T (null for plain Task → void-equivalent). Same
            // BuildDispatchResultExpr fast-path machinery as the sync return.
            var expr = BuildDispatchResultExpr(resultVar, taskGenericType, triggersVar, forcePersistPart);
            asyncTails.AppendLine($"            return {expr};");
            asyncTails.AppendLine("        }");
        }

        /// <summary>
        /// Strips the type argument out of <c>"Task&lt;T&gt;"</c> / <c>"System.Threading.Tasks.Task&lt;T&gt;"</c>.
        /// Returns <c>"object"</c> as a defensive fallback when the type cannot be parsed.
        /// </summary>
        private static string ExtractTaskGenericType(string returnType)
        {
            var lt = returnType.IndexOf('<');
            var gt = returnType.LastIndexOf('>');
            if (lt < 0 || gt <= lt) return "object";
            return returnType.Substring(lt + 1, gt - lt - 1).Trim();
        }

        /// <summary>
        /// Bag of parsed <c>[MetaMethod]</c> args used by the dispatcher emit (0.22.0+).
        /// </summary>
        private class MetaMethodInfo
        {
            public string Alias { get; set; } = "";
            public int Version { get; set; }
            public bool ForcePersist { get; set; }
            public bool GenerateClientApi { get; set; } = true;
            // 0.26.6+ SnapshotTiming bitmask (1 = Before, 2 = After, 3 = Both, 0 = None).
            // Parsed from [MetaMethod(DeepStateCheck = SnapshotTiming.X)]; drives per-case
            // emit of state pre/post snapshot + CRC compare against context.ClientDebug.
            public int DeepStateCheck { get; set; }
        }

        /// <summary>
        /// Read <c>[MetaMethod]</c> attribute args from the interface method declaration:
        /// <c>Alias</c> (default = method name), <c>Version</c> (default 0), <c>ForcePersist</c>,
        /// <c>GenerateClientApi</c>. Used by the dispatcher emit to group declarations sharing
        /// an alias and route by <c>(Alias, Version)</c>.
        /// </summary>
        private static MetaMethodInfo ReadMetaMethodInfo(MethodDeclarationSyntax method)
        {
            var info = new MetaMethodInfo { Alias = method.Identifier.Text };
            var metaMethod = method.AttributeLists.SelectMany(a => a.Attributes)
                .FirstOrDefault(a => a.Name.ToString().Contains("MetaMethod"));
            if (metaMethod?.ArgumentList == null) return info;

            foreach (var arg in metaMethod.ArgumentList.Arguments)
            {
                if (arg.NameEquals == null) continue;
                var name = arg.NameEquals.Name.Identifier.Text;
                switch (name)
                {
                    case "Alias":
                        if (arg.Expression is LiteralExpressionSyntax aliasLit)
                            info.Alias = aliasLit.Token.ValueText;
                        break;
                    case "Version":
                        if (arg.Expression is LiteralExpressionSyntax verLit && int.TryParse(verLit.Token.ValueText, out var v))
                            info.Version = v;
                        break;
                    case "ForcePersist":
                        if (arg.Expression is LiteralExpressionSyntax fpLit)
                            info.ForcePersist = fpLit.Token.ValueText == "true";
                        break;
                    case "GenerateClientApi":
                        if (arg.Expression is LiteralExpressionSyntax gaLit && gaLit.Token.ValueText == "false")
                            info.GenerateClientApi = false;
                        break;
                    case "DeepStateCheck":
                        if (arg.Expression is MemberAccessExpressionSyntax dscAccess)
                        {
                            info.DeepStateCheck = dscAccess.Name.Identifier.Text switch
                            {
                                "Before" => 1,
                                "After" => 2,
                                "Both" => 3,
                                _ => 0,
                            };
                        }
                        else if (arg.Expression is LiteralExpressionSyntax dscLit
                            && int.TryParse(dscLit.Token.ValueText, out var dscInt))
                        {
                            info.DeepStateCheck = dscInt & 3;
                        }
                        break;
                }
            }
            return info;
        }

        /// <summary>
        /// Emit a single method body inside a dispatcher case: the GenerateClientApi gate, argument
        /// unpacking (MemoryPack fast path or generic IPayloadReader with transformers), and the
        /// service call + trigger collection. Indentation matches an unconditional case body (was
        /// previously inlined under <c>case "{alias}":</c>); for multi-version aliases the caller
        /// wraps additional <c>case N:</c> + braces around this block, but the inner indentation
        /// remains the same — C# tolerates extra leading whitespace.
        /// </summary>
        private static void EmitMethodBody(StringBuilder sb, StringBuilder asyncTails, MethodDeclarationSyntax method, MetaMethodInfo info,
            string symbol, string namespaceName, Dictionary<string, List<TriggerInfo>> triggersByMethod, DetectedSerializer serializer, string? stateTypeFullName)
        {
            var methodName = method.Identifier.Text;
            var returnType = method.ReturnType.ToString();
            var paramCount = method.ParameterList.Parameters.Count;

            // 0.20.0 security gate (mirrored): see main switch comment for the rationale.
            if (!info.GenerateClientApi)
            {
                sb.AppendLine("                    if (context.IsClientCall)");
                sb.AppendLine($"                        throw new System.InvalidOperationException(\"Method '{symbol}.{info.Alias}' is not callable from clients\");");
            }

            if (paramCount > 0)
            {
                var hasTransformers = method.ParameterList.Parameters.Any(p =>
                {
                    var attrs = p.AttributeLists.SelectMany(a => a.Attributes).ToList();
                    return attrs.Any(a => a.Name.ToString().Contains("Transform"));
                });

                if (serializer == DetectedSerializer.MemoryPack && !hasTransformers)
                {
                    GenerateMemoryPackArgumentUnpacking(sb, method, out var argNames);
                    var callArgs = string.Join(", ", argNames);
                    GenerateMethodCallWithTriggers(sb, asyncTails, symbol, info, methodName, callArgs, returnType, triggersByMethod, symbol, namespaceName, serializer, info.ForcePersist, info.DeepStateCheck, stateTypeFullName);
                }
                else
                {
                    sb.AppendLine("                    using var reader = serializer.CreateReader(payload);");
                    var argNames = new List<string>();
                    foreach (var param in method.ParameterList.Parameters)
                    {
                        var paramType = param.Type!.ToString();
                        var paramName = param.Identifier.Text;
                        var paramAttrs = param.AttributeLists.SelectMany(a => a.Attributes).ToList();
                        var hasSkipTransform = paramAttrs.Any(a => a.Name.ToString().Contains("SkipTransform"));
                        var transformAttr = paramAttrs.FirstOrDefault(a =>
                            a.Name.ToString().Contains("Transform") && !a.Name.ToString().Contains("SkipTransform"));

                        if (hasSkipTransform)
                        {
                            sb.AppendLine($"                    var {paramName} = reader.Read<{paramType}>();");
                        }
                        else if (transformAttr != null && transformAttr.ArgumentList?.Arguments.Count > 0)
                        {
                            var transformerTypeArg = transformAttr.ArgumentList.Arguments.First();
                            if (transformerTypeArg.Expression is TypeOfExpressionSyntax typeOf)
                            {
                                var transformerTypeName = typeOf.Type.ToString();
                                sb.AppendLine($"                    // Unbox {paramName} using explicit {transformerTypeName}");
                                sb.AppendLine($"                    var boxedBytes_{paramName} = reader.Read<byte[]>();");
                                sb.AppendLine($"                    var simpleType_{paramName} = MetaContext.GetSimpleType(typeof({transformerTypeName}));");
                                sb.AppendLine($"                    var boxed_{paramName} = serializer.Unpack(simpleType_{paramName}, boxedBytes_{paramName});");
                                sb.AppendLine($"                    var {paramName} = ({paramType})context.UnboxValue(typeof({transformerTypeName}), boxed_{paramName}!);");
                            }
                            else
                            {
                                sb.AppendLine($"                    var {paramName} = reader.Read<{paramType}>();");
                            }
                        }
                        else
                        {
                            sb.AppendLine($"                    var {paramName} = context.ReadWithAutoUnbox<{paramType}>(reader, serializer);");
                        }
                        argNames.Add(paramName);
                    }
                    var callArgs = string.Join(", ", argNames);
                    GenerateMethodCallWithTriggers(sb, asyncTails, symbol, info, methodName, callArgs, returnType, triggersByMethod, symbol, namespaceName, serializer, info.ForcePersist, info.DeepStateCheck, stateTypeFullName);
                }
            }
            else
            {
                GenerateMethodCallWithTriggers(sb, asyncTails, symbol, info, methodName, "", returnType, triggersByMethod, symbol, namespaceName, serializer, info.ForcePersist);
            }
        }
    }
}
