using System.Text;
using System.Linq;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SharedMeta.Generator.Generators
{
    public static class ServerServiceWrapperGenerator
    {
        public static (string? Recorder, string? Replayer) Generate(InterfaceDeclarationSyntax node, INamedTypeSymbol symbol)
        {
            // Check for [ServerMetaService] attribute
            var attr = symbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.ServerMetaServiceAttribute");
            if (attr == null) return (null, null);

            var interfaceName = symbol.Name;
            var namespaceName = symbol.ContainingNamespace.ToDisplayString();

            // Remove leading 'I' for class names
            var baseName = interfaceName;
            if (baseName.StartsWith("I") && baseName.Length > 1 && char.IsUpper(baseName[1]))
            {
                baseName = baseName.Substring(1);
            }

            // Check if any method is async
            var methods = node.Members.OfType<MethodDeclarationSyntax>().ToList();
            var hasAsync = methods.Any(m => m.ReturnType.ToString().StartsWith("Task"));

            var recorderCode = GenerateRecorder(node, symbol, interfaceName, baseName, namespaceName, hasAsync);
            var replayerCode = GenerateReplayer(node, symbol, interfaceName, baseName, namespaceName, hasAsync);

            return (recorderCode, replayerCode);
        }

        /// <summary>
        /// Parse async return type. Returns (isAsync, innerType).
        /// Task -> (true, null), Task&lt;bool&gt; -> (true, "bool"), int -> (false, "int")
        /// </summary>
        private static (bool isAsync, string? innerType) ParseReturnType(string returnType)
        {
            if (returnType == "Task")
                return (true, null);

            var match = Regex.Match(returnType, @"^Task<(.+)>$");
            if (match.Success)
                return (true, match.Groups[1].Value);

            if (returnType == "void")
                return (false, null);

            return (false, returnType);
        }

        private static string GenerateRecorder(InterfaceDeclarationSyntax node, INamedTypeSymbol symbol,
            string interfaceName, string baseName, string namespaceName, bool hasAsync)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            if (hasAsync)
                sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using SharedMeta.Core;");
            sb.AppendLine($"namespace {namespaceName}.Server");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Server-side recorder wrapper for {interfaceName}.");
            sb.AppendLine($"    /// Executes real logic and writes results to context Writer.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public class {baseName}Recorder : {namespaceName}.{interfaceName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        private readonly {namespaceName}.{interfaceName} _real;");
            sb.AppendLine("        private readonly IServerRecordContext _context;");
            sb.AppendLine();
            sb.AppendLine($"        public {baseName}Recorder({namespaceName}.{interfaceName} real, IServerRecordContext context)");
            sb.AppendLine("        {");
            sb.AppendLine("            _real = real;");
            sb.AppendLine("            _context = context;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Generate methods
            var methods = node.Members.OfType<MethodDeclarationSyntax>().ToList();
            foreach (var method in methods)
            {
                GenerateRecorderMethod(sb, method, interfaceName);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void GenerateRecorderMethod(StringBuilder sb, MethodDeclarationSyntax method, string interfaceName)
        {
            var methodName = method.Identifier.Text;
            var returnType = method.ReturnType.ToString();
            var parameters = string.Join(", ", method.ParameterList.Parameters);
            var paramNames = string.Join(", ", method.ParameterList.Parameters.Select(p => p.Identifier.Text));

            var (isAsync, innerType) = ParseReturnType(returnType);

            if (isAsync)
            {
                sb.AppendLine($"        public async {returnType} {methodName}({parameters})");
                sb.AppendLine("        {");

                if (innerType == null)
                {
                    // Task (void async)
                    sb.AppendLine($"            await _real.{methodName}({paramNames});");
                    sb.AppendLine($"            if (_context.DebugEnabled) _context.WriteDebugInfo(\"{interfaceName}.{methodName}() -> void\");");
                }
                else
                {
                    // Task<T>
                    sb.AppendLine($"            var result = await _real.{methodName}({paramNames});");
                    sb.AppendLine($"            _context.Writer.Write(result);");
                    sb.AppendLine($"            if (_context.DebugEnabled) _context.WriteDebugInfo($\"{interfaceName}.{methodName}() -> {{result}}\");");
                    sb.AppendLine("            return result;");
                }
            }
            else
            {
                sb.AppendLine($"        public {returnType} {methodName}({parameters})");
                sb.AppendLine("        {");

                if (innerType == null)
                {
                    // void
                    sb.AppendLine($"            _real.{methodName}({paramNames});");
                    sb.AppendLine($"            if (_context.DebugEnabled) _context.WriteDebugInfo(\"{interfaceName}.{methodName}() -> void\");");
                }
                else
                {
                    // T
                    sb.AppendLine($"            var result = _real.{methodName}({paramNames});");
                    sb.AppendLine($"            _context.Writer.Write(result);");
                    sb.AppendLine($"            if (_context.DebugEnabled) _context.WriteDebugInfo($\"{interfaceName}.{methodName}() -> {{result}}\");");
                    sb.AppendLine("            return result;");
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static string GenerateReplayer(InterfaceDeclarationSyntax node, INamedTypeSymbol symbol,
            string interfaceName, string baseName, string namespaceName, bool hasAsync)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            if (hasAsync)
                sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using SharedMeta.Core;");
            sb.AppendLine($"namespace {namespaceName}.Client");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Client-side replayer wrapper for {interfaceName}.");
            sb.AppendLine($"    /// Reads pre-recorded results from context Reader.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public class {baseName}Replayer : {namespaceName}.{interfaceName}");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly IClientReplayContext _context;");
            sb.AppendLine();
            sb.AppendLine($"        public {baseName}Replayer(IClientReplayContext context)");
            sb.AppendLine("        {");
            sb.AppendLine("            _context = context;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Generate methods
            var methods = node.Members.OfType<MethodDeclarationSyntax>().ToList();
            foreach (var method in methods)
            {
                GenerateReplayerMethod(sb, method, interfaceName);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void GenerateReplayerMethod(StringBuilder sb, MethodDeclarationSyntax method, string interfaceName)
        {
            var methodName = method.Identifier.Text;
            var returnType = method.ReturnType.ToString();
            var parameters = string.Join(", ", method.ParameterList.Parameters);

            var (isAsync, innerType) = ParseReturnType(returnType);

            sb.AppendLine($"        public {returnType} {methodName}({parameters})");
            sb.AppendLine("        {");

            if (isAsync)
            {
                if (innerType == null)
                {
                    // Task (void async) - nothing to read
                    sb.AppendLine("            return Task.CompletedTask;");
                }
                else
                {
                    // Task<T> - read result and wrap in Task.FromResult
                    sb.AppendLine($"            var result = _context.Reader.Read<{innerType}>();");
                    sb.AppendLine("            return Task.FromResult(result);");
                }
            }
            else
            {
                if (innerType != null)
                {
                    // T - read result
                    sb.AppendLine($"            return _context.Reader.Read<{returnType}>();");
                }
                // void - nothing to read
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }
}
