using System.Collections.Generic;
using System.Text;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Generates AddXxxServices() extension methods for DI registration.
    /// Creates MetaServiceConfig registrations for IMetaServiceResolver.
    /// </summary>
    public static class ServiceRegistrationGenerator
    {
        public static string? Generate(InterfaceDeclarationSyntax node, INamedTypeSymbol symbol, Compilation? compilation = null)
        {
            // Check for [MetaService] attribute with state type
            var attr = symbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceAttribute");
            if (attr == null) return null;

            // Detect serializer so EntityReplayDispatcher's arg-unpacking matches the wire format
            // emitted by the corresponding ApiClient (raw MemoryPack vs length-prefixed envelope).
            var serializer = compilation != null
                ? Utilities.SerializerDetector.Detect(compilation)
                : Utilities.DetectedSerializer.Generic;

            // Get state type from attribute if available
            var stateTypeArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "StateType");
            string? stateTypeName = null;
            string? stateTypeFullName = null;

            if (stateTypeArg.Value.Value is INamedTypeSymbol stateType)
            {
                stateTypeName = stateType.Name;
                stateTypeFullName = stateType.ToDisplayString();
            }

            // If no state type in attribute, we can't generate registration.
            // The service registration will need to be done manually.
            // stateTypeName and stateTypeFullName are set together inside the `is INamedTypeSymbol`
            // branch above; checking both keeps the nullable analyzer happy at the call sites below.
            if (stateTypeName == null || stateTypeFullName == null)
            {
                return null;
            }

            // Get ConfigType from attribute
            string? configTypeFullName = null;
            var configTypeArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "ConfigType");
            if (!configTypeArg.Value.IsNull && configTypeArg.Value.Value is INamedTypeSymbol configType)
            {
                configTypeFullName = configType.ToDisplayString();
            }

            // Handle DefaultConfig = true. Tracked separately from configTypeFullName because
            // it gates the opt-in auto-default-StaticConfigProvider emission below — explicit
            // ConfigType = typeof(X) requires a user-registered provider, DefaultConfig = true
            // is the explicit "I'm OK with new TConfig() as fallback" opt-in.
            bool usesDefaultConfig = false;
            var defaultConfigArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "DefaultConfig");
            if (defaultConfigArg.Value.Value is true)
            {
                usesDefaultConfig = true;
                if (configTypeFullName == null && compilation != null)
                {
                    configTypeFullName = FindDefaultConfigType(compilation, symbol.ContainingNamespace);
                }
            }

            // 0.33.0+ [ServiceConfig] entries — independently-versioned configs, symmetric with
            // each other. Positional: declaration order = list index (after the legacy primary's
            // index 0 on the wire, when a legacy ConfigType is also declared).
            var serviceConfigAttrs = symbol.GetAttributes()
                .Where(a => a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.ServiceConfigAttribute")
                .Select(a => (a.ConstructorArguments.Length > 0 ? a.ConstructorArguments[0].Value as INamedTypeSymbol : null)?.ToDisplayString())
                .Where(t => t != null)
                .Select(t => t!)
                .ToList();

            var interfaceName = symbol.Name;
            var namespaceName = symbol.ContainingNamespace.ToDisplayString();

            // Remove leading 'I' for class names
            var baseName = interfaceName;
            if (baseName.StartsWith("I") && baseName.Length > 1 && char.IsUpper(baseName[1]))
            {
                baseName = baseName.Substring(1);
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using SharedMeta.Core;");
            sb.AppendLine("using SharedMeta.Core.Network;");
            sb.AppendLine("using SharedMeta.Core.Diagnostics;");
            sb.AppendLine("using SharedMeta.Core.Random;");
            sb.AppendLine("using SharedMeta.Core.Patch;");
            sb.AppendLine("using SharedMeta.Client;");
            sb.AppendLine($"using {namespaceName};");
            sb.AppendLine($"using {namespaceName}.Client;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}.DependencyInjection");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// DI registration extensions for {interfaceName}.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public static class {baseName}ServiceExtensions");
            sb.AppendLine("    {");
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Register {baseName}ApiClient with IMetaServiceResolver.");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public static TResolver Add{baseName}Services<TResolver>(this TResolver resolver) where TResolver : IMetaServiceResolver");
            sb.AppendLine("        {");
            sb.AppendLine($"            resolver.RegisterService<{baseName}ApiClient>(new MetaServiceConfig");
            sb.AppendLine("            {");
            EmitConfigBody(sb, node, baseName, stateTypeFullName, stateTypeName, configTypeFullName, interfaceName, namespaceName, serializer, serviceConfigAttrs);
            sb.AppendLine("            });");
            if (configTypeFullName != null && usesDefaultConfig)
            {
                // Auto-default-StaticConfigProvider is opt-in via [MetaService(DefaultConfig = true)].
                // The flag is the explicit "I am OK with new TConfig() as a fallback" contract —
                // for services that don't ask for it, MetaServiceResolver throws on first subscribe
                // when no provider is registered. This used to fire unconditionally for any
                // ConfigType, which silently substituted an empty default and hid wiring bugs.
                // TryRegister is non-clobbering — if the user already registered a custom provider
                // (e.g. DownloadingConfigProvider) via resolver.RegisterConfigProvider<TConfig>(...),
                // this call is a no-op.
                sb.AppendLine($"            resolver.TryRegisterConfigProvider<{configTypeFullName}>(new StaticConfigProvider<{configTypeFullName}>(new {configTypeFullName}()));");
            }
            sb.AppendLine("            return resolver;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Get MetaServiceConfig for {baseName}ApiClient.");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public static MetaServiceConfig Get{baseName}ServiceConfig()");
            sb.AppendLine("        {");
            sb.AppendLine($"            return new MetaServiceConfig");
            sb.AppendLine("            {");
            EmitConfigBody(sb, node, baseName, stateTypeFullName, stateTypeName, configTypeFullName, interfaceName, namespaceName, serializer, serviceConfigAttrs);
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitConfigBody(
            StringBuilder sb,
            InterfaceDeclarationSyntax node,
            string baseName,
            string stateTypeFullName,
            string stateTypeName,
            string? configTypeFullName,
            string interfaceName,
            string namespaceName,
            Utilities.DetectedSerializer serializer,
            List<string> serviceConfigTypeNames)
        {
            sb.AppendLine($"                ServiceName = \"{interfaceName}\",");
            sb.AppendLine($"                ApiClientType = typeof({baseName}ApiClient),");
            sb.AppendLine($"                StateType = typeof({stateTypeFullName}),");
            sb.AppendLine($"                LocalServiceType = typeof({baseName}),");
            if (configTypeFullName != null)
            {
                sb.AppendLine($"                ConfigType = typeof({configTypeFullName}),");
            }
            if (serviceConfigTypeNames.Count > 0)
            {
                var typeofList = string.Join(", ", serviceConfigTypeNames.Select(t => $"typeof({t})"));
                sb.AppendLine($"                ServiceConfigTypes = new System.Type[] {{ {typeofList} }},");
            }
            EmitMethodIds(sb, node, interfaceName, namespaceName);
            sb.AppendLine($"                ApiClientFactory = (network, serializer, stateContainer, modeProvider, diagnostics, crossResolver, optimisticRandom, config, namedRandoms, configResolver, serviceConfigs) =>");
            sb.AppendLine($"                    new {baseName}ApiClient(network, serializer, (EntityStateContainer<{stateTypeFullName}>)stateContainer, modeProvider, diagnostics, crossResolver, optimisticRandom, config, namedRandoms, configResolver, serviceConfigs),");
            sb.AppendLine($"                StateContainerFactory = state => new EntityStateContainer<{stateTypeFullName}>(({stateTypeFullName})state),");
            sb.AppendLine($"                PatchApplier = (state, patchBytes, ser) =>");
            sb.AppendLine($"                {{");
            sb.AppendLine($"                    var patch = ser.Unpack<PatchNode>(patchBytes);");
            sb.AppendLine($"                    {stateTypeFullName}PatchApplier.Apply(({stateTypeFullName})state, patch, ser);");
            sb.AppendLine($"                }},");
            EmitEntityReplayDispatcher(sb, node, baseName, interfaceName, stateTypeFullName, namespaceName, serializer);
            // 0.20.0: Client-side sibling factory. When user code calls Get{Iface}SiblingAsync()
            // or GetI{Iface}(self) on the client, the framework asks the resolver to produce
            // a transient impl bound to the calling client-side MetaContext. Typed cast — no
            // reflection. Returns a fresh impl every call (impls are stateless w.r.t. fields,
            // they read State/Random through Context).
            sb.AppendLine($"                ClientSiblingFactory = ctx =>");
            sb.AppendLine($"                    new {namespaceName}.{baseName}() {{ Context = (MetaContext<{stateTypeFullName}>)ctx }},");
            sb.AppendLine($"                StateRefresher = (apiClient, state, random, namedRandoms) =>");
            sb.AppendLine($"                    (({baseName}ApiClient)apiClient).RefreshState(({stateTypeFullName})state, random, namedRandoms)");
        }

        /// <summary>
        /// Generates the EntityReplayDispatcher lambda — invoked by MetaServiceResolver's
        /// entity-level broadcast handler when a foreign-service Optimistic / Server / etc.
        /// broadcast arrives for this service. Spins up a fresh impl instance, replays the
        /// method against the shared state container — same effect as the matching ApiClient's
        /// own DispatchServiceBroadcast replay path, but doesn't require the foreign ApiClient
        /// to be subscribed locally.
        /// Skips Query/Signal methods (no broadcasts).
        /// </summary>
        private static void EmitEntityReplayDispatcher(
            StringBuilder sb,
            InterfaceDeclarationSyntax node,
            string baseName,
            string interfaceName,
            string stateTypeFullName,
            string namespaceName,
            Utilities.DetectedSerializer serializer)
        {
            sb.AppendLine($"                EntityReplayDispatcher = (state, methodId, argsBytes, replayContext, callerId, serverTimeTicks, ser, optRandom, namedRandoms, cfg, crossResolver, serviceConfigs) =>");
            sb.AppendLine($"                {{");
            sb.AppendLine($"                    var ctx = new SharedMeta.Client.ClientMetaContext<{stateTypeFullName}>(({stateTypeFullName})state, ser);");
            sb.AppendLine($"                    ctx.CallerId = callerId;");
            sb.AppendLine($"                    ctx.ServerTimeTicks = serverTimeTicks;");
            sb.AppendLine($"                    ctx.BeginReplay(replayContext ?? System.Array.Empty<byte>());");
            sb.AppendLine($"                    ctx.Random = optRandom;");
            sb.AppendLine($"                    ctx.Config = cfg;");
            sb.AppendLine($"                    ctx.Configs = serviceConfigs;");
            sb.AppendLine($"                    ctx.ServerRandom = new SharedMeta.Core.Random.MetaRandomReplayer(ctx);");
            sb.AppendLine($"                    ctx.NamedRandoms = namedRandoms;");
            sb.AppendLine($"                    var prev = SharedMeta.Core.MetaContextAccessor.Current;");
            sb.AppendLine($"                    SharedMeta.Core.MetaContextAccessor.Current = ctx;");
            // Activate ChangeTracker so [Tracked] field setters fired during the replay
            // notify their per-state subscribers (Tracked{State}.OnChanged). Without this,
            // foreign-service replay would silently mutate state but UIs wired to Tracked
            // events wouldn't refresh — that's the gift-demo regression.
            sb.AppendLine($"                    var _tracker = SharedMeta.Core.Reactive.ChangeTracker.Activate();");
            sb.AppendLine($"                    try");
            sb.AppendLine($"                    {{");
            // 0.20.0: also set Context as instance field on the transient impl so it doesn't
            // depend on the AsyncLocal fallback in the impl partial's Context getter. Accessor
            // remains set for framework internals (signal/trigger dispatchers and the like).
            sb.AppendLine($"                        var svc = new {baseName}() {{ Context = ctx }};");
            sb.AppendLine($"#pragma warning disable CS1522 // empty switch block when all methods are Query/Signal");
            sb.AppendLine($"                        switch (methodId)");
            sb.AppendLine($"                        {{");

            // 0.22.0+: dedup by alias for multi-version coexistence. Lowest-versioned method
            // wins the case; higher versions emit a #warning explaining the routing limitation.
            // Replay/cross-entity sibling-bypass currently doesn't carry MethodVersion, so
            // routing higher versions would require additional wire-format work.
            var seenAliases = new HashSet<string>();
            var methodGroups = node.Members.OfType<MethodDeclarationSyntax>()
                .Where(m => !IsQueryOrSignalMethod(m))
                .GroupBy(m => SimplifiedApiClientGenerator.GetMethodAliasInternal(m))
                .Select(g => g.OrderBy(m => SimplifiedApiClientGenerator.GetMethodVersion(m)).ToList())
                .ToList();

            foreach (var group in methodGroups)
            {
                var method = group[0];  // lowest-versioned
                var methodName = method.Identifier.Text;
                var alias = GetMethodAlias(method, methodName);
                var paramCount = method.ParameterList.Parameters.Count;
                var returnType = method.ReturnType.ToString();
                bool isAsync = returnType.StartsWith("Task");
                bool isVoid = returnType == "void" || returnType == "Task";
                var methodVersion = SimplifiedApiClientGenerator.GetMethodVersion(method);

                if (group.Count > 1)
                {
                    var higherVersions = string.Join(", ", group.Skip(1).Select(m => $"v{SimplifiedApiClientGenerator.GetMethodVersion(m)}"));
                    sb.AppendLine($"#warning SharedMeta 0.22.0 limitation: alias \"{alias}\" has multiple versions ({higherVersions} besides v{methodVersion}). Sibling/replay invocation routes to v{methodVersion} only; per-version routing is a follow-up.");
                }

                var idConst = "global::" + namespaceName + ".Generated.GameMethodIds." +
                    SignatureHashGenerator.MakeMethodIdConstName(interfaceName, alias, methodVersion);
                sb.AppendLine($"                            case {idConst}:");
                sb.AppendLine($"                            {{");

                string callArgs;
                if (paramCount == 0)
                {
                    callArgs = "";
                }
                else if (serializer == Utilities.DetectedSerializer.MemoryPack)
                {
                    // Match the ApiClient's raw MemoryPack arg encoding (single-arg: direct
                    // Serialize<T>, multi-arg: concatenated Serialize<T,TBufferWriter>). The
                    // length-prefixed CreateReader path consumes the first value's bytes as a
                    // length header and produces garbage on raw MemoryPack input.
                    var argNames = new System.Collections.Generic.List<string>();
                    var ps = method.ParameterList.Parameters;
                    if (ps.Count == 1)
                    {
                        var paramType = ps[0].Type!.ToString();
                        var paramName = ps[0].Identifier.Text;
                        sb.AppendLine($"                                var {paramName} = global::MemoryPack.MemoryPackSerializer.Deserialize<{paramType}>(((System.ReadOnlySpan<byte>)argsBytes))!;");
                        argNames.Add(paramName);
                    }
                    else
                    {
                        sb.AppendLine($"                                var mpState_ = global::MemoryPack.MemoryPackReaderOptionalStatePool.Rent(null);");
                        sb.AppendLine($"                                var mpReader_ = new global::MemoryPack.MemoryPackReader(((System.ReadOnlySpan<byte>)argsBytes), mpState_);");
                        foreach (var param in ps)
                        {
                            var paramType = param.Type!.ToString();
                            var paramName = param.Identifier.Text;
                            sb.AppendLine($"                                var {paramName} = mpReader_.ReadValue<{paramType}>()!;");
                            argNames.Add(paramName);
                        }
                        sb.AppendLine($"                                mpReader_.Dispose();");
                    }
                    callArgs = string.Join(", ", argNames);
                }
                else
                {
                    sb.AppendLine($"                                using var rdr = ser.CreateReader(argsBytes);");
                    var argNames = new System.Collections.Generic.List<string>();
                    foreach (var param in method.ParameterList.Parameters)
                    {
                        var paramType = param.Type!.ToString();
                        var paramName = param.Identifier.Text;
                        sb.AppendLine($"                                var {paramName} = rdr.Read<{paramType}>()!;");
                        argNames.Add(paramName);
                    }
                    callArgs = string.Join(", ", argNames);
                }

                if (isVoid && !isAsync)
                {
                    sb.AppendLine($"                                svc.{methodName}({callArgs});");
                }
                else if (isVoid && isAsync)
                {
                    sb.AppendLine($"                                SharedMeta.Core.BroadcastValidator.EnsureSyncCompletion(svc.{methodName}({callArgs}), \"{baseName}\", \"{alias}\");");
                }
                else
                {
                    // Non-void return — ignore the result during replay (caller already saw it).
                    sb.AppendLine($"                                _ = svc.{methodName}({callArgs});");
                }

                sb.AppendLine($"                                break;");
                sb.AppendLine($"                            }}");
            }

            sb.AppendLine($"                        }}");
            sb.AppendLine($"#pragma warning restore CS1522");
            sb.AppendLine($"                        _tracker.FlushAndNotify();");
            sb.AppendLine($"                    }}");
            sb.AppendLine($"                    catch");
            sb.AppendLine($"                    {{");
            sb.AppendLine($"                        _tracker.Discard();");
            sb.AppendLine($"                        throw;");
            sb.AppendLine($"                    }}");
            sb.AppendLine($"                    finally");
            sb.AppendLine($"                    {{");
            sb.AppendLine($"                        ctx.EndReplay();");
            sb.AppendLine($"                        SharedMeta.Core.MetaContextAccessor.Current = prev;");
            sb.AppendLine($"                    }}");
            sb.AppendLine($"                }},");
        }

        /// <summary>
        /// Emits the MetaServiceConfig.MethodIds set — the client-local ids that this service
        /// owns. MetaServiceResolver uses this set to route inbound broadcasts: a broadcast
        /// whose MethodId is in some service's set is delivered to that service's ApiClient
        /// (or, for foreign services not subscribed locally, to its EntityReplayDispatcher).
        /// Query and Signal methods are excluded — they don't produce broadcasts.
        /// Multi-version groups list every version's id (alias collisions still apply at
        /// replay routing, but the set itself must be exhaustive for the broadcast filter).
        /// </summary>
        private static void EmitMethodIds(
            StringBuilder sb,
            InterfaceDeclarationSyntax node,
            string interfaceName,
            string namespaceName)
        {
            var methods = node.Members.OfType<MethodDeclarationSyntax>()
                .Where(m => !IsQueryOrSignalMethod(m))
                .ToList();

            if (methods.Count == 0)
            {
                return;
            }

            sb.AppendLine("                MethodIds = new ushort[]");
            sb.AppendLine("                {");
            foreach (var method in methods)
            {
                var alias = GetMethodAlias(method, method.Identifier.Text);
                var version = SimplifiedApiClientGenerator.GetMethodVersion(method);
                var idConst = "global::" + namespaceName + ".Generated.GameMethodIds." +
                    SignatureHashGenerator.MakeMethodIdConstName(interfaceName, alias, version);
                sb.AppendLine($"                    {idConst},");
            }
            sb.AppendLine("                },");
        }

        private static bool IsQueryOrSignalMethod(MethodDeclarationSyntax method)
        {
            foreach (var attrList in method.AttributeLists)
            {
                foreach (var attr in attrList.Attributes)
                {
                    if (!attr.Name.ToString().Contains("MetaMethod")) continue;
                    if (attr.ArgumentList == null) continue;
                    foreach (var arg in attr.ArgumentList.Arguments)
                    {
                        if (arg.NameEquals == null) continue;
                        var name = arg.NameEquals.Name.Identifier.Text;
                        var expr = arg.Expression.ToString();
                        // LocalQuery is a client-only no-RPC read: like Query/Signal it produces no
                        // broadcast and no client RPC registration, so it's excluded here too.
                        if (name == "Mode" && (expr.EndsWith(".Query") || expr.EndsWith(".Signal") || expr.EndsWith(".LocalQuery"))) return true;
                        if ((name == "Query" || name == "Signal") && expr == "true") return true;
                    }
                }
            }
            return false;
        }

        private static string GetMethodAlias(MethodDeclarationSyntax method, string defaultName)
        {
            foreach (var attrList in method.AttributeLists)
            {
                foreach (var attr in attrList.Attributes)
                {
                    if (!attr.Name.ToString().Contains("MetaMethod")) continue;
                    if (attr.ArgumentList == null) continue;
                    foreach (var arg in attr.ArgumentList.Arguments)
                    {
                        if (arg.NameEquals?.Name.Identifier.Text == "Alias" &&
                            arg.Expression is LiteralExpressionSyntax lit)
                        {
                            return lit.Token.ValueText;
                        }
                    }
                }
            }
            return defaultName;
        }

        private static string? FindDefaultConfigType(Compilation compilation, INamespaceSymbol serviceNamespace)
        {
            // Search for [MetaConfig(Default = true)] classes across the current compilation AND
            // referenced assemblies. Prior to 0.20.2 this only walked compilation.SyntaxTrees, so
            // a config class declared in a referenced project (typical layout: Models.csproj →
            // Services.csproj) returned null silently — the generator emitted MetaServiceConfig
            // without ConfigType, MetaServiceResolver.ResolveConfigAsync's
            // `if (config.ConfigType == null) return null;` short-circuited, Context.Config stayed
            // null, and user code NRE'd at the first Config.X access. Mirrors the cross-assembly
            // scanning convention used by ContextInjectionGenerator and ResultComparerScanner.
            //
            // Precedence: same-namespace-in-current > anywhere-in-current > same-namespace-in-refs
            //           > anywhere-in-refs. Workaround for users who want to short-circuit this:
            // explicit [MetaService(ConfigType = typeof(...), DefaultConfig = true)] bypasses
            // discovery entirely (handled at the call site, lines 44-48).
            var current = new List<INamedTypeSymbol>();
            CollectDefaultConfigCandidates(compilation.Assembly.GlobalNamespace, current);

            var sameNsCurrent = current.FirstOrDefault(c =>
                SymbolEqualityComparer.Default.Equals(c.ContainingNamespace, serviceNamespace));
            if (sameNsCurrent != null) return sameNsCurrent.ToDisplayString();
            if (current.Count > 0) return current[0].ToDisplayString();

            // Walk references — skip BCL / serialization runtime / Orleans only. Deliberately
            // do NOT skip `SharedMeta.*` here: a user's product project may legitimately live
            // under a `SharedMeta.*` namespace (test fixtures within this repo do exactly
            // that), and those framework assemblies don't carry `[MetaConfig]` types so the
            // namespace walk below returns empty for them at minor cost.
            var fromRefs = new List<INamedTypeSymbol>();
            foreach (var reference in compilation.References)
            {
                if (compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol asm) continue;
                var name = asm.Name;
                if (name.StartsWith("System") || name.StartsWith("Microsoft") ||
                    name.StartsWith("netstandard") || name == "mscorlib" ||
                    name.StartsWith("Orleans") || name == "MemoryPack" ||
                    name == "MemoryPack.Core" || name == "MessagePack" ||
                    name == "MessagePack.Annotations")
                    continue;

                CollectDefaultConfigCandidates(asm.GlobalNamespace, fromRefs);
            }

            var sameNsRef = fromRefs.FirstOrDefault(c =>
                SymbolEqualityComparer.Default.Equals(c.ContainingNamespace, serviceNamespace));
            if (sameNsRef != null) return sameNsRef.ToDisplayString();
            if (fromRefs.Count > 0) return fromRefs[0].ToDisplayString();

            return null;
        }

        private static void CollectDefaultConfigCandidates(INamespaceSymbol ns, List<INamedTypeSymbol> sink)
        {
            foreach (var type in ns.GetTypeMembers())
            {
                var metaConfigAttr = type.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaConfigAttribute");
                if (metaConfigAttr == null) continue;

                var defaultArg = metaConfigAttr.NamedArguments.FirstOrDefault(a => a.Key == "Default");
                if (defaultArg.Value.Value is true)
                    sink.Add(type);
            }
            foreach (var childNs in ns.GetNamespaceMembers())
                CollectDefaultConfigCandidates(childNs, sink);
        }
    }
}
