using System.Collections.Generic;
using System.Text;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Generates AddXxxServices() extension methods for DI registration.
    /// Creates MetaServiceConfig registrations for IMetaServiceResolver.
    /// </summary>
    public static class ServiceRegistrationGenerator
    {
        public static string? Generate(InterfaceDeclarationSyntax node, INamedTypeSymbol symbol, Compilation? compilation = null)
        {
            // Check for [MetaService] attribute with state type
            var attr = symbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceAttribute");
            if (attr == null) return null;

            // Get state type from attribute if available
            var stateTypeArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "StateType");
            string? stateTypeName = null;
            string? stateTypeFullName = null;

            if (stateTypeArg.Value.Value is INamedTypeSymbol stateType)
            {
                stateTypeName = stateType.Name;
                stateTypeFullName = stateType.ToDisplayString();
            }

            // If no state type in attribute, we can't generate registration.
            // The service registration will need to be done manually.
            // stateTypeName and stateTypeFullName are set together inside the `is INamedTypeSymbol`
            // branch above; checking both keeps the nullable analyzer happy at the call sites below.
            if (stateTypeName == null || stateTypeFullName == null)
            {
                return null;
            }

            // Get ConfigType from attribute
            string? configTypeFullName = null;
            var configTypeArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "ConfigType");
            if (!configTypeArg.Value.IsNull && configTypeArg.Value.Value is INamedTypeSymbol configType)
            {
                configTypeFullName = configType.ToDisplayString();
            }

            // Handle DefaultConfig = true. Tracked separately from configTypeFullName because
            // it gates the opt-in auto-default-StaticConfigProvider emission below — explicit
            // ConfigType = typeof(X) requires a user-registered provider, DefaultConfig = true
            // is the explicit "I'm OK with new TConfig() as fallback" opt-in.
            bool usesDefaultConfig = false;
            var defaultConfigArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "DefaultConfig");
            if (defaultConfigArg.Value.Value is true)
            {
                usesDefaultConfig = true;
                if (configTypeFullName == null && compilation != null)
                {
                    configTypeFullName = FindDefaultConfigType(compilation, symbol.ContainingNamespace);
                }
            }

            var interfaceName = symbol.Name;
            var namespaceName = symbol.ContainingNamespace.ToDisplayString();

            // Remove leading 'I' for class names
            var baseName = interfaceName;
            if (baseName.StartsWith("I") && baseName.Length > 1 && char.IsUpper(baseName[1]))
            {
                baseName = baseName.Substring(1);
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using SharedMeta.Core;");
            sb.AppendLine("using SharedMeta.Core.Network;");
            sb.AppendLine("using SharedMeta.Core.Diagnostics;");
            sb.AppendLine("using SharedMeta.Core.Random;");
            sb.AppendLine("using SharedMeta.Core.Patch;");
            sb.AppendLine("using SharedMeta.Client;");
            sb.AppendLine($"using {namespaceName};");
            sb.AppendLine($"using {namespaceName}.Client;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}.DependencyInjection");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// DI registration extensions for {interfaceName}.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public static class {baseName}ServiceExtensions");
            sb.AppendLine("    {");
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Register {baseName}ApiClient with IMetaServiceResolver.");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public static TResolver Add{baseName}Services<TResolver>(this TResolver resolver) where TResolver : IMetaServiceResolver");
            sb.AppendLine("        {");
            sb.AppendLine($"            resolver.RegisterService<{baseName}ApiClient>(new MetaServiceConfig");
            sb.AppendLine("            {");
            EmitConfigBody(sb, node, baseName, stateTypeFullName, stateTypeName, configTypeFullName, interfaceName, namespaceName);
            sb.AppendLine("            });");
            if (configTypeFullName != null && usesDefaultConfig)
            {
                // Auto-default-StaticConfigProvider is opt-in via [MetaService(DefaultConfig = true)].
                // The flag is the explicit "I am OK with new TConfig() as a fallback" contract —
                // for services that don't ask for it, MetaServiceResolver throws on first subscribe
                // when no provider is registered. This used to fire unconditionally for any
                // ConfigType, which silently substituted an empty default and hid wiring bugs.
                // TryRegister is non-clobbering — if the user already registered a custom provider
                // (e.g. DownloadingConfigProvider) via resolver.RegisterConfigProvider<TConfig>(...),
                // this call is a no-op.
                sb.AppendLine($"            resolver.TryRegisterConfigProvider<{configTypeFullName}>(new StaticConfigProvider<{configTypeFullName}>(new {configTypeFullName}()));");
            }
            sb.AppendLine("            return resolver;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Get MetaServiceConfig for {baseName}ApiClient.");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public static MetaServiceConfig Get{baseName}ServiceConfig()");
            sb.AppendLine("        {");
            sb.AppendLine($"            return new MetaServiceConfig");
            sb.AppendLine("            {");
            EmitConfigBody(sb, node, baseName, stateTypeFullName, stateTypeName, configTypeFullName, interfaceName, namespaceName);
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitConfigBody(
            StringBuilder sb,
            InterfaceDeclarationSyntax node,
            string baseName,
            string stateTypeFullName,
            string stateTypeName,
            string? configTypeFullName,
            string interfaceName,
            string namespaceName)
        {
            sb.AppendLine($"                ServiceName = \"{interfaceName}\",");
            sb.AppendLine($"                ApiClientType = typeof({baseName}ApiClient),");
            sb.AppendLine($"                StateType = typeof({stateTypeFullName}),");
            sb.AppendLine($"                LocalServiceType = typeof({baseName}),");
            if (configTypeFullName != null)
            {
                sb.AppendLine($"                ConfigType = typeof({configTypeFullName}),");
            }
            sb.AppendLine($"                ApiClientFactory = (network, serializer, stateContainer, modeProvider, diagnostics, crossResolver, optimisticRandom, config, namedRandoms) =>");
            sb.AppendLine($"                    new {baseName}ApiClient(network, serializer, (EntityStateContainer<{stateTypeFullName}>)stateContainer, modeProvider, diagnostics, crossResolver, optimisticRandom, config, namedRandoms),");
            sb.AppendLine($"                StateContainerFactory = state => new EntityStateContainer<{stateTypeFullName}>(({stateTypeFullName})state),");
            sb.AppendLine($"                PatchApplier = (state, patchBytes, ser) =>");
            sb.AppendLine($"                {{");
            sb.AppendLine($"                    var patch = ser.Unpack<PatchNode>(patchBytes);");
            sb.AppendLine($"                    {stateTypeFullName}PatchApplier.Apply(({stateTypeFullName})state, patch, ser);");
            sb.AppendLine($"                }},");
            EmitEntityReplayDispatcher(sb, node, baseName, stateTypeFullName, namespaceName);
            // 0.20.0: Client-side sibling factory. When user code calls Get{Iface}SiblingAsync()
            // or GetI{Iface}(self) on the client, the framework asks the resolver to produce
            // a transient impl bound to the calling client-side MetaContext. Typed cast — no
            // reflection. Returns a fresh impl every call (impls are stateless w.r.t. fields,
            // they read State/Random through Context).
            sb.AppendLine($"                ClientSiblingFactory = ctx =>");
            sb.AppendLine($"                    new {namespaceName}.{baseName}() {{ Context = (MetaContext<{stateTypeFullName}>)ctx }},");
            sb.AppendLine($"                StateRefresher = (apiClient, state, random, namedRandoms) =>");
            sb.AppendLine($"                    (({baseName}ApiClient)apiClient).RefreshState(({stateTypeFullName})state, random, namedRandoms)");
        }

        /// <summary>
        /// Generates the EntityReplayDispatcher lambda — invoked by MetaServiceResolver's
        /// entity-level broadcast handler when a foreign-service Optimistic / Server / etc.
        /// broadcast arrives for this service. Spins up a fresh impl instance, replays the
        /// method against the shared state container — same effect as the matching ApiClient's
        /// own DispatchServiceBroadcast replay path, but doesn't require the foreign ApiClient
        /// to be subscribed locally.
        /// Skips Query/Signal methods (no broadcasts).
        /// </summary>
        private static void EmitEntityReplayDispatcher(
            StringBuilder sb,
            InterfaceDeclarationSyntax node,
            string baseName,
            string stateTypeFullName,
            string namespaceName)
        {
            sb.AppendLine($"                EntityReplayDispatcher = (state, methodName, argsBytes, replayContext, callerId, serverTimeTicks, ser, optRandom, namedRandoms, cfg, crossResolver) =>");
            sb.AppendLine($"                {{");
            sb.AppendLine($"                    var ctx = new SharedMeta.Client.ClientMetaContext<{stateTypeFullName}>(({stateTypeFullName})state, ser);");
            sb.AppendLine($"                    ctx.CallerId = callerId;");
            sb.AppendLine($"                    ctx.ServerTimeTicks = serverTimeTicks;");
            sb.AppendLine($"                    ctx.BeginReplay(replayContext ?? System.Array.Empty<byte>());");
            sb.AppendLine($"                    ctx.Random = optRandom;");
            sb.AppendLine($"                    ctx.Config = cfg;");
            sb.AppendLine($"                    ctx.ServerRandom = new SharedMeta.Core.Random.MetaRandomReplayer(ctx);");
            sb.AppendLine($"                    ctx.NamedRandoms = namedRandoms;");
            sb.AppendLine($"                    var prev = SharedMeta.Core.MetaContextAccessor.Current;");
            sb.AppendLine($"                    SharedMeta.Core.MetaContextAccessor.Current = ctx;");
            // Activate ChangeTracker so [Tracked] field setters fired during the replay
            // notify their per-state subscribers (Tracked{State}.OnChanged). Without this,
            // foreign-service replay would silently mutate state but UIs wired to Tracked
            // events wouldn't refresh — that's the gift-demo regression.
            sb.AppendLine($"                    var _tracker = SharedMeta.Core.Reactive.ChangeTracker.Activate();");
            sb.AppendLine($"                    try");
            sb.AppendLine($"                    {{");
            // 0.20.0: also set Context as instance field on the transient impl so it doesn't
            // depend on the AsyncLocal fallback in the impl partial's Context getter. Accessor
            // remains set for framework internals (signal/trigger dispatchers and the like).
            sb.AppendLine($"                        var svc = new {baseName}() {{ Context = ctx }};");
            sb.AppendLine($"#pragma warning disable CS1522 // empty switch block when all methods are Query/Signal");
            sb.AppendLine($"                        switch (methodName)");
            sb.AppendLine($"                        {{");

            foreach (var member in node.Members)
            {
                if (member is not MethodDeclarationSyntax method) continue;
                if (IsQueryOrSignalMethod(method)) continue;

                var methodName = method.Identifier.Text;
                var alias = GetMethodAlias(method, methodName);
                var paramCount = method.ParameterList.Parameters.Count;
                var returnType = method.ReturnType.ToString();
                bool isAsync = returnType.StartsWith("Task");
                bool isVoid = returnType == "void" || returnType == "Task";

                sb.AppendLine($"                            case \"{alias}\":");
                sb.AppendLine($"                            {{");

                string callArgs;
                if (paramCount == 0)
                {
                    callArgs = "";
                }
                else
                {
                    // Args are written via _serializer.CreateWriter().Write(...) (length-prefixed
                    // payload format), so the matching read path is CreateReader().Read<T>().
                    // Direct ser.Unpack<T>(argsBytes) would consume the length prefix as data.
                    sb.AppendLine($"                                using var rdr = ser.CreateReader(argsBytes);");
                    var argNames = new System.Collections.Generic.List<string>();
                    foreach (var param in method.ParameterList.Parameters)
                    {
                        var paramType = param.Type!.ToString();
                        var paramName = param.Identifier.Text;
                        sb.AppendLine($"                                var {paramName} = rdr.Read<{paramType}>()!;");
                        argNames.Add(paramName);
                    }
                    callArgs = string.Join(", ", argNames);
                }

                if (isVoid && !isAsync)
                {
                    sb.AppendLine($"                                svc.{methodName}({callArgs});");
                }
                else if (isVoid && isAsync)
                {
                    sb.AppendLine($"                                SharedMeta.Core.BroadcastValidator.EnsureSyncCompletion(svc.{methodName}({callArgs}), \"{baseName}\", \"{alias}\");");
                }
                else
                {
                    // Non-void return — ignore the result during replay (caller already saw it).
                    sb.AppendLine($"                                _ = svc.{methodName}({callArgs});");
                }

                sb.AppendLine($"                                break;");
                sb.AppendLine($"                            }}");
            }

            sb.AppendLine($"                        }}");
            sb.AppendLine($"#pragma warning restore CS1522");
            sb.AppendLine($"                        _tracker.FlushAndNotify();");
            sb.AppendLine($"                    }}");
            sb.AppendLine($"                    catch");
            sb.AppendLine($"                    {{");
            sb.AppendLine($"                        _tracker.Discard();");
            sb.AppendLine($"                        throw;");
            sb.AppendLine($"                    }}");
            sb.AppendLine($"                    finally");
            sb.AppendLine($"                    {{");
            sb.AppendLine($"                        ctx.EndReplay();");
            sb.AppendLine($"                        SharedMeta.Core.MetaContextAccessor.Current = prev;");
            sb.AppendLine($"                    }}");
            sb.AppendLine($"                }},");
        }

        private static bool IsQueryOrSignalMethod(MethodDeclarationSyntax method)
        {
            foreach (var attrList in method.AttributeLists)
            {
                foreach (var attr in attrList.Attributes)
                {
                    if (!attr.Name.ToString().Contains("MetaMethod")) continue;
                    if (attr.ArgumentList == null) continue;
                    foreach (var arg in attr.ArgumentList.Arguments)
                    {
                        if (arg.NameEquals == null) continue;
                        var name = arg.NameEquals.Name.Identifier.Text;
                        var expr = arg.Expression.ToString();
                        if (name == "Mode" && (expr.EndsWith(".Query") || expr.EndsWith(".Signal"))) return true;
                        if ((name == "Query" || name == "Signal") && expr == "true") return true;
                    }
                }
            }
            return false;
        }

        private static string GetMethodAlias(MethodDeclarationSyntax method, string defaultName)
        {
            foreach (var attrList in method.AttributeLists)
            {
                foreach (var attr in attrList.Attributes)
                {
                    if (!attr.Name.ToString().Contains("MetaMethod")) continue;
                    if (attr.ArgumentList == null) continue;
                    foreach (var arg in attr.ArgumentList.Arguments)
                    {
                        if (arg.NameEquals?.Name.Identifier.Text == "Alias" &&
                            arg.Expression is LiteralExpressionSyntax lit)
                        {
                            return lit.Token.ValueText;
                        }
                    }
                }
            }
            return defaultName;
        }

        private static string? FindDefaultConfigType(Compilation compilation, INamespaceSymbol serviceNamespace)
        {
            // Search for [MetaConfig(Default = true)] classes in the same namespace first, then globally
            var candidates = new List<INamedTypeSymbol>();

            foreach (var tree in compilation.SyntaxTrees)
            {
                var model = compilation.GetSemanticModel(tree);
                var root = tree.GetRoot();
                foreach (var classDecl in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
                {
                    var classSymbol = model.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                    if (classSymbol == null) continue;

                    var metaConfigAttr = classSymbol.GetAttributes().FirstOrDefault(a =>
                        a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaConfigAttribute");
                    if (metaConfigAttr == null) continue;

                    var defaultArg = metaConfigAttr.NamedArguments.FirstOrDefault(a => a.Key == "Default");
                    if (defaultArg.Value.Value is true)
                    {
                        candidates.Add(classSymbol);
                    }
                }
            }

            if (candidates.Count == 0) return null;

            // Prefer same namespace
            var sameNs = candidates.FirstOrDefault(c =>
                SymbolEqualityComparer.Default.Equals(c.ContainingNamespace, serviceNamespace));
            if (sameNs != null) return sameNs.ToDisplayString();

            return candidates[0].ToDisplayString();
        }
    }
}
