using System.Text;
using System.Linq;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Generator for <c>[StatelessMetaService]</c> / <c>[StatelessMetaServiceImpl]</c> — services
    /// with no entity/state whose resolution only requires materializing a linked
    /// <c>[MetaConfig]</c>. Produces three kinds of output:
    /// <list type="bullet">
    /// <item><see cref="GenerateImplContext"/> — injects a typed <c>Config</c> property into the
    /// impl partial (the only member the impl gets).</item>
    /// <item><see cref="GenerateClientExtension"/> — <c>client.GetI{Iface}Async()</c> on
    /// <c>MetaClient</c>, resolving the config version via a non-entity RPC then materializing
    /// through the registered <c>IClientMetaConfigProvider&lt;TConfig&gt;</c> (Path 2).</item>
    /// <item><see cref="GenerateVersionSource"/> — server-side <c>GeneratedStatelessConfigVersionSource</c>
    /// consumed by the transport-level <c>ResolveStatelessConfigVersion</c> RPC.</item>
    /// </list>
    /// Path 1 (resolving a stateless service as a dependency from inside another
    /// <c>[MetaServiceImpl]</c>) is generated separately by
    /// <see cref="ContextInjectionGenerator.GenerateStatelessServiceGetter"/>.
    /// </summary>
    public static class StatelessServiceGenerator
    {
        public sealed class StatelessImplInfo
        {
            public string ImplFullName = "";
            public string ImplNamespace = "";
            public string ImplName = "";
            public string InterfaceFullName = "";
            public string InterfaceName = "";
            public string ConfigFullName = "";
            public string ConfigName = "";
        }

        /// <summary>
        /// Analyze a <c>[StatelessMetaServiceImpl(typeof(IThing))]</c> class. Returns the resolved
        /// info, or an error message when the impl/interface pair is malformed (missing
        /// ServiceInterface, or the interface lacks <c>[StatelessMetaService]</c>/ConfigType).
        /// </summary>
        public static (StatelessImplInfo? Info, string? Error) Analyze(INamedTypeSymbol implSymbol)
        {
            var attr = implSymbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.StatelessMetaServiceImplAttribute");
            if (attr == null || attr.ConstructorArguments.Length < 1) return (null, null);

            var ifaceSymbol = attr.ConstructorArguments[0].Value as INamedTypeSymbol;
            if (ifaceSymbol == null)
            {
                return (null, $"[StatelessMetaServiceImpl] on {implSymbol.ToDisplayString()} has no service interface argument.");
            }

            var svcAttr = ifaceSymbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.StatelessMetaServiceAttribute");
            if (svcAttr == null || svcAttr.ConstructorArguments.Length < 1)
            {
                return (null, $"{ifaceSymbol.ToDisplayString()} is used as a [StatelessMetaServiceImpl] target on {implSymbol.ToDisplayString()} but has no [StatelessMetaService(typeof(TConfig))] attribute.");
            }

            var configSymbol = svcAttr.ConstructorArguments[0].Value as INamedTypeSymbol;
            if (configSymbol == null)
            {
                return (null, $"[StatelessMetaService] on {ifaceSymbol.ToDisplayString()} has no ConfigType argument.");
            }

            return (new StatelessImplInfo
            {
                ImplFullName = implSymbol.ToDisplayString(),
                ImplNamespace = implSymbol.ContainingNamespace.ToDisplayString(),
                ImplName = implSymbol.Name,
                InterfaceFullName = ifaceSymbol.ToDisplayString(),
                InterfaceName = ifaceSymbol.Name,
                ConfigFullName = configSymbol.ToDisplayString(),
                ConfigName = configSymbol.Name,
            }, null);
        }

        /// <summary>
        /// Emits the impl partial's only injected member: a settable, typed <c>Config</c>
        /// property. No Context, no Random, no ServerTimeTicks, no dependencies — a stateless
        /// service is a pure function of (Config, method args) by design.
        /// </summary>
        public static string GenerateImplContext(StatelessImplInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine($"namespace {info.ImplNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {info.ImplName}");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>Resolved config for this call — set by the framework before invocation.</summary>");
            sb.AppendLine($"        public {info.ConfigFullName} Config {{ get; set; }} = default!;");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>
        /// Emits <c>client.GetI{Iface}Async()</c> on <see cref="SharedMeta.Client.MetaClient"/> —
        /// Path 2 (no entity subscribe). Safe to emit unconditionally: Shared projects already
        /// reference <c>SharedMeta.Client</c> (see <c>SimplifiedApiClientGenerator</c> output),
        /// so no <c>#if SHAREDMETA_SERVER</c>-style guard is needed here.
        /// </summary>
        public static string GenerateClientExtension(StatelessImplInfo info)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine($"namespace {info.ImplNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Client-side resolution for {info.InterfaceName} — no entity subscribe. Resolves the");
            sb.AppendLine($"    /// linked config version via a non-entity RPC, then materializes it through the");
            sb.AppendLine($"    /// registered IClientMetaConfigProvider&lt;{info.ConfigName}&gt;.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public static class {info.InterfaceName}StatelessClientExtensions");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static async Task<{info.InterfaceFullName}> Get{info.InterfaceName}Async(this SharedMeta.Client.MetaClient client)");
            sb.AppendLine("        {");
            sb.AppendLine("            var clientAppVersion = client.ClientAppVersion ?? throw new InvalidOperationException(\"MetaClient.ClientAppVersion must be set to resolve a StatelessMetaService.\");");
            sb.AppendLine($"            var resolved = await client.Connection.ResolveStatelessConfigVersionAsync(\"{info.ConfigName}\", clientAppVersion).ConfigureAwait(false);");
            sb.AppendLine("            if (!resolved.Success)");
            sb.AppendLine($"                throw new InvalidOperationException($\"Failed to resolve config version for {info.InterfaceName}: {{resolved.Error}}\");");
            sb.AppendLine("            if (!resolved.Found)");
            sb.AppendLine($"                throw new InvalidOperationException(\"No [StatelessMetaService] registered server-side for config '{info.ConfigName}'.\");");
            sb.AppendLine("            var version = new SharedMeta.Core.MetaConfigVersion(resolved.Major, resolved.Minor, resolved.Patch);");
            sb.AppendLine($"            var config = await client.Resolver.ResolveConfigAsync<{info.ConfigFullName}>(version).ConfigureAwait(false)");
            sb.AppendLine($"                ?? throw new InvalidOperationException(\"IClientMetaConfigProvider<{info.ConfigName}> returned null.\");");
            sb.AppendLine($"            return new {info.ImplFullName} {{ Config = config }};");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>
        /// Emits <c>GeneratedStatelessConfigVersionSource : IConfigVersionResolutionSource</c> —
        /// routes <c>(configTypeName, clientAppVersion)</c> to the matching
        /// <c>IMetaConfigProvider&lt;TConfig&gt;.ResolveForClient</c>, mirroring
        /// <c>ServerMetaConfigurationGenerator.GenerateConfigByteSource</c>'s shape.
        /// </summary>
        /// <param name="wrapped">
        /// True when emitted from the Shared-project source pipeline (guard with
        /// <c>#if SHAREDMETA_SERVER</c> so it compiles away on the client/Unity build). False for
        /// the Server-project assembly-scan pipeline, which emits the real, unwrapped version.
        /// </param>
        public static string GenerateVersionSource(string rootNamespace, List<StatelessImplInfo> infos, bool wrapped)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            if (wrapped) sb.AppendLine("#if SHAREDMETA_SERVER");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine($"namespace {rootNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated non-generic config-version source for [StatelessMetaService]. Pair with");
            sb.AppendLine("    /// the transport-level ResolveStatelessConfigVersion RPC — routes by configTypeName");
            sb.AppendLine("    /// at request time, no entity involved.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public sealed class GeneratedStatelessConfigVersionSource : SharedMeta.Server.Core.IConfigVersionResolutionSource");
            sb.AppendLine("    {");

            // Dedup by ConfigName — several stateless services may share one config type.
            var byConfig = infos
                .GroupBy(i => i.ConfigFullName)
                .Select(g => g.First())
                .ToList();

            if (byConfig.Count > 0)
            {
                foreach (var entry in byConfig)
                {
                    var fieldName = $"_{char.ToLower(entry.ConfigName[0])}{entry.ConfigName.Substring(1)}ConfigProvider";
                    sb.AppendLine($"        private readonly SharedMeta.Server.Core.IMetaConfigProvider<{entry.ConfigFullName}>? {fieldName};");
                }
                sb.AppendLine();

                sb.AppendLine("        public GeneratedStatelessConfigVersionSource(System.IServiceProvider sp)");
                sb.AppendLine("        {");
                foreach (var entry in byConfig)
                {
                    var fieldName = $"_{char.ToLower(entry.ConfigName[0])}{entry.ConfigName.Substring(1)}ConfigProvider";
                    sb.AppendLine($"            {fieldName} = sp.GetService<SharedMeta.Server.Core.IMetaConfigProvider<{entry.ConfigFullName}>>();");
                }
                sb.AppendLine("        }");
                sb.AppendLine();

                sb.AppendLine("        public SharedMeta.Core.MetaConfigVersion? ResolveVersion(string configTypeName, string clientAppVersion)");
                sb.AppendLine("        {");
                sb.AppendLine("            switch (configTypeName)");
                sb.AppendLine("            {");
                foreach (var entry in byConfig)
                {
                    var fieldName = $"_{char.ToLower(entry.ConfigName[0])}{entry.ConfigName.Substring(1)}ConfigProvider";
                    sb.AppendLine($"                case \"{entry.ConfigName}\":");
                    sb.AppendLine($"                case \"{entry.ConfigFullName}\":");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    if ({fieldName} == null) return null;");
                    sb.AppendLine($"                    var policyResolver = SharedMeta.Core.MetaConfigVersionResolver.ForType(typeof({entry.ConfigFullName}));");
                    sb.AppendLine($"                    return {fieldName}.ResolveForClient(clientAppVersion, policyResolver);");
                    sb.AppendLine("                }");
                }
                sb.AppendLine("                default: return null;");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
            }
            else
            {
                sb.AppendLine("        public GeneratedStatelessConfigVersionSource(System.IServiceProvider sp) { }");
                sb.AppendLine();
                sb.AppendLine("        public SharedMeta.Core.MetaConfigVersion? ResolveVersion(string configTypeName, string clientAppVersion) => null;");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Explicit host opt-in, mirroring AddMetaConfigPublicUrl's pattern: call from Program.cs");
            sb.AppendLine("    /// so MetaHub / HttpPolling can resolve [StatelessMetaService] config versions for");
            sb.AppendLine("    /// clients that never subscribe to any entity.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class GeneratedStatelessConfigVersionSourceExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedStatelessConfigVersionSource(this Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
            sb.AppendLine("        {");
            sb.AppendLine("            Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions");
            sb.AppendLine("                .TryAddSingleton<SharedMeta.Server.Core.IConfigVersionResolutionSource>(services, sp => new GeneratedStatelessConfigVersionSource(sp));");
            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            if (wrapped) sb.AppendLine("#endif");
            return sb.ToString();
        }
    }
}
