using System.Text;
using System.Linq;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Generates dispatcher for framework service subscriber interfaces.
    /// Routes events to subscriber methods and executes ServiceTrigger methods.
    /// </summary>
    public static class SubscriberDispatcherGenerator
    {
        /// <summary>
        /// Information about a subscriber interface implemented by the service.
        /// </summary>
        public class SubscriberInfo
        {
            public string InterfaceName { get; set; } = "";
            public List<SubscriberMethodInfo> Methods { get; set; } = new();
        }

        /// <summary>
        /// Information about a subscriber method.
        /// </summary>
        public class SubscriberMethodInfo
        {
            public string MethodName { get; set; } = "";
            public string EventTypeName { get; set; } = "";
        }

        /// <summary>
        /// Information about a ServiceTrigger.
        /// </summary>
        public class ServiceTriggerInfo
        {
            public string TriggerMethodName { get; set; } = "";
            public string SubscriberInterfaceName { get; set; } = "";
            public string OnMethod { get; set; } = "";
            public string? Condition { get; set; }
            public bool IsMetaMethod { get; set; }
            public string ServiceName { get; set; } = "";
        }

        /// <summary>
        /// Generate subscriber dispatcher for a service implementation class.
        /// </summary>
        public static string? Generate(ClassDeclarationSyntax classNode, INamedTypeSymbol classSymbol)
        {
            // Find subscriber interfaces
            var subscribers = new List<SubscriberInfo>();
            foreach (var iface in classSymbol.AllInterfaces)
            {
                // Skip the marker interface itself
                if (iface.Name == "IFrameworkServiceSubscriber")
                {
                    continue;
                }

                // Check if this interface extends IFrameworkServiceSubscriber
                var implementsMarker = iface.AllInterfaces.Any(i =>
                    i.ToDisplayString() == "SharedMeta.Core.IFrameworkServiceSubscriber" ||
                    i.Name == "IFrameworkServiceSubscriber");

                if (implementsMarker)
                {
                    var subscriberInfo = new SubscriberInfo
                    {
                        InterfaceName = iface.Name
                    };

                    foreach (var member in iface.GetMembers().OfType<IMethodSymbol>())
                    {
                        if (member.Parameters.Length == 1)
                        {
                            subscriberInfo.Methods.Add(new SubscriberMethodInfo
                            {
                                MethodName = member.Name,
                                EventTypeName = member.Parameters[0].Type.ToDisplayString()
                            });
                        }
                    }

                    if (subscriberInfo.Methods.Count > 0)
                    {
                        subscribers.Add(subscriberInfo);
                    }
                }
            }

            if (subscribers.Count == 0)
                return null;

            // Find ServiceTrigger attributes on class methods
            var serviceTriggers = CollectServiceTriggers(classSymbol);

            // Get service interface name for triggered MetaMethods
            var serviceAttr = classSymbol.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "MetaServiceImplAttribute");
            var serviceInterfaceName = "IUnknownService";
            if (serviceAttr != null && serviceAttr.ConstructorArguments.Length > 0)
            {
                var serviceType = serviceAttr.ConstructorArguments[0].Value as INamedTypeSymbol;
                if (serviceType != null)
                    serviceInterfaceName = serviceType.Name;
            }

            // Generate code
            var className = classSymbol.Name;
            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable CS1998, CS1522");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using SharedMeta.Core;");
            sb.AppendLine("using SharedMeta.Core.Framework;");
            sb.AppendLine($"using {namespaceName};");
            sb.AppendLine($"namespace {namespaceName}.Server");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Dispatcher for framework service events to {className}.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public static class {className}SubscriberDispatcher");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static List<(string serviceName, string methodName, byte[]? resultBytes)>? Dispatch(");
            sb.AppendLine($"            object serviceObj,");
            sb.AppendLine($"            string subscriberInterface,");
            sb.AppendLine($"            string methodName,");
            sb.AppendLine($"            byte[] eventData,");
            sb.AppendLine($"            IMetaSerializer serializer)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var service = ({className})serviceObj;");
            sb.AppendLine("            var triggeredMethods = new List<(string, string, byte[]?)>();");
            sb.AppendLine();
            sb.AppendLine("            switch (subscriberInterface)");
            sb.AppendLine("            {");

            foreach (var subscriber in subscribers)
            {
                sb.AppendLine($"                case \"{subscriber.InterfaceName}\":");
                sb.AppendLine("                {");
                sb.AppendLine("                    switch (methodName)");
                sb.AppendLine("                    {");

                foreach (var method in subscriber.Methods)
                {
                    sb.AppendLine($"                        case \"{method.MethodName}\":");
                    sb.AppendLine("                        {");
                    sb.AppendLine($"                            var @event = serializer.Unpack<{method.EventTypeName}>(eventData);");
                    sb.AppendLine($"                            service.{method.MethodName}(@event);");
                    sb.AppendLine();
                    sb.AppendLine($"                            // Broadcast subscriber method to clients for state sync");
                    sb.AppendLine($"                            triggeredMethods.Add((\"{subscriber.InterfaceName}\", \"{method.MethodName}\", eventData));");

                    // Check for ServiceTriggers
                    var triggers = serviceTriggers.Where(t =>
                        t.SubscriberInterfaceName == subscriber.InterfaceName &&
                        t.OnMethod == method.MethodName).ToList();

                    foreach (var trigger in triggers)
                    {
                        if (!string.IsNullOrEmpty(trigger.Condition))
                        {
                            sb.AppendLine($"                            // ServiceTrigger with condition");
                            sb.AppendLine($"                            if (service.{trigger.Condition}())");
                            sb.AppendLine("                            {");
                            sb.AppendLine($"                                service.{trigger.TriggerMethodName}();");
                            if (trigger.IsMetaMethod)
                            {
                                sb.AppendLine($"                                triggeredMethods.Add((\"{serviceInterfaceName}\", \"{trigger.TriggerMethodName}\", null));");
                            }
                            sb.AppendLine("                            }");
                        }
                        else
                        {
                            sb.AppendLine($"                            // ServiceTrigger (unconditional)");
                            sb.AppendLine($"                            service.{trigger.TriggerMethodName}();");
                            if (trigger.IsMetaMethod)
                            {
                                sb.AppendLine($"                            triggeredMethods.Add((\"{serviceInterfaceName}\", \"{trigger.TriggerMethodName}\", null));");
                            }
                        }
                    }

                    sb.AppendLine("                            break;");
                    sb.AppendLine("                        }");
                }

                sb.AppendLine("                    }");
                sb.AppendLine("                    break;");
                sb.AppendLine("                }");
            }

            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return triggeredMethods.Count > 0 ? triggeredMethods : null;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Generate SubscriberLocalInvoker for client-side replay
            GenerateSubscriberLocalInvoker(sb, className, subscribers);

            // Generate SubscriberEvents helper for API client integration
            GenerateSubscriberEvents(sb, className, subscribers);

            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Generate LocalInvoker for subscriber interface methods.
        /// Used on client to replay subscriber method calls.
        /// </summary>
        private static void GenerateSubscriberLocalInvoker(StringBuilder sb, string className, List<SubscriberInfo> subscribers)
        {
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// LocalInvoker for subscriber interface methods on {className}.");
            sb.AppendLine($"    /// Replays subscriber events on client to sync state.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public static class {className}SubscriberLocalInvoker");
            sb.AppendLine("    {");

            foreach (var subscriber in subscribers)
            {
                sb.AppendLine($"        /// <summary>");
                sb.AppendLine($"        /// Create LocalInvoker for {subscriber.InterfaceName}.");
                sb.AppendLine($"        /// </summary>");
                sb.AppendLine($"        public static LocalMethodInvoker Create{subscriber.InterfaceName}Invoker(Func<{subscriber.InterfaceName}> serviceFactory)");
                sb.AppendLine("        {");
                sb.AppendLine("            return (serviceName, methodName, argsBytes, serializer) =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                if (serviceName != \"{subscriber.InterfaceName}\") return;");
                sb.AppendLine();
                sb.AppendLine("                var service = serviceFactory();");
                sb.AppendLine();
                sb.AppendLine("                switch (methodName)");
                sb.AppendLine("                {");

                foreach (var method in subscriber.Methods)
                {
                    sb.AppendLine($"                    case \"{method.MethodName}\":");
                    sb.AppendLine("                    {");
                    sb.AppendLine($"                        var @event = serializer.Unpack<{method.EventTypeName}>(argsBytes);");
                    sb.AppendLine($"                        service.{method.MethodName}(@event);");
                    sb.AppendLine("                        break;");
                    sb.AppendLine("                    }");
                }

                sb.AppendLine("                }");
                sb.AppendLine("            };");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
        }

        /// <summary>
        /// Generate subscriber event hooks for API client integration.
        /// </summary>
        private static void GenerateSubscriberEvents(StringBuilder sb, string className, List<SubscriberInfo> subscribers)
        {
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Subscriber events for {className}.");
            sb.AppendLine($"    /// Subscribe to framework service events being replayed.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public class {className}SubscriberEvents");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly IMetaClient _client;");
            sb.AppendLine("        private readonly IMetaSerializer _serializer;");
            sb.AppendLine();

            // Generate event declarations
            foreach (var subscriber in subscribers)
            {
                foreach (var method in subscriber.Methods)
                {
                    var eventName = GetEventName(method.MethodName);
                    sb.AppendLine($"        /// <summary>Fired when {subscriber.InterfaceName}.{method.MethodName} is replayed.</summary>");
                    sb.AppendLine($"        public event Action<{method.EventTypeName}>? {eventName};");
                }
            }
            sb.AppendLine();

            // Constructor
            sb.AppendLine($"        public {className}SubscriberEvents(IMetaClient client, IMetaSerializer serializer)");
            sb.AppendLine("        {");
            sb.AppendLine("            _client = client;");
            sb.AppendLine("            _serializer = serializer;");
            sb.AppendLine();

            // Subscribe to method replays
            foreach (var subscriber in subscribers)
            {
                foreach (var method in subscriber.Methods)
                {
                    var eventName = GetEventName(method.MethodName);
                    sb.AppendLine($"            _client.OnMethodReplayed(\"{subscriber.InterfaceName}\", \"{method.MethodName}\", ctx =>");
                    sb.AppendLine("            {");
                    sb.AppendLine($"                var @event = _serializer.Unpack<{method.EventTypeName}>(ctx.ArgsBytes);");
                    sb.AppendLine($"                {eventName}?.Invoke(@event);");
                    sb.AppendLine("            });");
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// Generate event name, avoiding double "On" prefix.
        /// </summary>
        private static string GetEventName(string methodName)
        {
            if (methodName.StartsWith("On") && methodName.Length > 2 && char.IsUpper(methodName[2]))
            {
                return $"{methodName}_Replayed";
            }
            return $"On{methodName}_Replayed";
        }

        /// <summary>
        /// Collect ServiceTrigger attributes from the class.
        /// </summary>
        private static List<ServiceTriggerInfo> CollectServiceTriggers(INamedTypeSymbol classSymbol)
        {
            var result = new List<ServiceTriggerInfo>();

            foreach (var member in classSymbol.GetMembers().OfType<IMethodSymbol>())
            {
                foreach (var attr in member.GetAttributes())
                {
                    if (attr.AttributeClass?.Name == "ServiceTriggerAttribute")
                    {
                        var triggerInfo = new ServiceTriggerInfo
                        {
                            TriggerMethodName = member.Name
                        };

                        // Check if also has MetaMethod attribute
                        triggerInfo.IsMetaMethod = member.GetAttributes()
                            .Any(a => a.AttributeClass?.Name == "MetaMethodAttribute");

                        // Extract Service and Method properties
                        foreach (var arg in attr.NamedArguments)
                        {
                            if (arg.Key == "Service" && arg.Value.Value is INamedTypeSymbol serviceType)
                            {
                                triggerInfo.SubscriberInterfaceName = serviceType.Name;
                            }
                            else if (arg.Key == "Method" && arg.Value.Value is string methodValue)
                            {
                                triggerInfo.OnMethod = methodValue;
                            }
                            else if (arg.Key == "Condition" && arg.Value.Value is string conditionValue)
                            {
                                triggerInfo.Condition = conditionValue;
                            }
                        }

                        if (!string.IsNullOrEmpty(triggerInfo.SubscriberInterfaceName) &&
                            !string.IsNullOrEmpty(triggerInfo.OnMethod))
                        {
                            result.Add(triggerInfo);
                        }
                    }
                }
            }

            return result;
        }
    }
}
