using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Generates automatic TransformerRegistry registration code.
    /// Scans for classes implementing IArgumentTransformer or IStateArgumentTransformer
    /// and generates a static RegisterAll method with typed invokers.
    /// </summary>
    public static class TransformerRegistrationGenerator
    {
        /// <summary>
        /// Data about a transformer for code generation.
        /// </summary>
        public class TransformerInfo
        {
            public string TransformerFullName { get; set; } = "";
            public string ComplexTypeFullName { get; set; } = "";
            public string SimpleTypeFullName { get; set; } = "";
            public string? StateTypeFullName { get; set; } // null for stateless transformers
            public bool NoAutoRegister { get; set; }
            public bool IsStateAware => StateTypeFullName != null;
        }

        /// <summary>
        /// Analyze a class to determine if it's a transformer.
        /// </summary>
        public static TransformerInfo? Analyze(INamedTypeSymbol symbol)
        {
            // Find IArgumentTransformer<TComplex, TSimple> or IStateArgumentTransformer<TComplex, TSimple, TState>
            var stateInterface = symbol.AllInterfaces.FirstOrDefault(i =>
                i.IsGenericType &&
                i.ConstructedFrom.ToDisplayString().StartsWith("SharedMeta.Core.IStateArgumentTransformer<"));

            var simpleInterface = symbol.AllInterfaces.FirstOrDefault(i =>
                i.IsGenericType &&
                i.ConstructedFrom.ToDisplayString().StartsWith("SharedMeta.Core.IArgumentTransformer<"));

            INamedTypeSymbol? transformerInterface = stateInterface ?? simpleInterface;

            if (transformerInterface == null)
                return null;

            // Get type arguments
            var typeArgs = transformerInterface.TypeArguments.ToList();
            if (typeArgs.Count < 2)
                return null;

            var complexType = typeArgs[0];
            var simpleType = typeArgs[1];
            var stateType = stateInterface != null && typeArgs.Count >= 3 ? typeArgs[2] : null;

            // Check for [Transformer(NoAutoRegister = true)]
            var transformerAttr = symbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.TransformerAttribute");

            bool noAutoRegister = false;
            if (transformerAttr != null)
            {
                var noAutoRegisterArg = transformerAttr.NamedArguments
                    .FirstOrDefault(arg => arg.Key == "NoAutoRegister");
                if (noAutoRegisterArg.Value.Value is bool value)
                {
                    noAutoRegister = value;
                }
            }

            return new TransformerInfo
            {
                TransformerFullName = symbol.ToDisplayString(),
                ComplexTypeFullName = complexType.ToDisplayString(),
                SimpleTypeFullName = simpleType.ToDisplayString(),
                StateTypeFullName = stateType?.ToDisplayString(),
                NoAutoRegister = noAutoRegister
            };
        }

        /// <summary>
        /// Generate the TransformerRegistrations class for a namespace.
        /// Uses typed registration (no reflection at runtime).
        /// </summary>
        public static string Generate(string namespaceName, IEnumerable<TransformerInfo> transformers)
        {
            var activeTransformers = transformers.Where(t => !t.NoAutoRegister).ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using SharedMeta.Core;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Auto-generated transformer registrations.");
            sb.AppendLine("    /// Call RegisterAll to register all discovered transformers.");
            sb.AppendLine("    /// Uses typed invokers - no reflection at runtime.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class TransformerRegistrations");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Register all auto-discovered transformers with the registry.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static void RegisterAll(TransformerRegistry registry)");
            sb.AppendLine("        {");

            foreach (var transformer in activeTransformers)
            {
                if (transformer.IsStateAware)
                {
                    // State-aware: Register<TComplex, TSimple, TState, TTransformer>()
                    sb.AppendLine($"            registry.Register<{transformer.ComplexTypeFullName}, {transformer.SimpleTypeFullName}, {transformer.StateTypeFullName}, {transformer.TransformerFullName}>();");
                }
                else
                {
                    // Stateless: RegisterSimple<TComplex, TSimple, TTransformer>()
                    sb.AppendLine($"            registry.RegisterSimple<{transformer.ComplexTypeFullName}, {transformer.SimpleTypeFullName}, {transformer.TransformerFullName}>();");
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
