using System.Text;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SharedMeta.Generator.Generators
{
    /// <summary>
    /// Generates XApiClient classes that integrate with IMetaClient.
    /// Provides typed async methods with automatic local replay.
    /// Supports argument transformers (explicit and auto-discovery).
    /// Triggers are broadcast separately by the server, not executed inline in LocalInvoker.
    /// </summary>
    public static class XApiClientGenerator
    {
        public static string? Generate(InterfaceDeclarationSyntax node, INamedTypeSymbol symbol, Compilation? compilation = null)
        {
            // Check for [MetaService] attribute
            var attr = symbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "SharedMeta.Core.MetaServiceAttribute");
            if (attr == null) return null;

            var interfaceName = symbol.Name;
            var namespaceName = symbol.ContainingNamespace.ToDisplayString();

            // Remove leading 'I' for class names
            var baseName = interfaceName;
            if (baseName.StartsWith("I") && baseName.Length > 1 && char.IsUpper(baseName[1]))
            {
                baseName = baseName.Substring(1);
            }

            // Get state type from attribute
            var stateTypeArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "StateType");
            string? stateTypeName = null;
            if (!stateTypeArg.Value.IsNull && stateTypeArg.Value.Value is INamedTypeSymbol stateType)
            {
                stateTypeName = stateType.ToDisplayString();
            }

            if (stateTypeName == null)
            {
                // Infer from interface name: IProfileService -> ProfileState
                var inferBase = baseName;
                if (inferBase.EndsWith("Service"))
                    inferBase = inferBase.Substring(0, inferBase.Length - 7);
                stateTypeName = namespaceName + "." + inferBase + "State";
            }

            var methods = node.Members.OfType<MethodDeclarationSyntax>().ToList();

            // Get subscriber interfaces from attribute
            var subscriberInterfacesArg = attr.NamedArguments.FirstOrDefault(a => a.Key == "SubscriberInterfaces");
            var subscriberInterfaces = new System.Collections.Generic.List<SubscriberInterfaceInfo>();
            if (!subscriberInterfacesArg.Value.IsNull && subscriberInterfacesArg.Value.Values.Length > 0)
            {
                foreach (var val in subscriberInterfacesArg.Value.Values)
                {
                    if (val.Value is INamedTypeSymbol subscriberType)
                    {
                        var info = new SubscriberInterfaceInfo
                        {
                            Name = subscriberType.Name,
                            FullName = subscriberType.ToDisplayString()
                        };
                        // Get methods from subscriber interface
                        foreach (var member in subscriberType.GetMembers().OfType<IMethodSymbol>())
                        {
                            if (member.Parameters.Length == 1)
                            {
                                info.Methods.Add(new SubscriberMethodInfo
                                {
                                    MethodName = member.Name,
                                    EventTypeName = member.Parameters[0].Type.ToDisplayString()
                                });
                            }
                        }
                        if (info.Methods.Count > 0)
                        {
                            subscriberInterfaces.Add(info);
                        }
                    }
                }
            }

            // Check if any method needs transformation support (explicit or potential auto-discovery)
            // We now always include context to support auto-discovery at runtime
            bool needsContext = methods.Any(m =>
                m.ParameterList.Parameters.Any(p =>
                {
                    var attrs = p.AttributeLists.SelectMany(a => a.Attributes);
                    // Has explicit Transform
                    if (attrs.Any(a => a.Name.ToString().Contains("Transform") && !a.Name.ToString().Contains("SkipTransform")))
                        return true;
                    // No SkipTransform = potential auto-discovery candidate
                    if (!attrs.Any(a => a.Name.ToString().Contains("SkipTransform")))
                        return true;
                    return false;
                }));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable CS1998, CS1522");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using SharedMeta.Core;");
            sb.AppendLine($"namespace {namespaceName}.Client");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Async API client for {interfaceName}.");
            sb.AppendLine($"    /// Wraps IMetaClient with typed methods and local replay support.");
            sb.AppendLine($"    /// Supports Optimistic (local-first) and Server (server-first) execution modes.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public class {baseName}ApiClient");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly IMetaClient _client;");
            sb.AppendLine("        private readonly IMetaSerializer _serializer;");
            sb.AppendLine("        private readonly MetaContext _context;");
            sb.AppendLine($"        private readonly {namespaceName}.{interfaceName} _service;");
            sb.AppendLine($"        private const string ServiceName = \"{interfaceName}\";");
            sb.AppendLine();
            sb.AppendLine($"        /// <summary>Current entity state.</summary>");
            sb.AppendLine($"        public {stateTypeName} State => _client.GetState<{stateTypeName}>();");
            sb.AppendLine();

            // Generate replay events for each method
            sb.AppendLine("        // Events fired when methods are replayed from server broadcasts");
            foreach (var method in methods)
            {
                var methodName = method.Identifier.Text;
                var methodAlias = GetMethodAlias(method, methodName);
                var eventName = GetEventName(methodName);
                var paramCount = method.ParameterList.Parameters.Count;

                if (paramCount == 0)
                {
                    sb.AppendLine($"        public event Action? {eventName};");
                }
                else
                {
                    // Build args tuple type
                    var argTypes = method.ParameterList.Parameters.Select(p => p.Type!.ToString());
                    var argTypesStr = string.Join(", ", argTypes);
                    if (paramCount == 1)
                    {
                        sb.AppendLine($"        public event Action<{argTypesStr}>? {eventName};");
                    }
                    else
                    {
                        sb.AppendLine($"        public event Action<({argTypesStr})>? {eventName};");
                    }
                }
            }

            // Generate subscriber interface events
            if (subscriberInterfaces.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("        // Events from subscriber interfaces (ILobbySubscriber, etc.)");
                foreach (var subscriber in subscriberInterfaces)
                {
                    foreach (var method in subscriber.Methods)
                    {
                        var eventName = GetEventName(method.MethodName);
                        sb.AppendLine($"        public event Action<{method.EventTypeName}>? {eventName};");
                    }
                }
            }
            sb.AppendLine();

            // Constructor - requires service instance for direct local invocation
            sb.AppendLine($"        public {baseName}ApiClient(IMetaClient client, IMetaSerializer serializer, MetaContext context, {namespaceName}.{interfaceName} service)");
            sb.AppendLine("        {");
            sb.AppendLine("            _client = client;");
            sb.AppendLine("            _serializer = serializer;");
            sb.AppendLine("            _context = context;");
            sb.AppendLine("            _service = service;");
            sb.AppendLine();
            sb.AppendLine("            // Subscribe to method replays to fire events");
            foreach (var method in methods)
            {
                var methodName = method.Identifier.Text;
                var methodAlias = GetMethodAlias(method, methodName);
                var eventName = GetEventName(methodName);
                var paramCount = method.ParameterList.Parameters.Count;

                sb.AppendLine($"            _client.OnMethodReplayed(ServiceName, \"{methodAlias}\", ctx =>");
                sb.AppendLine("            {");
                if (paramCount == 0)
                {
                    sb.AppendLine($"                {eventName}?.Invoke();");
                }
                else
                {
                    // Deserialize args
                    sb.AppendLine("                using var reader = _serializer.CreateReader(ctx.ArgsBytes);");
                    var argNames = new System.Collections.Generic.List<string>();
                    foreach (var param in method.ParameterList.Parameters)
                    {
                        var paramType = param.Type!.ToString();
                        var paramName = param.Identifier.Text;
                        var paramAttrs = param.AttributeLists.SelectMany(a => a.Attributes).ToList();

                        var hasSkipTransform = paramAttrs.Any(a => a.Name.ToString().Contains("SkipTransform"));

                        if (hasSkipTransform)
                        {
                            sb.AppendLine($"                var {paramName} = reader.Read<{paramType}>();");
                        }
                        else
                        {
                            sb.AppendLine($"                var {paramName} = _context.ReadWithAutoUnbox<{paramType}>(reader, _serializer);");
                        }
                        argNames.Add(paramName);
                    }

                    if (paramCount == 1)
                    {
                        sb.AppendLine($"                {eventName}?.Invoke({argNames[0]});");
                    }
                    else
                    {
                        var argsStr = string.Join(", ", argNames);
                        sb.AppendLine($"                {eventName}?.Invoke(({argsStr}));");
                    }
                }
                sb.AppendLine("            });");
            }

            // Subscribe to subscriber interface method replays
            if (subscriberInterfaces.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("            // Subscribe to subscriber interface events");
                foreach (var subscriber in subscriberInterfaces)
                {
                    foreach (var method in subscriber.Methods)
                    {
                        var eventName = GetEventName(method.MethodName);
                        sb.AppendLine($"            _client.OnMethodReplayed(\"{subscriber.Name}\", \"{method.MethodName}\", ctx =>");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                var @event = _serializer.Unpack<{method.EventTypeName}>(ctx.ArgsBytes);");
                        sb.AppendLine($"                {eventName}?.Invoke(@event);");
                        sb.AppendLine("            });");
                    }
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine();

            // Generate methods
            foreach (var method in methods)
            {
                GenerateMethod(sb, method, interfaceName, namespaceName);
            }

            sb.AppendLine("    }");
            sb.AppendLine();

            // Generate LocalInvoker helper (triggers are broadcast separately, not executed inline)
            GenerateLocalInvoker(sb, methods, interfaceName, baseName, namespaceName);

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void GenerateMethod(StringBuilder sb, MethodDeclarationSyntax method,
            string interfaceName, string namespaceName)
        {
            var methodName = method.Identifier.Text;
            var returnType = method.ReturnType.ToString();
            var parameters = string.Join(", ", method.ParameterList.Parameters);
            var paramCount = method.ParameterList.Parameters.Count;

            // Parse MetaMethod attribute
            var methodAlias = methodName;
            var executionMode = "Optimistic"; // Default
            var skipServerOnFalse = false;

            var attributes = method.AttributeLists.SelectMany(a => a.Attributes);
            var metaMethod = attributes.FirstOrDefault(a => a.Name.ToString().Contains("MetaMethod"));
            if (metaMethod != null)
            {
                foreach (var arg in metaMethod.ArgumentList?.Arguments ?? Enumerable.Empty<AttributeArgumentSyntax>())
                {
                    if (arg.NameEquals != null)
                    {
                        var name = arg.NameEquals.Name.Identifier.Text;
                        if (name == "Alias" && arg.Expression is LiteralExpressionSyntax aliasLit)
                            methodAlias = aliasLit.Token.ValueText;
                        else if (name == "Mode" && arg.Expression is MemberAccessExpressionSyntax modeAccess)
                            executionMode = modeAccess.Name.Identifier.Text;
                        else if (name == "SkipServerOnFalse" && arg.Expression is LiteralExpressionSyntax skipLit)
                            skipServerOnFalse = skipLit.Token.ValueText == "true";
                    }
                }
            }

            // Determine async return type
            string asyncReturnType;
            bool isVoidReturn = returnType == "void";

            if (isVoidReturn)
            {
                asyncReturnType = "Task";
            }
            else if (returnType.StartsWith("Task"))
            {
                asyncReturnType = returnType;
            }
            else
            {
                asyncReturnType = $"Task<{returnType}>";
            }

            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Async call to {methodName}. Mode: {executionMode}.");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public {asyncReturnType} {methodName}Async({parameters})");
            sb.AppendLine("        {");

            // Build the argument list for direct service call
            var argNames = method.ParameterList.Parameters.Select(p => p.Identifier.Text).ToList();
            var callArgs = string.Join(", ", argNames);

            // Use lazy serialization for Optimistic + SkipServerOnFalse to avoid wasted work
            bool useLazySerialization = executionMode == "Optimistic" && skipServerOnFalse && paramCount > 0;

            // Generate serialization code (either inline or as lambda)
            if (useLazySerialization)
            {
                // Lazy serialization - defer until after local execution succeeds
                sb.AppendLine("            // Lazy serialization - only serialize if local execution succeeds");
                sb.AppendLine("            byte[] SerializeArgs()");
                sb.AppendLine("            {");
                if (paramCount == 0)
                {
                    sb.AppendLine("                return Array.Empty<byte>();");
                }
                else
                {
                    sb.AppendLine("                var writer = _serializer.CreateWriter();");
                    GenerateSerializationCode(sb, method, "                ");
                    sb.AppendLine("                return writer.Complete();");
                }
                sb.AppendLine("            }");
                sb.AppendLine();
            }
            else
            {
                // Eager serialization
                if (paramCount == 0)
                {
                    sb.AppendLine("            var argsBytes = Array.Empty<byte>();");
                }
                else
                {
                    sb.AppendLine("            var writer = _serializer.CreateWriter();");
                    GenerateSerializationCode(sb, method, "            ");
                    sb.AppendLine("            var argsBytes = writer.Complete();");
                }
                sb.AppendLine();
            }

            // Generate call based on execution mode
            if (executionMode == "Local")
            {
                // Local only - no server call
                if (isVoidReturn)
                {
                    sb.AppendLine($"            _service.{methodName}({callArgs});");
                    sb.AppendLine("            return Task.CompletedTask;");
                }
                else
                {
                    var resultType = returnType.StartsWith("Task<")
                        ? returnType.Substring(5, returnType.Length - 6)
                        : returnType;
                    sb.AppendLine($"            var result = _service.{methodName}({callArgs});");
                    sb.AppendLine($"            return Task.FromResult(result);");
                }
            }
            else if (executionMode == "Optimistic")
            {
                // Optimistic: local first, then server
                if (useLazySerialization)
                {
                    // Use lazy serialization variant
                    if (isVoidReturn)
                    {
                        sb.AppendLine($"            return _client.CallOptimisticLazyVoidAsync(");
                        sb.AppendLine($"                ServiceName, \"{methodAlias}\",");
                        sb.AppendLine($"                () => {{ _service.{methodName}({callArgs}); return null; }},");
                        sb.AppendLine($"                SerializeArgs,");
                        sb.AppendLine($"                true);");
                    }
                    else
                    {
                        var resultType = returnType.StartsWith("Task<")
                            ? returnType.Substring(5, returnType.Length - 6)
                            : returnType;
                        sb.AppendLine($"            return _client.CallOptimisticLazyAsync<{resultType}>(");
                        sb.AppendLine($"                ServiceName, \"{methodAlias}\",");
                        sb.AppendLine($"                () => _service.{methodName}({callArgs}),");
                        sb.AppendLine($"                SerializeArgs,");
                        sb.AppendLine($"                true);");
                    }
                }
                else
                {
                    // Use eager serialization variant
                    var skipStr = skipServerOnFalse ? "true" : "false";
                    if (isVoidReturn)
                    {
                        sb.AppendLine($"            return _client.CallOptimisticVoidAsync(");
                        sb.AppendLine($"                ServiceName, \"{methodAlias}\", argsBytes,");
                        sb.AppendLine($"                () => {{ _service.{methodName}({callArgs}); return null; }},");
                        sb.AppendLine($"                {skipStr});");
                    }
                    else
                    {
                        var resultType = returnType.StartsWith("Task<")
                            ? returnType.Substring(5, returnType.Length - 6)
                            : returnType;
                        sb.AppendLine($"            return _client.CallOptimisticAsync<{resultType}>(");
                        sb.AppendLine($"                ServiceName, \"{methodAlias}\", argsBytes,");
                        sb.AppendLine($"                () => _service.{methodName}({callArgs}),");
                        sb.AppendLine($"                {skipStr});");
                    }
                }
            }
            else
            {
                // Server mode: server first, then replay (current behavior)
                if (isVoidReturn)
                {
                    sb.AppendLine($"            return _client.CallVoidAsync(ServiceName, \"{methodAlias}\", argsBytes);");
                }
                else
                {
                    var resultType = returnType.StartsWith("Task<")
                        ? returnType.Substring(5, returnType.Length - 6)
                        : returnType;
                    sb.AppendLine($"            return _client.CallAsync<{resultType}>(ServiceName, \"{methodAlias}\", argsBytes);");
                }
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void GenerateSerializationCode(StringBuilder sb, MethodDeclarationSyntax method, string indent)
        {
            foreach (var param in method.ParameterList.Parameters)
            {
                var paramName = param.Identifier.Text;
                var paramType = param.Type!.ToString();
                var paramAttrs = param.AttributeLists.SelectMany(a => a.Attributes).ToList();

                var hasSkipTransform = paramAttrs.Any(a => a.Name.ToString().Contains("SkipTransform"));
                var transformAttr = paramAttrs.FirstOrDefault(a =>
                    a.Name.ToString().Contains("Transform") && !a.Name.ToString().Contains("SkipTransform"));

                if (hasSkipTransform)
                {
                    sb.AppendLine($"{indent}writer.Write({paramName});");
                }
                else if (transformAttr != null && transformAttr.ArgumentList?.Arguments.Count > 0)
                {
                    var transformerTypeArg = transformAttr.ArgumentList.Arguments.First();
                    if (transformerTypeArg.Expression is TypeOfExpressionSyntax typeOf)
                    {
                        var transformerTypeName = typeOf.Type.ToString();
                        sb.AppendLine($"{indent}var boxed_{paramName} = _context.BoxValue(typeof({transformerTypeName}), {paramName}!);");
                        sb.AppendLine($"{indent}var simpleType_{paramName} = MetaContext.GetSimpleType(typeof({transformerTypeName}));");
                        sb.AppendLine($"{indent}var boxedPayload_{paramName} = _serializer.Pack(simpleType_{paramName}, boxed_{paramName});");
                        sb.AppendLine($"{indent}writer.Write(boxedPayload_{paramName});");
                    }
                    else
                    {
                        sb.AppendLine($"{indent}writer.Write({paramName});");
                    }
                }
                else
                {
                    sb.AppendLine($"{indent}_context.WriteWithAutoBox(writer, {paramName}, _serializer);");
                }
            }
        }

        private static string GetMethodAlias(MethodDeclarationSyntax method, string defaultName)
        {
            var attributes = method.AttributeLists.SelectMany(a => a.Attributes);
            var metaMethod = attributes.FirstOrDefault(a => a.Name.ToString().Contains("MetaMethod"));
            if (metaMethod != null)
            {
                var aliasArg = metaMethod.ArgumentList?.Arguments
                    .FirstOrDefault(arg => arg.NameEquals != null && arg.NameEquals.Name.Identifier.Text == "Alias");
                if (aliasArg != null && aliasArg.Expression is LiteralExpressionSyntax literal)
                {
                    return literal.Token.ValueText;
                }
            }
            return defaultName;
        }

        /// <summary>
        /// Generate event name for a method, avoiding double "On" prefix.
        /// SetName -> OnSetName_Replayed
        /// OnMatchReady -> OnMatchReady_Replayed (not OnOnMatchReady_Replayed)
        /// </summary>
        private static string GetEventName(string methodName)
        {
            // If method already starts with "On", just append "_Replayed"
            if (methodName.StartsWith("On") && methodName.Length > 2 && char.IsUpper(methodName[2]))
            {
                return $"{methodName}_Replayed";
            }
            return $"On{methodName}_Replayed";
        }

        private static void GenerateLocalInvoker(StringBuilder sb, System.Collections.Generic.List<MethodDeclarationSyntax> methods,
            string interfaceName, string baseName, string namespaceName)
        {
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Helper to create LocalMethodInvoker for {interfaceName}.");
            sb.AppendLine($"    /// Triggers are broadcast separately by the server, not executed inline.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public static class {baseName}LocalInvoker");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static LocalMethodInvoker Create(Func<{namespaceName}.{interfaceName}> serviceFactory)");
            sb.AppendLine("        {");
            sb.AppendLine("            return (serviceName, methodName, argsBytes, serializer) =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                if (serviceName != \"{interfaceName}\") return;");
            sb.AppendLine();
            sb.AppendLine("                var context = MetaContextAccessor.Current ?? throw new InvalidOperationException(\"MetaContext not set for LocalInvoker.\");");
            sb.AppendLine("                var service = serviceFactory();");
            sb.AppendLine();
            sb.AppendLine("                switch (methodName)");
            sb.AppendLine("                {");

            foreach (var method in methods)
            {
                var methodName = method.Identifier.Text;
                var methodAlias = methodName;
                var attributes = method.AttributeLists.SelectMany(a => a.Attributes);
                var metaMethod = attributes.FirstOrDefault(a => a.Name.ToString().Contains("MetaMethod"));
                if (metaMethod != null)
                {
                    var aliasArg = metaMethod.ArgumentList?.Arguments
                        .FirstOrDefault(arg => arg.NameEquals != null && arg.NameEquals.Name.Identifier.Text == "Alias");
                    if (aliasArg != null && aliasArg.Expression is LiteralExpressionSyntax literal)
                    {
                        methodAlias = literal.Token.ValueText;
                    }
                }

                var paramCount = method.ParameterList.Parameters.Count;

                sb.AppendLine($"                    case \"{methodAlias}\":");
                sb.AppendLine($"                    {{");

                if (paramCount == 0)
                {
                    sb.AppendLine($"                        service.{methodName}();");
                }
                else
                {
                    sb.AppendLine($"                        using var reader = serializer.CreateReader(argsBytes);");

                    var argNames = new System.Collections.Generic.List<string>();
                    foreach (var param in method.ParameterList.Parameters)
                    {
                        var paramType = param.Type!.ToString();
                        var paramName = param.Identifier.Text;
                        var paramAttrs = param.AttributeLists.SelectMany(a => a.Attributes).ToList();

                        var hasSkipTransform = paramAttrs.Any(a => a.Name.ToString().Contains("SkipTransform"));
                        var transformAttr = paramAttrs.FirstOrDefault(a =>
                            a.Name.ToString().Contains("Transform") && !a.Name.ToString().Contains("SkipTransform"));

                        if (hasSkipTransform)
                        {
                            // [SkipTransform] - read as-is
                            sb.AppendLine($"                        var {paramName} = reader.Read<{paramType}>();");
                        }
                        else if (transformAttr != null && transformAttr.ArgumentList?.Arguments.Count > 0)
                        {
                            // [Transform(typeof(T))] - use explicit transformer
                            var transformerTypeArg = transformAttr.ArgumentList.Arguments.First();
                            if (transformerTypeArg.Expression is TypeOfExpressionSyntax typeOf)
                            {
                                var transformerTypeName = typeOf.Type.ToString();
                                sb.AppendLine($"                        // Unbox {paramName} using explicit {transformerTypeName}");
                                sb.AppendLine($"                        var boxedBytes_{paramName} = reader.Read<byte[]>();");
                                sb.AppendLine($"                        var simpleType_{paramName} = MetaContext.GetSimpleType(typeof({transformerTypeName}));");
                                sb.AppendLine($"                        var boxed_{paramName} = serializer.Unpack(simpleType_{paramName}, boxedBytes_{paramName});");
                                sb.AppendLine($"                        var {paramName} = ({paramType})context.UnboxValue(typeof({transformerTypeName}), boxed_{paramName}!);");
                            }
                            else
                            {
                                sb.AppendLine($"                        var {paramName} = reader.Read<{paramType}>();");
                            }
                        }
                        else
                        {
                            // Auto-discovery - use compact helper
                            sb.AppendLine($"                        var {paramName} = context.ReadWithAutoUnbox<{paramType}>(reader, serializer);");
                        }

                        argNames.Add(paramName);
                    }

                    var callArgs = string.Join(", ", argNames);
                    sb.AppendLine($"                        service.{methodName}({callArgs});");
                }

                // Note: Triggers are broadcast separately by the server, not executed here

                sb.AppendLine($"                        break;");
                sb.AppendLine($"                    }}");
            }

            sb.AppendLine("                }");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        /// <summary>
        /// Info about a subscriber interface.
        /// </summary>
        private class SubscriberInterfaceInfo
        {
            public string Name { get; set; } = "";
            public string FullName { get; set; } = "";
            public System.Collections.Generic.List<SubscriberMethodInfo> Methods { get; } = new();
        }

        /// <summary>
        /// Info about a subscriber method.
        /// </summary>
        private class SubscriberMethodInfo
        {
            public string MethodName { get; set; } = "";
            public string EventTypeName { get; set; } = "";
        }
    }
}
