using ClanWars.Server;
using ClanWars.Shared;
using ClanWars.Shared.Server;  // generated MetaServiceCollectionExtensions.ConfigureMeta
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Orleans;
using Orleans.Configuration;
using Orleans.Hosting;
using SharedMeta.Core;
using SharedMeta.Server.Core;
using SharedMeta.Server.Core.Grains;
using SharedMeta.Server.Core.Session;
using SharedMeta.Server.Core.Storage;
using SharedMeta.Server.Core.Transport;
using SharedMeta.Serialization.MemoryPack;
using SharedMeta.Transport.SignalR;
using SharedMeta.Debug.Mux;
using OpenTelemetry;
using OpenTelemetry.Metrics;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;
using Serilog;
using Serilog.Events;

// Port can be passed as first arg (default 5050). Silo + gateway shift in lockstep.
var port = args.Length > 0 && int.TryParse(args[0], out var p) ? p : 5050;
var siloPort = 11111 + (port - 5050);
var gatewayPort = 30000 + (port - 5050);

var builder = WebApplication.CreateBuilder(args);
builder.WebHost.UseUrls($"http://localhost:{port}");

// Serilog: console + rolling file under logs/clanwars-{port}-YYYYMMDD.log.
// One file per port keeps logs from multiple silos on the same host separable. The
// AspNetCore/Routing override mirrors the prior AddFilter(Warning) — Prometheus scraping
// /metrics every few seconds otherwise floods the file with per-request 3-line blocks.
builder.Host.UseSerilog((ctx, config) => config
    .MinimumLevel.Information()
    .MinimumLevel.Override("Microsoft.AspNetCore", LogEventLevel.Warning)
    .MinimumLevel.Override("Microsoft.AspNetCore.Hosting", LogEventLevel.Warning)
    .MinimumLevel.Override("Microsoft.AspNetCore.Routing", LogEventLevel.Warning)
    .Enrich.FromLogContext()
    .WriteTo.Console()
    .WriteTo.File(
        path: $"logs/clanwars-{port}-.log",
        rollingInterval: RollingInterval.Day,
        retainedFileCountLimit: 7,
        shared: true,
        outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level:u3}] {SourceContext} {Message:lj}{NewLine}{Exception}"));

var serializer = new MemoryPackMetaSerializer();
builder.Services.AddSingleton<IMetaSerializer>(serializer);

// Single shared provider — registered on the silo via ConfigureMeta below.
var configProvider = new ClanConfigProvider();
builder.Services.AddSingleton<IMetaConfigProvider<ClanConfig>>(configProvider);

// Cluster-wide client/server version policy. Both 1.0 and 2.0 clients accepted —
// per-client config branch decided per [MetaConfigVersion] rules on ClanConfig.
builder.Services.AddSingleton(new MetaTransportOptions
{
    ServerVersion    = "2.0.0",
    MinClientVersion = "1.0.0",
    MaxClientVersion = "2.x.*",
});

// Per-silo pool registry — single instance shared between the web host DI (for the /debug/pool
// endpoint) and the silo DI (where EntityGrain / SessionManagerGrain consume it). The startup
// task registered on the silo binds the SiloId on this same instance.
// Both toggles default OFF — opt in via env vars:
//   SHAREDMETA_ENABLE_POOL=1     route outgoing payloads through the pool (ref-counted)
//   SHAREDMETA_POOL_HISTORY=1    record per-slot Acquire/IncrementRef/Release stacks
var pooledOptions = new SharedMeta.Server.Core.Memory.PooledPayloadOptions
{
    UsePoolPath   = Environment.GetEnvironmentVariable("SHAREDMETA_ENABLE_POOL")  == "1",
    EnableHistory = Environment.GetEnvironmentVariable("SHAREDMETA_POOL_HISTORY") == "1",
};
var pooledRegistry = new SharedMeta.Server.Core.Memory.PooledPayloadRegistry(pooledOptions);
builder.Services.AddSingleton(pooledRegistry);

// Per-silo capability registry (signature → ClientCapabilities cache).
builder.Services.AddSharedMetaClientSignatureRegistry();
// Server signature — generated by SharedMeta.Generator from every [MetaService] + [MetaMethod]
// declaration in ClanWars.Shared. Carries the full per-method (ServiceName, Alias, Version,
// ArgHash, GenerateClientApi, GlobalIndex, ConfigTypeFullName) table consumed by the
// per-signature client→server method-id translation, plus the [MetaConfigStructureBoundary]
// declarations harvested from [MetaConfig] classes (here: ClanConfig 2.0). A hand-crafted
// stub used to live here, but after the 0.24 wire-level methodId migration the registry
// needs the complete table to build a valid c2s map — incomplete tables caused all client
// RPCs to be marked Rejected.
builder.Services.AddSingleton(global::ClanWars.Shared.GameServiceDiscoveryBase.ServerSignature);

// ClanContainerService is a per-silo singleton that fronts the cluster-wide
// IClanContainerGrain. Hosted-service lifecycle handles hydration + periodic flush.
builder.Services.AddSingleton<ClanContainerService>();
builder.Services.AddSingleton<IClanContainerService>(sp => sp.GetRequiredService<ClanContainerService>());
builder.Services.AddHostedService(sp => sp.GetRequiredService<ClanContainerService>());

builder.Host.UseOrleans(siloBuilder =>
{
    siloBuilder
        .UseLocalhostClustering(siloPort, gatewayPort)
        .Configure<ClusterOptions>(options =>
        {
            options.ClusterId = "clanwars-cluster";
            options.ServiceId = "clanwars-server";
        })
        // 0.23.0+ Allocation hotfix: replace Orleans default JsonGrainStorageSerializer
        // with the MemoryPack-backed one. Per-stack allocation profiling traced ~50% of the
        // total server allocation budget (Strings + Char[] + StringBuilder + serialized Byte[])
        // to Newtonsoft.Json inside MemoryGrainStorage.WriteStateAsync. Switching to a binary
        // codec eliminates that bucket — see observability/allocation-profile.md, Stack profile #1.
        .AddMemoryGrainStorage("Default", o =>
            o.GrainStorageSerializer = new MemoryPackGrainStorageSerializer())
        .AddStartupTask<SharedMeta.Server.Core.Memory.PooledPayloadRegistryStartupTask>()
        .ConfigureServices(services =>
        {
            services.AddSingleton<IMetaSerializer>(serializer);
            services.Configure<EntityGrainOptions>(o =>
            {
                o.SubscriberTtl = TimeSpan.FromMinutes(10);
                // Debounced persistence — every state mutation marks the grain dirty, but
                // WriteStateAsync only fires when at least 10s have passed since the last save
                // (checked on each request, no background timer). Trades up-to-10s recovery
                // window for a roughly 10x drop in WriteStateAsync invocations under stress.
                o.PersistencePolicy = PersistencePolicy.EveryNMinutes(10);
            });

            // Make the same registry visible inside the silo (so MetaConnectionHandler
            // can pick it up via DI when constructing per-connection handlers).
            services.AddSharedMetaClientSignatureRegistry();
            services.AddSingleton(global::ClanWars.Shared.GameServiceDiscoveryBase.ServerSignature);

            // Per-silo pool registry — same instance as the web-host DI uses. SiloId is allocated
            // by the cluster-singleton IPooledPayloadRegistryCoordinator grain at startup
            // (see PooledPayloadRegistryStartupTask); the web-host /debug/pool endpoint reads
            // the same registry's DumpAllocatedSlots() to surface leak diagnostics.
            services.AddSingleton(pooledRegistry);

            // ConfigureMeta wires the generated provider factories.
            services.ConfigureMeta(svc =>
            {
                svc.AddSingleton<IMetaConfigProvider<ClanConfig>>(configProvider);
                // ClanService accesses this via Context.ResolveService<IClanContainerService>().
                svc.AddSingleton<IClanContainerService>(sp =>
                    sp.GetRequiredService<ClanContainerService>());
            });
        });
});

// SignalR wire — game grade timeouts.
builder.Services.AddSignalR(o =>
{
    o.EnableDetailedErrors = true;
    o.ClientTimeoutInterval = TimeSpan.FromMinutes(30);
    o.KeepAliveInterval = TimeSpan.FromMinutes(15);
    // 0.23.0+ Allow many concurrent hub-method invocations per connection. Default = 1,
    // which serializes ALL invokes from a single SignalR client at the hub-dispatch level.
    // With the Mux transport carrying 100+ simulated players on one socket, default = 1
    // turns every RPC into a head-of-line block; profiling showed client p95 of 2000 ms
    // against server-side processing of 5 ms (400× queue-time gap). 100 here corresponds
    // to the realistic mux fan-out width — increase further if a single socket carries more.
    o.MaximumParallelInvocationsPerClient = 100;
}).AddMetaMessagePackProtocol();

// Web-host (top-level) ClientVersionPolicy: SignalR's MetaHub resolves IMetaConnectionHandlerFactory
// from web-host DI, NOT from silo DI — the policy that ConfigureMeta() emits lives in the silo's
// container and is invisible here. Without this registration the per-connect version gate is OFF
// and the handler logs "ClientVersionPolicy is null" on every SessionConnect.
builder.Services.AddSingleton<ClientVersionPolicy>(sp =>
{
    var opts = sp.GetService<MetaTransportOptions>();
    var grainFactory = sp.GetService<IGrainFactory>();
    return new ClientVersionPolicy(opts?.ServerVersion, opts?.MinClientVersion, opts?.MaxClientVersion, grainFactory);
});

builder.Services.AddSingleton<IMetaConnectionHandlerFactory>(sp =>
{
    var grainFactory = sp.GetRequiredService<IGrainFactory>();
    var loggerFactory = sp.GetRequiredService<Microsoft.Extensions.Logging.ILoggerFactory>();
    var entityGrainResolver = sp.GetRequiredService<IEntityGrainResolver>();
    var transportOptions = sp.GetRequiredService<MetaTransportOptions>();
    var signatureRegistry = sp.GetService<IClientSignatureRegistry>();
    var versionPolicy = sp.GetService<ClientVersionPolicy>();
    // 0.24.0+ MetaConnectionHandler needs the server signature to translate inbound
    // RpcCall.MethodId (client-local index) into the server's GlobalIndex. Without it
    // every dispatch falls back to "unknown method" because the c2s-mapped server id
    // can't be resolved back to a (ServiceName, Alias) for the grain lookup.
    var serverSignature = sp.GetService<SharedMeta.Core.Transport.MetaServerSignature>();
    return new MetaConnectionHandlerFactory(
        grainFactory, entityGrainResolver, loggerFactory,
        transportOptions: transportOptions,
        serializer: serializer,
        versionPolicy: versionPolicy,
        signatureRegistry: signatureRegistry,
        serverSignature: serverSignature);
});

builder.Services.AddCors(o => o.AddDefaultPolicy(p => p.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader()));

// 0.23.0+ Observability: wire SharedMeta meters + activities into OpenTelemetry.
// Metrics scrape: GET http://localhost:{port}/metrics (Prometheus format).
// Console exporter is enabled so a developer can see deltas in stdout without setup.
builder.Services.AddOpenTelemetry()
    .ConfigureResource(r => r.AddService(serviceName: "ClanWars.Server", serviceVersion: "0.23.0"))
    .WithMetrics(m => m
        .AddMeter(SharedMeta.Server.Core.Telemetry.SharedMetaMeters.MeterName)
        .AddRuntimeInstrumentation()        // .NET GC, ThreadPool, JIT, exceptions
        .AddPrometheusExporter())           // /metrics endpoint
    .WithTracing(t => t
        .AddSource(SharedMeta.Server.Core.Telemetry.SharedMetaActivities.SourceName));
// Optional: uncomment to dump spans to console for local debugging.
// .WithTracing(t => t.AddConsoleExporter());

var app = builder.Build();
app.UseCors();
app.MapHub<MetaHub>("/meta");
// Mux endpoint — one SignalR socket carries N logical client sessions for stress tests.
// Production / regular clients keep using /meta; load tests connect to /meta-mux.
app.MapMetaMuxHub("/meta-mux");
// Prometheus scrape endpoint — point Grafana / Prometheus at http://localhost:5050/metrics
app.MapPrometheusScrapingEndpoint();

// Diagnostic: dump currently-allocated pool slots. Use this when the AllocatedSlots gauge
// in Grafana shows residual slots long after load stopped — each entry shows ref-count,
// payload length, acquire timestamp + age, and (if SHAREDMETA_POOL_HISTORY=1 was set at
// startup) the full Acquire/IncrementRef/Release call-stack chain.
//   GET /debug/pool                       → human-readable text dump
//   GET /debug/pool?minAgeSec=N           → only slots older than N seconds
//   GET /debug/pool?stacks=1              → include history dumps (verbose; only useful if EnableHistory)
app.MapGet("/debug/pool", (HttpContext ctx, SharedMeta.Server.Core.Memory.PooledPayloadRegistry reg) =>
{
    var minAgeSec = ctx.Request.Query.TryGetValue("minAgeSec", out var v) && double.TryParse(v, out var d) ? d : 0d;
    var includeStacks = ctx.Request.Query.TryGetValue("stacks", out var s) && s == "1";

    var snapshots = reg.DumpAllocatedSlots();
    var sb = new System.Text.StringBuilder();
    sb.Append("AllocatedSlotCount=").Append(reg.AllocatedSlotCount)
      .Append("  PoolEnabled=").Append(reg.IsEnabled)
      .Append("  HistoryEnabled=").Append(reg.EnableHistory)
      .Append("  SiloId=").Append(reg.IsInitialized ? reg.SiloId.ToString() : "<unbound>")
      .Append("  Now=").Append(DateTime.UtcNow.ToString("O")).Append('\n').Append('\n');

    int shown = 0;
    foreach (var snap in snapshots)
    {
        if (snap.Age.TotalSeconds < minAgeSec) continue;
        sb.Append("slot=").Append(snap.SlotIndex)
          .Append(" ref=0x").Append(snap.Ref.ToString("X8"))
          .Append(" refcount=").Append(snap.RefCount)
          .Append(" len=").Append(snap.Length)
          .Append(" acquired=").Append(snap.AcquiredAtUtc == DateTime.MinValue
              ? "<unknown>"
              : snap.AcquiredAtUtc.ToString("O"))
          .Append(" age=").Append(snap.Age.ToString(@"hh\:mm\:ss\.fff"))
          .Append('\n');
        if (includeStacks && snap.HistoryDump != null)
            sb.Append(snap.HistoryDump).Append('\n');
        shown++;
    }
    sb.Append('\n').Append("Total shown=").Append(shown).Append(" of ").Append(snapshots.Count).Append('\n');
    return Results.Text(sb.ToString(), "text/plain; charset=utf-8");
});

Console.WriteLine($"[ClanWars] Server listening on http://localhost:{port}");
Console.WriteLine($"           Orleans silo: {siloPort}, gateway: {gatewayPort}");
Console.WriteLine($"           Hubs: /meta (regular), /meta-mux (multiplexed stress-test transport)");
Console.WriteLine($"           Metrics: /metrics (Prometheus format)");
Console.WriteLine($"           ConfigBoundary: ClanConfig 2.0 (v1 clients force-ServerPatch on v2-pinned clans)");

await app.RunAsync();
